### ISSUE TITLE
Login and sharing identity

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#1]
As a learner, I can access my account by logging in with my 'private key'.

As a learner, I can share my identity with other players via my 'public key'.

**Comment by GBKS** [comment]
We will have the first ask in V1. Sharing public keys is a bigger design and tech process we'll have to tackle separately at a later stage.

**Comment by aureleoules** [comment]
The way I would implement this is to store the hash of the private key in the localStorage to serve a 'public key' when the user signs up, along with the user progress and avatar.
I don't think it's worth it to derive the actual secp256k1 public key and not sure how easy that is in javascript also.

When the user tries to login, they will provide their private key and we will hash it to make sure it matches our public key.

And is there a need for the public key (in a chapter for example)? Maybe we can just store the private key as is.

**Comment by aureleoules** [comment]
I'll work on "As a learner, I can access my account by logging in with my 'private key'.".
