### ISSUE TITLE
Show dynamic content in tabs on the chapters page

### ISSUE THREAD

**Issue by ggwilin** [saving-satoshi/saving-satoshi#10]
Currently, on the chapter overview we have 2 tabs, Info and Challenges

<img width="352" alt="Screenshot 2022-12-01 at 11 55 44 PM" src="https://user-images.githubusercontent.com/96985348/205235186-acb36b94-c043-4c37-94af-58c363a43b08.png">

Those tabs need to load the content dynamically, as shown in the figma, an overview in text, and the list of challenges 

Overview component already exists to load the chapter overview, you can find it in  `components/partials/Overview.tsx`

Overviewinfo, is the class that contains the tab groups (I was looking to link to other views but i think changing the Link inside Tab.tsx to a button that toggles the info would be possible), this class receives a Chapter type in its parameters, a chapter contains its lessons, we could load those in the "challenges" section

<img width="664" alt="Screenshot 2022-12-02 at 2 12 56 AM" src="https://user-images.githubusercontent.com/96985348/205236471-13d60b66-27f7-4821-98a5-b02b01b75aa7.png">

**Comment by GBKS** [comment]
Updated the title of this issue to be about showing dynamic content in the tabs - easier to tackle with a more defined scope.

**Comment by GBKS** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/695901/207537755-3616a524-6bd2-4c12-bd8d-69ca6c83dee5.png">

Here's the latest design, which added the check and lock icons to indicate completed and locked lessons (user needs to complete previous lesson before).

<img width="386" alt="image" src="https://user-images.githubusercontent.com/695901/207537942-a8039941-a38a-40e7-a82d-536dc5da3f7b.png">

We also need this state for chapters that are not unlocked yet (we don't want to give away the whole story right off the bat.

**Comment by vinayaksh42** [comment]
@GBKS I think the first part of this issue has been completed by the PR #86 (saving progress PR by you).

For the remaining part, we can lock the introduction for the chapters using the `getUserProgress` function at https://github.com/saving-satoshi/saving-satoshi/blob/master/lib/user.ts#L12
