### ISSUE TITLE
Mobile formatting issue and copy/paste bug

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#102]
Wanted to highlight a potential misalignment on the top. Are these supposed to be aligned horizontally?
![IMG_1327](https://user-images.githubusercontent.com/32662508/214409033-66744089-009f-4093-aee7-bbf613550f42.PNG)

Here the #'s are disappearing from the screen.
![IMG_1328](https://user-images.githubusercontent.com/32662508/214409223-accf0c19-f5a8-4b68-9f74-ad3f9befc670.PNG)

I'm also unable to paste into console in this challenge.
https://user-images.githubusercontent.com/32662508/214409402-8e2a2ec6-1e15-4181-947c-5a314549581a.MP4

_Originally posted by @ecurrencyhodler in https://github.com/saving-satoshi/saving-satoshi/issues/98#issuecomment-1402638223_

**Comment by 1t1e1** [comment]
Hi @GBKS. I will solve the first part of the issue in #116
- [x] Adding `items-center` to the navbar solved the layout problem.
- [ ] I will checked font size

**Comment by ecurrencyhodler** [comment]
Hi @1t1e1 and thanks for the fix! 

tACK. Tested on mobile. 

![IMG_1344](https://user-images.githubusercontent.com/32662508/215163847-d2248d8b-e21b-474b-8f19-b8da61af0edf.PNG)

**Comment by 1t1e1** [comment]
The font-size in Figma Mobile being 19px while on the website it is 20px. Right now I won't change it. 

I want to make a pixel-perfect design, however Tailwind does not work. There are many classes that do not apply to elements. There are several discrepancies between the design and website, such as the gap between chapters and about must be 30px. I must resolve these issues before I can start designing.

I will create a new issue regarding the tailwind config and work to resolve there.

I am changing my second todo to be "make pixel perfect design"

- [ ] make pixel perfect design

**Comment by GBKS** [comment]
@1t1e1 thanks for bringing this up. Adjusting the Tailwind config for font sizes is something that has been in the back of my mind, but I have not brought it up since we're still working through some more basic things in the site development. Would be amazing to make this change. I think the Figma files are pretty consistent in terms of font styles overall, but I can take a look and prepare a spec sheet if that's helpful. Let me know what you information you need.
