### ISSUE TITLE
OpCodeChallenges Advanced Challenge logic

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#1033]
We currently need to have advanced challenges with multiple success states before passing the lesson.

The example provided is for advanced challenge 2
https://github.com/saving-satoshi/challenges/blob/master/chapter9/README.md#advanced-challenge-2

### Steps

1. given a blank script and initial stack the block height should be pre-populated with `6930299`
2. this part of the challenge should succeed with the basic script of `OP_PUSH PUBKEY(VANDERPOOLE) OP_CHECKSIG` the only initial stack _required_ is `SIG(VANDERPOOLE)`
3. after filling in the script and initial stack there should be 3 ui changes
- `SuccessBar` should show a state like in `CH1GEN2` "looking good so far"
![image](https://github.com/user-attachments/assets/ae6510d2-5283-4b64-9b5a-646db6f34192)
- the initial stack should be cleared
- The block height should increment by 1 to `6930300`
- The script will no longer be editable
![image](https://github.com/user-attachments/assets/bfd0d118-1834-416d-bd7a-6fc51cef2c48)

4. the user may now input a new initial stack to pass the challenge completely
- this success script will be `OP_IF OP_PUSH PUBKEY(vanderpoole) OP_ELSE OP_PUSH 6930300 OP_CHECKLOCKTIMEVERIFY OP_DROP OP_PUSH PUBKEY(me) OP_ENDIF OP_CHECKSIG` and the initial stack must equal `SIG(ME) 0`
5. On a failure of the second part, the user has two options, continue tweaking the initial stack until they get the correct answer or try again like in chapter 7. however, unlike chapter 7 this try again button in the successBar will reset the state back to step 1
![image](https://github.com/user-attachments/assets/c83e9dd9-b0e2-47d1-b9a9-7f400303e1c2)

#### additional tweak
we should add a optional param that can check the user's initial stack to make sure they are inputting the correct initial stack for a challenge

**Comment by benalleng** [comment]
@pinheadmz we created a logic board for our advanced challenges that we would appreciate a quick read

**Comment by pinheadmz** [comment]
![Screenshot 2024-08-05 at 3 20 10 PM](https://github.com/user-attachments/assets/677acfcf-2aef-49c4-b506-cda1d5468d2a)

Just brainstorming here... let the user switch between the two stacks and check their script against both?
