### ISSUE TITLE
OpCode Challenge Design cleanup

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#1038]
We've made great progress on our opcode challenge but I think we should maybe make a small list about things we really would like as nice-to-haves while they are fresh.

They can be anything, design, ux/ui, speed, difficulty, etc.

**Comment by daviroo** [comment]
@GBKS made a comment in our last call that it would be good to have some subtle animations in the script runner.  I'm going to take a look into our options around that and follow up here.

**Comment by benalleng** [comment]
I am going to create a small render function to create colored borders on opcodes of type constant and push-data like so to make it clear what is being added

![image](https://github.com/user-attachments/assets/386bedc3-09ba-45d2-8c5b-6bf87670478e)
