### ISSUE TITLE
Chapter 6, put-it-together-3-normal: stale lesson name in instructions

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1070]
In Chapter 6's put-it-together-3-normal challenge, the instructions mention something called "Populate the Input". I couldn't find it in the list of challenges for this chapter. Is this an old challenge name? Is it supposed to be a link? An easy fix could be to replace it with "an earlier exercise".

![Screenshot from 2024-08-30 14-51-25](https://github.com/user-attachments/assets/c1f84da6-60e1-49db-950a-bda8bdeee91e)

**Comment by benalleng** [comment]
I just changed the text to be "(the UTXO we identified in <ins>The input class</ins>)"

**Comment by satsie** [comment]
That works for me. Closing!
