### ISSUE TITLE
Add tabs and tab logic to challenges

### ISSUE THREAD

**Issue by ggwilin** [saving-satoshi/saving-satoshi#11]
Currently, some elements are not responding perfectly, it is necessary to check out those 

having things like this, would make everything easier, mobile-first approach

<img width="598" alt="Screenshot 2022-12-02 at 2 49 54 AM" src="https://user-images.githubusercontent.com/96985348/205242670-37b90ea0-f6aa-4149-ba58-b5c2b93ea5fd.png">

**Comment by GBKS** [comment]
I updated the title of this issue to be more precise - adding tabs and the corresponding logic to challenge pages. This was it's easier to code & review.

**Comment by GBKS** [comment]
I started this via #48 for one page so we can fine-tune the technique.

**Comment by GBKS** [comment]
I created separate per-page issues with #67, #68, and #69. So closing this one.
