### ISSUE TITLE
Improve readability of the signup modal

### ISSUE THREAD

**Issue by sabakhilji** [saving-satoshi/saving-satoshi#111]
I might be wrong so please close this issue if preferred.

I think the profile page font is not clear enough to read:
For example this text on the profile page:

Copy and store a simple code to save and load your progress on any device and browser. If you already have a code, load your progress here.
 
It's hard to read. Letters are mixed up

I believe either changing the background color or font size and text style may resolve this problem.

**Comment by vinayaksh42** [comment]
Yes, I think the font is a bit small. We can simply increase the font size for desktop-view in order to fix this issue

Currently : 
![Screenshot 2023-01-27 at 9 28 09 PM](https://user-images.githubusercontent.com/54861487/215131429-7ae07f98-db57-48f5-b41a-65d95fbcf0bb.png)

After increasing the font:
![Screenshot 2023-01-27 at 9 29 05 PM](https://user-images.githubusercontent.com/54861487/215131546-39690aec-f615-4a53-9786-01aea2a12f87.png)

**Comment by sabakhilji** [comment]
Yes, thanks @vinayaksh42, I guess in order to make the profile page more accessible this will work :)

**Comment by GBKS** [comment]
That screenshot looks really problematic, the font does not render correctly. Can you let me know which operating system and browser you use? And do you have any browser scaling or any accessibility options enabled that could affect scaling?

The designs are not correctly implemented. Per [design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1112%3A14118&t=JfZedXfIQ4Yy63mE-1), the modal text should use Nunito and not Caveat Brush, and the font sizes should be larger.

For any design requests, let's make sure to go through Figma first before jumping into implementation.

**Comment by GBKS** [comment]
I renamed the title of this issue, as "improve profile" page did not properly descriptive the matter.

**Comment by sabakhilji** [comment]
Hey, thanks,@GBKS to rename the issue for clarity. In my case, OS is Windows 10 ,64 bit and the web browser is Firefox.
Also, no accessibility option is enabled on my browser.

**Comment by ecurrencyhodler** [comment]
This issue still persists. Styling is not properly implemented.

**Comment by vinayaksh42** [comment]
@ecurrencyhodler, I would like to take on this issue and try to implement the styling with a pixel-perfect approach or as close to the Figma mockup as possible.

**Comment by ecurrencyhodler** [comment]
Amazing! Thank you so much! I've moved the issue to in progress and assigned it to you. 🫡
