### ISSUE TITLE
Change the Mining Reward Amount from the 51% Attack

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1111]
This is a high priority ticket and something we'd like to do before TABConf. In chapter 3 you and your friends pool your hashpower together to overcome Bitrey's 51% attack. The current reward for all that mining is 6.1 BTC. To avoid any confusion with the meme, we are changing that number to 7.36 BTC.

These are the screens in chapter 3 that need updating:

https://savingsatoshi.com/en/chapters/chapter-3/split-1
![Screenshot from 2024-10-07 12-14-02](https://github.com/user-attachments/assets/29a7e0cb-fba1-4de7-badc-8bd4dd065b8c)

https://savingsatoshi.com/en/chapters/chapter-3/split-2
We have the user getting 21.74% share of the rewards. By some stroke of luck, 21.75% of our original 6.1 BTC is NOT 1.61! So that makes our lives easier! I worked backwards from this to get our new total reward of 7.36 BTC, where 21.74% works out to 1.61 so no need to make any updates to the challenges in chapter 4 :)
![Screenshot from 2024-10-07 12-12-27](https://github.com/user-attachments/assets/e15f8359-311a-4113-a675-28689d36f103)

**Comment by satsie** [comment]
I can take this ticket later this week but if anyone can get to it before me, feel free to grab it!

**Comment by benalleng** [comment]
Closed by #1114
