### ISSUE TITLE
Lost part of my progression after loging out. Stuck in chapter 6

### ISSUE THREAD

**Issue by kaiosatiro** [saving-satoshi/saving-satoshi#1124]
I stepped on this issue and thought it was a good idea to share it with you all.

**Describe the bug**
After I logged out and logged in again using my private key, my progression after chapter 6 was lost.
I had saved all my code answers with me, so I could paste them to recover. However, when I finished chapter six again, the next one was not liberated, it just sent me to the chapter page.

So I tried in hard mode, but after submitting the code for the "Input Class" exercise, the page sent me to a 404 page.

**To Reproduce**
In easy mode:
1. I finished all the steps and could see the congrats page.
2. Backing to the chapters page, the ch 7 is still blocked.

In hard mode:
1.  When submitting the "Chapter 6, The ins and outs input class", I got a successful answer.
2. Clicking the next button sends me to a 404 page.

**Expected behavior**
Normal advancing through the chapters

**Screenshots and/or logs**
The easy mode issue: (Chp 7 is still blocked)
![image](https://github.com/user-attachments/assets/b8cc7c1b-a1f7-4732-ac7f-5b3efd673dac)

Hard mode:
![image](https://github.com/user-attachments/assets/3e4e5a2c-71ab-4bf4-a5bd-fed56cc7d805)
![image](https://github.com/user-attachments/assets/046e1fbd-e613-44a0-8b6d-f18a995c828c)

**Desktop (please complete the following information):**
I'm using Firefox and Brave in Arch Linux.

**Additional context**
This happened after I logged in again using the private key. Before I logged out, it happened a similar thing the issue #1071.

**Comment by benalleng** [comment]
Do you mind sharing the account key for this?
I want to see what in the progress object has broken to cause this behaviour.
Also I will likely be able to go in and hand edit the progress object to fix it for you so you can restore your progress

**Comment by benalleng** [comment]
also do you have the exact link that was the 404 page?

**Comment by kaiosatiro** [comment]
Sure!

**Comment by kaiosatiro** [comment]
Sure !
The page: https://savingsatoshi.com/en/chaptersnull
The key: ef588ef6e333ddf29dfcd9905edfec478da3bc0c4fa653c863b4813028d8c516

I wish I could provide more information about it.

**Comment by benalleng** [comment]
Thanks! Did you fully complete any chapters beyond chapter 6? or did you finish chapter 6 in `normal` mode and then immediately try again in `hard` mode

**Comment by kaiosatiro** [comment]
I finished up to the 9 ch, not the 10th. This in normal mode.

**Comment by benalleng** [comment]
Ok! progress should be fixed up so you should be able to proceed and access any chapter that you have already completed even after switching difficulty. Let me know if you can confirm you are able to proceed

**Comment by kaiosatiro** [comment]
Yes, everything is working now. And the new features are pretty neat. Thanks!

**Comment by kaiosatiro** [comment]
Yes, everything is working now. And the new features are pretty neat. Thank you.
