### ISSUE TITLE
Add Portuguese Brazil language.

### ISSUE THREAD

**Issue by kaiosatiro** [saving-satoshi/saving-satoshi#1133]
**Describe the enhancement**
If your team doesn't have someone working on Brazilian Portuguese translation, I would like to help with that!
I have many new developers who annually participate in seminars with BTC developers who would be helped with this project.

(edit) I have read the [README](https://github.com/saving-satoshi/saving-satoshi/blob/master/i18n/README.md) for translations and understood how to do it.

**Comment by satsie** [comment]
Hi @kaiosatiro! Thank you so much for offering to work on this! To my knowledge there isn't anyone currently working on a Brazilian Portuguese translation, and we would absolutely love to take you up on this! 

We're still finishing up chapter 10, so the text for that chapter may have a few more changes, but the rest of the chapters are ready to be translated. Thank you and reach out if there's anything we can do to support you in this!

**Comment by biohazel** [comment]
Hi @kaiosatiro. I'm the translator of Mastering the Lightning Network into Brazilian Portuguese and founder of [@Scalar-School](https://github.com/Scalar-School) of Bitcoin developers. Let me know how I can support you in translating Saving Satoshi if you need help.

**Comment by kaiosatiro** [comment]
hey @biohazel, appreciated!

**Comment by benalleng** [comment]
Begun chapters 1-4 with #1155

**Comment by kaiosatiro** [comment]
All ten chapters were translated, but, was only able to review up to chapter 4 on the local build. For some reason, at the last challenge of chapter 4, I can't go forward.

**Comment by benalleng** [comment]
We just had a breaking change on #1153 for the backend. Make sure you are rebased up to dev on your local branch

**Comment by benalleng** [comment]
Closed by #1155
