### ISSUE TITLE
Chapter 10 prefill the output field

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#1138]
> Since the scripts are getting more complicated, i think it would be nice if the last script we wrote was still there in the output field so i just have to add the time lock, instead of having to debug the entire script again

**Comment by benalleng** [comment]
Do we want this on all the lessons? I am a little worried about how much of a redesign this would need.

**Comment by satsie** [comment]
Implementing this would help address feedback we have gotten from several testers: It would be nice to be able to copy and edit a previous answer so it can be submitted as solution to the current challenge. However, as discussed in #1182, persisting user answers would require overriding default challenge code with user code. That doesn't seem to be worth the complexity as we can achieve the same thing (users not having to rewrite the same code a bunch of times) with some default challenge code that happens to be the answer to the previous challenge.

**Comment by satsie** [comment]
> Do we want this on all the lessons? I am a little worried about how much of a redesign this would need.

If everyone's challenges are prefilled with the same code, as opposed to individual user code, does this make it less of a redesign?

**Comment by benalleng** [comment]
My follow up now is what page to prefill and what to prefill them with?
here are the individual challenge pages
- [ ] opening a channel - 2
- [ ] opening a channel - 4
- [ ] updating the state - 1
- [ ] updating the state - 3
- [ ] updating the state - 3
- [ ] making a payment - 2
- [ ] making a payment - 5
- [ ] making a payment - 8

**Comment by satsie** [comment]
That list makes sense to me. For a few of the challenges I see that the copy idea you proposed earlier probably does make sense, specifically for these two screens:

**making-a-payment-2**: copy to remind the user to switch to the refund tab to see the previous refund/commitment transaction. (unrelated note: I think it's confusing that in this point of the game we use both terms (refund and commitment) but it makes sense considering the user learned of it as a refund before they were introduced to commitment transactions in making-a-payment-1)

**making-a-payment-5**: copy to tell the user they can look at the commitment_you tab to see the script in their commitment transaction

I'm happy to pick this up if no one else gets to it before me.

**Comment by benalleng** [comment]
| making-a-payment-2: copy to remind the user to switch to the refund tab to see the previous refund/commitment transaction. (unrelated note: I think it's confusing that in this point of the game we use both terms (refund and commitment) but it makes sense considering the user learned of it as a refund before they were introduced to commitment transactions in making-a-payment-1)

Using this code, we can change the name of "refund" to "initial commitment / commitment"
https://github.com/saving-satoshi/saving-satoshi/blob/1b2914c77a138ab453684b32fe74222d1d8d4ed6/ui/lesson/TransactionsChallenge/index.tsx#L178-L206

**Comment by benalleng** [comment]
Will make a new issue about the copy. otherwise closed by #1239
