### ISSUE TITLE
Help with translation into Russian.

### ISSUE THREAD

**Issue by ArtoymKryazhev** [saving-satoshi/saving-satoshi#1157]
Hello. I am from Russia. My name is Artem and I am 19. I came across your game in one of the Russian Telegram channels. I would like to offer you my help with translation into Russian. Exclusively in a voluntary form.

**Comment by benalleng** [comment]
Thats great! feel free to check out the translating README https://github.com/saving-satoshi/saving-satoshi/blob/dev/i18n/README.md and let us know if you have any other questions in our bitcoin design discord

**Comment by satsie** [comment]
Amazing!! Thank you so much for you interest in helping with this! Tagging @aassoiants in case he can be helpful for review :smile:

**Comment by aassoiants** [comment]
@satsie ha! My proofreading would need some proofreading!

**Comment by satsie** [comment]
This issue is a duplicate of https://github.com/saving-satoshi/saving-satoshi/issues/1194 so I am closing this one!
