### ISSUE TITLE
Script editor: add space to OP_PUSH

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1170]
This is super nit picky but I think it will make a difference. In the script editor (https://script.savingsatoshi.com), there is the OP_PUSH opcode. Can we please add a little more space after OP_PUSH, before the content that the user populates?

Before:
![Screenshot from 2024-11-10 14-59-51](https://github.com/user-attachments/assets/c6f6c1bf-fa6d-4588-bcfc-af1867780058)

Here's an example of what it could look like after. I'm open to adding even more space that what this mock up has.
![new_op_push](https://github.com/user-attachments/assets/06aa8c64-925f-4dc2-be7a-71c2b3f80839)

The reason I ask is because I think we can make it more clear that OP_PUSH is a separate opcode from whatever the user enters. When I was playing chapter 10 I didn't see there was a copy script button so I manually wrote the script based based on my success in the script editor and, without paying much attention, entered OP_PUSH(SIG(YOU)) because having it all in the same building block made me think it was supposed to be treated as one unit. I think adding space here would help.

**Comment by benalleng** [comment]
Closed moving to the script editor issue
