### ISSUE TITLE
The year is 2139?

### ISSUE THREAD

**Issue by carnhofdaki** [saving-satoshi/saving-satoshi#1172]
Please use some other year and maybe add a month for fun. Let people think and realize if there was some 2140 prediction, it might have been current at the time of that prediction but is being slightly adjusted with every mined block.

See [my always current prediction](https://display.anyone.eu.org/test.html#6930000)\*.

Search for word `2139` in this repository and you find the files in `i18n` directory: https://github.com/search?q=repo%3Asaving-satoshi%2Fsaving-satoshi%202139&type=code

\* in the top-right corner of my prediction there is a [short kode](https://anyone.eu.org/skm.txt)

**Comment by satsie** [comment]
Hi @carnhofdaki thanks for filing this issue! I notice we have a discrepancy in chapter 10 where we say the year is 2140, but in chapter 1 it's 2139. Is this what this ticket is referring to?

This project was started over two years ago so you are correct that that prediction has since changed :)
