### ISSUE TITLE
ch 10: incorrect input amount in refund transaction

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1175]
In chapter 10, updating-the-state-1 (https://savingsatoshi.com/en/chapters/chapter-10/updating-the-state-1), the user creates a refund transaction for the 2-of-2 multisig they make with Laszlo in the previous exercise. In that exercise you need to set aside 1000 sats for miner fees, making a total of 100,000 sats locked in the multisig.

In this exercise, the multisig transaction is the input. In the screenshot below you can see that the input amount is 101,000 sats, but it should really be 100,000 sats.

![Screenshot from 2024-11-12 14-32-18](https://github.com/user-attachments/assets/e5e25c2a-bdc1-46c4-9ddb-7b9d947310a8)

This is also true for the updating-the-state-3 (https://savingsatoshi.com/en/chapters/chapter-10/updating-the-state-3) exercise: 
![image](https://github.com/user-attachments/assets/5b13aa7d-044b-4133-af83-e59658cdcb5d)

**Comment by satsie** [comment]
As I continue to QA chapter 10, I see that this issue impacts subsequent exercises. Here's a comment on how the Laszlo + you amount should probably end up to be 99,000 sats: https://github.com/saving-satoshi/saving-satoshi/pull/1174#discussion_r1842343476

![Screenshot from 2024-11-14 13-37-26](https://github.com/user-attachments/assets/c090d0ca-4942-4cae-a221-b70e3e7aeac0)

**Comment by satsie** [comment]
I need to retest this. I believe it has been fixed.

**Comment by benalleng** [comment]
with #1174 and #1195 now merged I think we did finally fix this issue

**Comment by benalleng** [comment]
I am going to close this as I am confident that we fixed our sats amounts
