### ISSUE TITLE
ch 10, updating-the-state-3, updating-the-state-5: Cannot press button for Laszlo to sign

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1177]
The revocation transaction exercise in chapter 10 (updating-the-state-3 https://savingsatoshi.com/en/chapters/chapter-10/updating-the-state-3?dev=true) has you adding a condition to the refund transaction so Laszlo can sweep the funds if you try to broadcast the refund transaction after it's been revoked. Laszlo is supposed to be the one to sign the transaction to complete the exercise, but 1. his sign button is disabled, and 2. I am able to finish the lesson if I press the sign button for me. 

Expected result: to complete the exercise you should have to press the sign button for Laszlo. This is part of the instructions, which I made minor tweaks to based on Christoph's feedback.

![image](https://github.com/user-attachments/assets/e5b41b04-f458-48f2-aeba-454d99944446)

The same issue is present for the next exercise, updating-the-state-5 (https://savingsatoshi.com/en/chapters/chapter-10/updating-the-state-5?dev=true)

![Screenshot from 2024-11-13 14-18-12](https://github.com/user-attachments/assets/83d7bf4d-9564-4c94-969c-7729740931c5)

**Comment by benalleng** [comment]
I think this got a little lost in translation with the figma => challenges repo => site

We decided to go with just pending as the continue button really is taking us to the page where laszlo will decide whether he will sign or not

**Comment by satsie** [comment]
Oooo I see. But I don't believe we should be signing these transactions at all, per Holocat's Trustless Warning:

![Screenshot from 2024-11-21 21-15-13](https://github.com/user-attachments/assets/10164969-1b4a-4858-8bf7-b982381b6068)

If that is the case, the sign button for us should not light up and become enabled for either of these challenges. Instead, we would probably want to press a "Continue" button, which would trigger the code that check's if the user's solution is correct.

**Comment by benalleng** [comment]
Closing as we now use a "send to laszlo" button
