### ISSUE TITLE
ch 10, making-a-payment-6: Prompt user to send revocation key to Laszlo

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1189]
This issue came out of Matthew's ch 10 QA: https://github.com/saving-satoshi/saving-satoshi/issues/1176

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-6?dev=true

clicking "continue" goes to next page but what is missing is literally "send REVOCATION_YOU_1 to laszlo

We can fix this by updating the copy to explain that by pressing the button, they will send the revocation key to Laszlo.

**Comment by satsie** [comment]
I'd like to take this one because I already have a lot of pending copy changes for this page.

**Comment by satsie** [comment]
> I think I inadvertently fixed this in #1198

I think I need to change this then, right? https://github.com/saving-satoshi/saving-satoshi/pull/1201/files#diff-442dbc2f4ed1e9dda2d52ecf1ca8a2e2db5615ab7efa1ce8fd17f0a08bfcf2faR2823

**Comment by benalleng** [comment]
ahh ok nvm I fixed something else

**Comment by benalleng** [comment]
Think we should just change the status bar text for this?
`Let's move on to the last challenge!`

**Comment by satsie** [comment]
> Think we should just change the status bar text for this? `Let's move on to the last challenge!`

I like this idea, but I saw the `status_bar.skip_challenge_last` translation key was generalized to many challenges so I didn't want to start mucking around with it.

I just rebased https://github.com/saving-satoshi/saving-satoshi/pull/1208 to mention `REVOCATION_YOU_1` in the last sentence (which is somewhat related to the comments you left on the PR to double check the names of the revocation keys :slightly_smiling_face: ). Here's what the copy looks like with the update in that PR:

![Screenshot from 2024-11-29 11-42-32](https://github.com/user-attachments/assets/e48fa1d4-059c-4bdd-81a5-ab9636075610)

**Comment by satsie** [comment]
Fixed in https://github.com/saving-satoshi/saving-satoshi/pull/1208
