### ISSUE TITLE
Complete the top bar and nav components shown in challenges

### ISSUE THREAD

**Issue by ggwilin** [saving-satoshi/saving-satoshi#12]
Tabs in lesson-1 are not seeing accordingly to figma files, you can get the information on `components/chapters/partials/TabGroup.tsx`

<img width="133" alt="Screenshot 2022-12-01 at 11 56 50 PM" src="https://user-images.githubusercontent.com/96985348/205242820-184ae6f5-60de-439d-a485-659c74a58513.png">

Things should look more like: 
<img width="345" alt="Screenshot 2022-12-02 at 2 52 37 AM" src="https://user-images.githubusercontent.com/96985348/205243199-a3549bc8-3b45-4720-9617-130f1d1d97d5.png">
 mobile: 
<img width="123" alt="Screenshot 2022-12-02 at 2 52 43 AM" src="https://user-images.githubusercontent.com/96985348/205243231-34ac3d15-2726-42e5-ae99-9127754d4399.png">

**Comment by GBKS** [comment]
This is partially fixed on desktop. Still needs the proper completed state with the small checkmark. For mobile, we need to switch out the component altogether because it's just too different to just be done with some CSS.
