### ISSUE TITLE
Research a11y tooling

### ISSUE THREAD

**Issue by SamSamskies** [saving-satoshi/saving-satoshi#120]
We should install some tooling to help us write more accessible code.

![Screenshot 2023-01-31 at 3 53 54 PM](https://user-images.githubusercontent.com/3655410/215892278-a1366cdb-ea03-4af5-8b6f-d11413e15425.png)

At minimum we should probably install https://www.npmjs.com/package/eslint-plugin-jsx-a11y and https://www.npmjs.com/package/@axe-core/react.

**Comment by sabakhilji** [comment]
Great, by default, eslint-plugin-jsx-a11y tool comes pre-packaged with any app that you create via create-react-app.  the only problem is error or warning message will come in the browser console. If we want to check accessibility issues in code editor we need to explicitly install extension for this tool.
