### ISSUE TITLE
ch 10: mixed case allowed in script area

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#1209]
This was originally filed as part of https://github.com/saving-satoshi/saving-satoshi/issues/1176 for the section on https://dev.savingsatoshi.com/en/chapters/chapter-10/updating-the-state-1?dev=true

The (very minor) issue is we are allowing mixed case in the script area. Everything the user types should be converted to uppercase.

Original text for issue:

> Nit: if you look at the multisig tab the script is mixed case: OP_2 OP_PUSH PUBKEY(Laszlo) OP_PUSH PUBKEY(You) OP_2 OP_CHECKMULTISIG

I'm opening an issue for it because it was checked, but per https://github.com/saving-satoshi/saving-satoshi/pull/1195#issuecomment-2498790655, it does not appear to be fixed (or there was a regression)

**Comment by benalleng** [comment]
Closed by #1210
