### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#121]
Right now Saving Satoshi only supports English but by adding translations we can increase accessibility and improve the user experience.

The idea behind the new architecture (#118) is to define the translations in the same file where they will be utilized. I'm a bit on the fence about whether that is a good idea or if maybe we should have a single file containing all translations (or group them based on locale) to prevent collisions between translation keys. 

Anyway, the solution I propose for now is to create a `useTranslations` hook that we can use from anywhere within our codebase. It returns a function `t` you can use like this:

```jsx
export default function Genesis() {
  const t = useTranslations()
  
  return <>
    <span>{t('genesis.paragraph_one')}</span>
  </>
}

export const translations = {
  en: {
    genesis: {
      paragraph_one: `Let's find the very first block in the Bitcoin blockchain...`
    }
  }
}
```

The `useTranslations` hook should take care of the getting the right `locale` from the users' browser settings, or we could create a language selector in the Topbar. It then finds the correct translation key-value pair using the key that was passed to the function and returns the corresponding value.

Like I mentioned during our call on `January 31, 2023` I think it might prove to be difficult to combine this with the Tooltip functionality that we have planned. It would be ideal if we could define our translations using `jsx`, but I'm not sure that's the way to go if we want to outsource the translation work at some point in the future.

So what I propose instead is that we create some logic that will find and replace parts of the strings that we mark as being a tooltip. My first thought was to use markdown syntax:
```jsx
export const translations = {
  en: {
    genesis: {
      paragraph_one: `Let's find the very first [block](genesis.tooltip) in the Bitcoin blockchain...`,
      tooltip: `A block refers to ...`
    }
  }
}

```
But since the text we target could be a clickable link at the same time this doesn't work very well since we cannot pass a href (unless we come up with our own syntax). Perhaps instead we can do something like this:
```jsx
export const translations = {
  en: {
    genesis: {
      paragraph_one: `Let's find the very first <Tooltip content="genesis.tooltip" href="...">block</Tooltip> in the Bitcoin blockchain...`,
      tooltip: `A block refers to ...`
    }
  }
}
```
This approach feels like you're writing jsx, which is nice. While at the same time it still allows us to store our translations as strings, which is good for third party translation tools. On the flip side this might be a little verbose. I'm open to alternative solutions that allow for both translations and tooltips to interface nicely.

It might be a good idea to establish some requirements first though, so let's use this issue to discuss.

**Comment by SamSamskies** [comment]
What do you think about using a library for the localization? Seems like it would be much easier. I've used `react-intl` before and it works great. https://formatjs.io/docs/react-intl/. I could make a spike branch if people would be interested in seeing how things would work with `react-intl`.

**Comment by SamSamskies** [comment]
The tooltips would also be very simple if we use `react-intl`.

**Comment by afterburn** [comment]
Hi @SamSamskies, I appreciate your suggestion! I was actually hoping someone would recommend a library that would work well with our `<Tooltip>` component. If you believe `react-intl` can meet that criteria, I'm definitely open to trying it out. It would be ideal if we could keep the translations close to the content where they are being used though, like in my draft, but I'm sure you'll be able to figure out a way to do that.

**Comment by SamSamskies** [comment]
>  It would be ideal if we could keep the translations close to the content where they are being used though, like in my draft, but I'm sure you'll be able to figure out a way to do that.

There's tooling that allows you to keep the messages close to where they're defined. At Strike we use [extract-react-intl-messages](https://www.npmjs.com/package/extract-react-intl-messages) to extract all the messages into one file per locale.

When I have some time I can do a small spike just to demonstrate an example of using it with this codebase.

**Comment by afterburn** [comment]
Sounds good, thanks @SamSamskies
