### ISSUE TITLE
ch 10 nits

### ISSUE THREAD

**Issue by pinheadmz** [saving-satoshi/saving-satoshi#1219]
https://script.savingsatoshi.com/?lesson=CH10MAP2

- [x] I wish it were also possible to type the script in (or paste) instead of always dragging

https://dev.savingsatoshi.com/en/chapters/chapter-10/updating-the-state-1?dev=true

- [x] I think we should be explicit that the multisig transaction is still off chain. With left-side copy and also the "Multisig" tab on the right could have disabled "sign and broadcast" buttons, or something?

https://dev.savingsatoshi.com/en/chapters/chapter-10/updating-the-state-5?dev=true

- [x] "Send it to Laszlo by clicking Sign so he can sign it" should say "Send it to Laszlo by clicking **Send to Laszlo** so he can sign it"

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-1?dev=true

- [x] "You to get all 100,000 satoshis back after 700 blocks, or" technically, it would only be 99,000 because YOU'd have to pay a fee to close the channel

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-2?dev=true

- [x] "This is your version of the commitment transaction." Is foreshadowing because we haven't revealed the asymmetry yet but still technically correct. It could just say "This is the second commitment transaction for this payment channel, that pays Laszlo 1,000 sats"

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-5?dev=true

- [x] #1225

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-6?dev=true

- [x] It would be great if the button to continue said literally "send REVOCATION_YOU_1 to laszlo"

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-7?dev=true

- [x] #1227

https://dev.savingsatoshi.com/en/chapters/chapter-10/making-a-payment-8?dev=true

- [x] when you get commitment_laszlo right it says "nice! let supdate your commitment!" but the button says "try again" and when pushed I think it resets the input fields

https://dev.savingsatoshi.com/en/chapters/chapter-10/outro-1?dev=true

- [ ] Technically there should be a "send REVOCATION_YOU_2 to laszlo" before we get beer number two

**Comment by benalleng** [comment]
> Technically there should be a "send REVOCATION_YOU_2 to laszlo" before we get beer number two

We sort of do already have this in the instructions, so for the sake of keeping the outro page clean of any additional instructions I think I'll leave this is a won't fix
