### ISSUE TITLE
Terminal at "Result Computing..." state, even with the correct code

### ISSUE THREAD

**Issue by joaoguimaraens** [saving-satoshi/saving-satoshi#1235]
**Describe the bug**

When I try to execute the code on the terminal at **Chapter 2. Automation: 3. Build a hash function**, it only shows the message: "Result Computing...". After one minute or two, the "Running..." label at the bottom changes to "Run the script" again, and nothing happens if I click.

**To Reproduce**

1. Go to **Chapter 2. Automation: 3. Build a hash function**
2. Try to run the code provided at **?** section in JavaScript or Python
3. The terminal doesn't return any message, just shows "Result Computing..."

**Screenshots and/or logs**

![image](https://github.com/user-attachments/assets/348c862c-96ea-4dca-ab17-5046092e9fb9)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Arc, Brave

**Comment by joaoguimaraens** [comment]
Now it's showing a "Repl timed out" response:

![image](https://github.com/user-attachments/assets/644c0fdc-efa7-47c3-8fcf-affac90b3ef5)

**Comment by benalleng** [comment]
Those are similar errors, one just correctly presented the error to the user and the first time it did not. I reset the backend last night but unfortunately it did not fix our problem I am taking a closer look this morning.

**Comment by benalleng** [comment]
Ok! we increased our timeout substantially, now 60s. It seems to work now, but please let me know when you get a chance to test it

**Comment by benalleng** [comment]
As well we improved the error handling in #1238

**Comment by joaoguimaraens** [comment]
![image](https://github.com/user-attachments/assets/a2b33faf-19f8-43e0-b3e4-99c080ab026d)

Worked very well!
Many thanks.
