### ISSUE TITLE
layout issues on the chapters page for Mobile view

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#127]
**Describe the bug**
According to the [Figma mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=372%3A3024&t=AbXTb7lnzN43hvk4-0) the content for `info` and `challenge` tab is to be displayed individually but currently it is being displayed next to each other (hidden but still occupying space) causing empty space.

**Screenshots**
<img src="https://user-images.githubusercontent.com/54861487/216344648-80665518-2b8d-44da-90a4-903560462bdd.png" width="200" height="400">
<img src="https://user-images.githubusercontent.com/54861487/216344674-608154aa-ded9-4968-8fc0-951555cc20b2.png" width="200" height="400">

**To Reproduce**

1. Go to https://savingsatoshi.com/chapters
2. Either open in Mobile or Change to Mobile view using device toolbar
3. See error

**Smartphone**

- Device: [e.g. iPhone13 pro]
- OS: [iOS 16.2]
- Browser [Safari]

**Comment by ecurrencyhodler** [comment]
Great catch. You're right. It should look like this where text spans across the whole screen.
<img width="378" alt="Screenshot 2023-02-02 at 7 14 01 AM" src="https://user-images.githubusercontent.com/32662508/216363653-bb7de067-a24b-4553-a06e-e121088ac2fe.png">
