### ISSUE TITLE
StatusBar not at the bottom of the page in mobile view

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#128]
**Describe the bug**
According to the [Figma mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=379%3A10942&t=AbXTb7lnzN43hvk4-0) the `StatusBar` is supposed to be at the bottom of the page for mobile view

**Screenshots**
<img src="https://user-images.githubusercontent.com/54861487/216345902-5bb6b50b-e4bf-45a6-8ca6-20b7ae607030.png" width="200" height="400">

**To Reproduce**

1. Go to https://savingsatoshi.com/chapters/chapter-1/transacting-1
2. Either open in Mobile or Change to Mobile view using device toolbar
3. See error

**Comment by ecurrencyhodler** [comment]
I believe this has been addressed with https://github.com/saving-satoshi/saving-satoshi/pull/126
