### ISSUE TITLE
Layout issue on Challenge Intro page for Desktop & Mobile view

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#132]
**Describe the bug**
The layout for the challenge introduction page is different from figma mockup - https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=83%3A2379&t=d9uHpsXOJhhxBAMy-0

**To Reproduce**

1. Go to https://savingsatoshi.com/chapters/chapter-1/transacting
2. See the error

**Screenshots and/or logs**
![Screenshot 2023-02-04 at 1 24 02 PM](https://user-images.githubusercontent.com/54861487/216756198-f3bbc658-f33d-4556-b5cd-af3ee282fadf.png)
![Screenshot 2023-02-04 at 1 23 35 PM](https://user-images.githubusercontent.com/54861487/216756204-582f3682-f1a3-4471-b68a-94d1496565bc.png)

**Comment by benalleng** [comment]
@ecurrencyhodler We should re-open #129 resolved #127 this Issue will be fixed with #135

**Comment by ecurrencyhodler** [comment]
Understood. Moving this to in progress. Thanks Ben.
