### ISSUE TITLE
Runtime Error due to missing variable 

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#141]
**Describe the bug**
Runtime error occurs while running the repo locally due to a missing variable (`isLast`). Deployment failure due to the same bug - https://github.com/saving-satoshi/saving-satoshi/commits/master 

**To Reproduce**

1. fetch the latest code from the master branch
2. `npm run dev`
3. go to `localhost:3000/chapters/chapter-1`
4. See the error

**Screenshots and/or logs**
![Screenshot 2023-02-08 at 1 59 58 PM](https://user-images.githubusercontent.com/54861487/217482550-7da897b2-1cd1-4ebc-9783-1924aa1a987c.png)

**Additional context**
https://github.com/saving-satoshi/saving-satoshi/pull/140#discussion_r1099830161

**Comment by shaavan** [comment]
Thanks for catching it @vinayaksh42

Reintroducing the isLast variable will be a good fix for this issue. Let me address this issue!
