### ISSUE TITLE
Update signed in modal with copy + timeout discussion

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#147]
**Describe the bug**
When you are signed in and click on the profile, the copy is confusing because it says "Load your progress".
<img width="499" alt="Screenshot 2023-02-13 at 8 03 45 AM" src="https://user-images.githubusercontent.com/32662508/218509304-398d7c44-e758-4ef5-9fdf-6ef62aa4fcb3.png">

**To Reproduce**

1. Be a new user to the site and click on profile.
2. Click on "I’ve copied and backed up my code"
3. Click on profile again
4. See screenshot above

**Expected behavior**
We have a new updated design which should look like this.
![Sign in modal](https://user-images.githubusercontent.com/32662508/218510111-13e11933-3f21-45d5-85fa-28b5e46b5e5c.png)

**Additional context**
Another question we should discuss is exactly how long should the timeout be for a user once they are logged in.

**Comment by afterburn** [comment]
When our backend system is operational, we will be using access tokens, which _should_ not be retained for extended periods of time as they could compromise security. If you find this kind of thing interesting, you can read more about it [here](https://www.oauth.com/oauth2-servers/access-tokens/access-token-lifetime/).

That being said, we do not store any sensitive information, and we may never do so, so I think 30 days is an acceptable duration.

**Comment by ecurrencyhodler** [comment]
Let's split this issue into two:

1. Update copy for demo
2. Address timeout for v1

**Comment by vinayaksh42** [comment]
@ecurrencyhodler can I work on this issue?

**Comment by ecurrencyhodler** [comment]
Yes absolutely. Thank vinayak!

**Comment by ecurrencyhodler** [comment]
First part of this issue has been completed. Thanks Vinayak!

**Comment by ecurrencyhodler** [comment]
Closing this as both parts have been answered.
