### ISSUE TITLE
Language switch

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#148]
**Describe the enhancement**
We now have support for translations but currently we automatically detect what translations to load based on the locale set in the user's browser settings. It might be a better experience if users are free to select their preferred language from a dropdown menu.

1. User navigates to savingsatoshi.com, we autodetect locale and choose a language.
2. User might prefer a different language so he/she needs a way to change the language. <-- this is missing

**Additional information**
Users can actually change the translations by changing the locale in their browser settings, but this is not the most pleasant experience.

**Comment by vinayaksh42** [comment]
We should add a dropdown menu to the landing page - https://savingsatoshi.com/en, and provide a language change option in the profile modal or another accessible location. This will allow users to easily change their language preference at any time.

**Comment by afterburn** [comment]
Yeah, I was also thinking maybe in the Topbar but I'll let @GBKS take this further. 😁

**Comment by vinayaksh42** [comment]
If possible, I would like to work on this issue when the design for the dropdown is complete.

**Comment by afterburn** [comment]
Hey @vinayaksh42 , by all means, feel free to pick this up once the design is finished. 😁

**Comment by GBKS** [comment]
Here's a simple language switcher dropdown. The dropdown is a generic component ([Figma link](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A25331&t=imDb39nDuXTvo6aS-1)).

<img width="346" alt="image" src="https://user-images.githubusercontent.com/695901/223366247-47c51245-6fb7-4cff-87e6-5ae1470c0fd9.png">

**Comment by vinayaksh42** [comment]
> Here's a simple language switcher dropdown. The dropdown is a generic component ([Figma link](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A25331&t=imDb39nDuXTvo6aS-1)).
> 
> <img alt="image" width="346" src="https://user-images.githubusercontent.com/695901/223366247-47c51245-6fb7-4cff-87e6-5ae1470c0fd9.png">

Thanks a lot for providing the design update.

**Comment by ecurrencyhodler** [comment]
On the call, we had discussed only focusing on english for the demo. But do we have everything we need to include this in the demo?

**Comment by ecurrencyhodler** [comment]
Kevin had a great idea: We could add some message at the bottom of the popup saying "Want to help translate saving satoshi to more languages?" which would then send users to a doc where they can read about how to contribute/help with translating the app further.
