### ISSUE TITLE
Input styling on Safari

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#154]
>Sorry to report a bug right away, I'm finding that when I start entering text in the input field on Safari (desktop and mobile), it instantly switches from multi line to single line, stretching beyond the browser frame. This might just be a simple CSS setting (max-width or so).

On Safari there might be some browser specific styling that is not supported and is causing some strange rendering

**To Reproduce**

1. Go to [Input screen](https://savingsatoshi.com/en/chapters/chapter-1/genesis-1)
3. Apply mobile view by adjusting screen size or open with iphone
4. Begin typing in input area to reproduce error

**Expected behavior**
The styling should behave like other browsers

- Browser safari

I don't have easy access to test on safari so any more probing of this error would be appreciated! Any advice on how to test safari browser support with a Linux laptop?

**Comment by afterburn** [comment]
Feel free to pick this up @benalleng if you feel like it. I'm not in possession of something able to run the safari browser unfortunately.

**Comment by benalleng** [comment]
![safari-input-test](https://user-images.githubusercontent.com/108441023/219398735-73aaf08d-717b-4734-bb3d-8afe7134ea7f.jpeg)

Time to find out which css property isn't supported by safari

**Comment by vinayaksh42** [comment]
I tested it out in my safari browser and created this video - https://drive.google.com/file/d/1PC4NUozn6HE4mIJcsgOUukwZrGbmxExl/view?usp=sharing
I can run safari both on my iPhone as well as MacBook, I will try to investigate the bug causing this issue.

**Comment by ecurrencyhodler** [comment]
I can confirm the bug is being reproduced in Safari for desktop and mobile.
