### ISSUE TITLE
Block navigation to locked challenges

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#155]
**Describe the bug**
Users are currently able to navigate to any challenge, even if they haven't unlocked it yet.

**To Reproduce**
Using a fresh account either go to the first Genesis page, then click on the Transacting challenge in the Navbar or go to [this url](https://savingsatoshi.com/en/chapters/chapter-1/transacting-1) directly.

**Expected behavior**
Users should only be able to navigate to challenges that they have unlocked. If they try to navigate to a locked challenge we should either show a "This challenge is locked" message or redirect them back to either chapter overview or the last challenge that they have unlocked.

**Comment by afterburn** [comment]
I'm aware we haven't implemented this yet because it makes it easier for us to debug & develop, but we should probably think of what the flow **should** look like. @GBKS

**Comment by ecurrencyhodler** [comment]
Thanks for flagging this. I noticed it too when I was testing it earlier today. I think we can punt this to to v1.

**Comment by gadabra** [comment]
I have been working on this since https://github.com/saving-satoshi/saving-satoshi/issues/66#issuecomment-1435354590 and I plan to submit my thoughts by Saturday. I am hoping to complete this by the end of the weekend.

**Comment by gadabra** [comment]
I could not resist then I decide to write a brief overview. 😃 

As @GBKS mentioned  in https://github.com/saving-satoshi/saving-satoshi/issues/155#issuecomment-1441915904 a simple redirect is a quick solution. 'Next' button on the bottom right of each lesson page has been implemented with simple. However, there are a lot of disadvantages. 

I want to generate links from chapter 1's [metadata](https://github.com/saving-satoshi/saving-satoshi/blob/ec1d5c01aa5bd5f086ecf9f7edb4f6c00008e383/content/chapters/chapter-1/index.tsx#L16). This abstraction could be useful for other chapters.
 
I am taking a look at https://nodeschool.io/. In this site there are a lot of amazing projects like Saving Satoshi. I would highly recommend that everyone check it out.

**Comment by gadabra** [comment]
Now I comprehend, you misinterpreted this issue.
As @afterburn pointed out, this is highly useful for development and debugging purposes. I think We should revisit this once our flow is clarified.

**Comment by ecurrencyhodler** [comment]
@gadabra have you had a chance to take a look at this yet?

**Comment by sabakhilji** [comment]
Hey I want to take a look at this issue .Can please assign it to me @ecurrencyhodler
