### ISSUE TITLE
Add demo disclaimer

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#156]
**Describe the enhancement**
@GBKS has requested we show a disclaimer stating that the current Saving Satoshi experience is a demo. This issue serves as a reminder to actually implement the design for that once it's ready.

**Comment by benalleng** [comment]
I think this will be easiest to implement after #167 is merged as we can probably just use a similar modal pop-up

**Comment by GBKS** [comment]
I'd prefer not to have a modal. Instead, we can just have a short text-based indicator on the home page, with a longer explainer on the about page (see #175), as well as a call-out on the chapter 1 completion page (see #186). I'll mock something up.

**Comment by ecurrencyhodler** [comment]
Assigning this to Christoph for the design.

**Comment by afterburn** [comment]
Hey @GBKS, I don't mean to press but what's the current status for a demo disclaimer mockup?

**Comment by ecurrencyhodler** [comment]
+1 on "start the demo" feel. 

I'm on the fence about the disclaimer at the top. I already kinda feel like there is a ton of space at the top. Without the disclaimer, I have to scroll down to get to the button "Start chapter 1".
<img width="1292" alt="sample" src="https://user-images.githubusercontent.com/32662508/223174116-a28282ee-af7c-4a30-961d-cd0025f77e9e.png">
