### ISSUE TITLE
Type error in user object.

### ISSUE THREAD

**Issue by gadabra** [saving-satoshi/saving-satoshi#161]
**Describe the bug**
The project fails to launch when it is freshly cloned. `user` object has no `privateKey` as key. `Cannot read properties of undefined` occurs at [here](https://github.com/saving-satoshi/saving-satoshi/blob/59dbb13e208d0597b31d009df293058612e0c93c/components/Modals/SignUp.tsx#L84)

**To Reproduce**
1. Clone repository.
2. Install dependencies with `yarn`
3. Run project with `yarn run dev`
4. This error occurs 

**Screenshots and/or logs**
![Screenshot 2023-02-17 at 17 19 31](https://user-images.githubusercontent.com/100441043/219900571-09b06eb1-27e3-41dc-8983-4043f18cf8d0.png)

**Comment by benalleng** [comment]
@gadabra unfortunately I wasn't able to reproduce your bug. Do you get any additional warnings or information when installing packages or starting the dev frontend?

**Comment by gadabra** [comment]
@benalleng  No, I'm not getting any errors or warnings. The project works fine if I change `{user ? user.privateKey.toString(16) : ''}` to `{user?.privateKey ? user.privateKey.toString(16) : ''}` in two places within Signup.tsx (I do not know it is a right solution, I just use temporarily).

@benalleng I believe your `user` is obtaining the `privateKey` value from somewhere else. Perhaps deleting localStorage or opening a private window could reproduce this bug.

**Comment by afterburn** [comment]
Hey @gadabra thanks for reporting this issue. I also have trouble reproducing it, would you mind sharing your localStorage content, in particular the `user` key-value pair? I have a feeling the `privateKey` might not have been generated correctly in your case (since we do generate it client-side) which has lead to this bug.

**Comment by gadabra** [comment]
Ok. I figure out. Another project that I am working on is using `http://localhost:3000` and have a `user` object. `saving-satoshi` try to use other `user` object. The project run perfect when start with the empty local storage.

**Comment by afterburn** [comment]
Good you reported this issue anyway, I think we should use a namespace for any key-value pairs we store in Local Storage. I'll create a ticket for it.
