### ISSUE TITLE
Add command history to Terminal

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#165]
**Describe the enhancement**
It'd be nice if I would be able to use my up/down arrow keys to navigate between commands I previously entered in the `Terminal` component. This is a very natural thing to be doing if you're a terminal user, and can prevent some frustration if you make a typo and have to type the command from the start.

**Suggested solution**
I don't suggest we persist these across sessions. We should just keep track of any commands users input in the Terminal component itself via its state.

**Comment by vinayaksh42** [comment]
@afterburn, After looking into the issue you mentioned, it appears that the [`react-terminal-ui`](https://www.npmjs.com/package/react-terminal-ui) library being used for the terminal-like experience has limited flexibility when it comes to handling the input text area. Specifically, the library only offers an `onInput` prop which is triggered only when the user hits the `enter` key. Unfortunately, there are no `onKeyDown` or `onKeyUp` events available for us to use in this scenario.

**Comment by afterburn** [comment]
Good suggestion @vinayaksh42, as mentioned in the call I think we'll put this in backlog for now, but yeah I'm also leaning towards implementing a custom solution because of the following reasons:

1. We can support terminal-like behavior (such as command history) that our `react-terminal-ui` doesn't provide.
2. We can implement a fully functioning custom styled caret if @GBKS thinks we should indeed have one.
3. We can create other types of custom functionality, (syntax highlighting, autocompletion/hints, etc).

**Comment by 1t1e1** [comment]
I would echo @vinayaksh42's saying and emphasize forking. We could fork from `react-terminal-ui` and publish it under our own repository, which would make the implementation of the caret and the history much easier.

**Comment by gadabra** [comment]
I would echo @vinayaksh42's saying and emphasize forking. We could fork from react-terminal-ui and publish it under our own repository, which would make the implementation of the caret and the history much easier.
