### ISSUE TITLE
Too much height on Chapter Intro page

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#166]
**Describe the bug**
Not sure if this is a bug or if its intended (@GBKS) but on the intro page for a chapter there is this extra height which causes a scrollbar to appear. It seems to be the exact height of the Topbar, so we should probably just subtract that from the content height.

**To Reproduce**

1. Go to Chapter 1 Intro page.
2. Observe the scrollbar caused by extra height.

**Expected behavior**
I expect the scrollbar to only be visible if the content exceeds the viewport height.

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/10757768/220192337-e8dfc34f-373d-494a-ad6d-d08c5dcf34af.png)

**Comment by ecurrencyhodler** [comment]
@benalleng will take this on.

**Comment by GBKS** [comment]
Reason for this is that the `img` tag has no height set (it's not related to the nav bar). It should be set to 100%.

**Comment by ecurrencyhodler** [comment]
One solution @afterburn suggested on the call tuesday was to have a fixed pixel height for the top bar. Then use that, subtract it from total, and save it as a variable. Then use tailwind class to define min height for content. So instead of modifying image, force min height on content.

In this method, min. height will enabled scrolling.

**Comment by GBKS** [comment]
That's not necessary. The CSS is already super well set up to allow this to be dynamic, we really just need this one extra CSS attribute on the image.

I generally would not try to use fix heights. With responsive design, accessibility settings, and browser scaling, elements can be dynamically resized in many ways for very legit reasons. So it's always better to try to make a dynamic layout work.

**Comment by afterburn** [comment]
Yeah the `min-height` approach was just a suggestion if it couldn't be easily fixed otherwise. @benalleng has tackled this issue, though it was a little more involved than setting the image height to be 100% judging by his code changes.
