### ISSUE TITLE
Mobile Responsive Modal: Profile screen doesn't adapt to mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#168]
**Describe the bug**
When I click on the profile on mobile for Chrome and Safari, the screen doesn't adapt. 

![Safari](https://user-images.githubusercontent.com/32662508/220198610-0c0e6bad-f107-48fe-982d-8c19580d3898.PNG)
![Chrome](https://user-images.githubusercontent.com/32662508/220198617-a1be0e57-7078-4b30-a9f6-da427c16a92f.PNG)

**To Reproduce**

1. Click on profile
2. View screen in mobile

**Expected behavior**
Profile screen should adapt. Here is [the design in figma.](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1852%3A21344&t=sDLyutrdiM9Wgrid-1)
<img width="236" alt="Profile screen" src="https://user-images.githubusercontent.com/32662508/220199022-0cbd4880-51ae-44f3-a789-ac27666ef2d2.png">

**Comment by shaavan** [comment]
Let me take a look into this!

**Comment by ecurrencyhodler** [comment]
Hey @shaavan this is actually being included in this PR! https://github.com/saving-satoshi/saving-satoshi/pull/167

**Comment by shaavan** [comment]
Okay! Thanks for letting me know!
