### ISSUE TITLE
Namespace data we store in Local Storage

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#170]
**Describe the enhancement**
When storing data in Local Storage we should namespace our keys (see #161 for context). Right now we use the words `user` and `loggedIn` in. These have a very high probability of conflicting with the data from other projects that contributors are running on localhost:3000.

I suggest we prefix with `saving-satoshi-` so for example `saving-satoshi-user` and `saving-satoshi-loggedIn`, or something similar.

**Comment by vinayaksh42** [comment]
I would like to work on this issue.

**Comment by afterburn** [comment]
@vinayaksh42 all yours!
