### ISSUE TITLE
Update images

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#173]
The current images are too low-resolution. We also want to have images in two resolutions for retina support. In addition to uploading higher-res ones, let's use newer ones we have generated.

This is for the AI-generated images on the:

- Home page
- Chapters page
- Chapter intro pages
- Chapter complete pages

**Comment by ecurrencyhodler** [comment]
Hi Christoph. Where can people find the final images to include? Will the designs in figma get updated?

**Comment by GBKS** [comment]
I'll prepare a set and share it here to get feedback from everyone.

**Comment by afterburn** [comment]
I think the image for the Homepage is being addressed in #199. What is the status for the other pages, do we have images ready for them? I did notice one for the first chapter in the `Images for export` page on Figma, but not sure if it is final. @GBKS

**Comment by ecurrencyhodler** [comment]
Christoph is going to work on getting final images within the next couple of days. Since we intro'd a new story, we haven't generated images for them yet for the extra screens. He'll also give us a design update at the beginning of our call tuesday. This will help us figure out the remaining items that need to be addressed.

**Comment by afterburn** [comment]
Sounds good, please assign this ticket to me (or comment here again) when the images are ready, that way I know when engineering can start working on these issues (just making sure we can close all demo issues for pi day).

**Comment by ecurrencyhodler** [comment]
We may close this issue once Christoph finalizes designs. I believe he wants to now create individual issues for the updates that engineers can take.

**Comment by afterburn** [comment]
Sounds good.

**Comment by ecurrencyhodler** [comment]
This is being addressed in https://github.com/saving-satoshi/saving-satoshi/pull/263

**Comment by ecurrencyhodler** [comment]
Closed by #263
