### ISSUE TITLE
Show "Coming soon" on the chapters page for chapters 2+

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#176]
This currently reads "Complete Chapter 1 to unlock.", which is not accurate as the content does not exist. We will still need the current message at a later stage once we have more than one chapter.

Let's include a "Coming soon" or "Stay tuned" (as "soon" is not really accurate either). Do we want to include a link where people can see a roadmap? Or ask them to follow on Twitter/Nostr for new chapter releases?

**Comment by ecurrencyhodler** [comment]
It'd be great if we could collect emails too.

**Comment by GBKS** [comment]
A simple solution would be to link out to a Google Form (or maybe a more privacy-preserving form tool) that also allows for users to leave an email with us.

**Comment by ecurrencyhodler** [comment]
Closed by https://github.com/saving-satoshi/saving-satoshi/pull/238
