### ISSUE TITLE
Adjust modal background color

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#177]
Make the modal background 50% black instead of 75% white. See [design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1852%3A21344&t=wtEGAyNRp9cwYerM-1).

![localhost_3000_en (2)](https://user-images.githubusercontent.com/695901/220896610-e4f40740-9819-403e-b2f8-952b26dc91da.png)

**Comment by sabakhilji** [comment]
Hi, I would like to take this issue.

**Comment by ecurrencyhodler** [comment]
All yours Saba!

**Comment by ecurrencyhodler** [comment]
Closed by #212
