### ISSUE TITLE
Make the story text cohesive (home, about, chapter 1)

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#178]
A linear user journey across home page, chapters overview page, and chapter 1 intro page means that the text on those pages should make sense in the given order. This is currently not the case. Let's revise all this copy so it's coherent.

![image](https://user-images.githubusercontent.com/695901/220904218-235a0e8e-5878-4e3f-86bf-0cab82a8950e.png)

**Comment by satsie** [comment]
Will tackle this in a 30 min working session after the team call on Tuesday 2/28

**Comment by ecurrencyhodler** [comment]
I hope to get this done EoW [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2147%3A24653&t=yULQpKrVq5wOTlHy-1).

**Comment by ecurrencyhodler** [comment]
Here is the [latest story](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2147%3A24653&t=o4jRHzU3EIZJVQGW-1) for demo. Closing this issue as it's been addressed in figma.
