### ISSUE TITLE
Header travels down page

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#18]
<img width="1423" alt="Screen Shot 2022-12-02 at 8 14 24 PM" src="https://user-images.githubusercontent.com/755825/205415368-9a5860e6-6867-4cfd-8130-3f94ad15d8f8.png">

I don't imagine we want it to be fixed like that? 

Removing fixed from https://github.com/saving-satoshi/saving-satoshi/blob/master/components/NavBar.tsx#L5 prevents it from being a stick nav.

@GBKS thoughts?

**Comment by ggwilin** [comment]
I put like like that thinking in some games that i have played that preserve their header along some of the menus, but e can change it by removing the `fixed` inside the NavBar

**Comment by ggwilin** [comment]
Solved in: https://github.com/saving-satoshi/saving-satoshi/commit/ad11a588af91875d466e12de25bf9e5f6030f32e `components/NavBar.tsx`
