### ISSUE TITLE
Remove tips from chapter 1, challenge 1, page 2

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#180]
Since this value is now pre-configured via a variable, we no longer need to help users find that value again ([link](https://savingsatoshi.com/en/chapters/chapter-1/genesis-2)). Note that we want this tip in the latter part of challenge 2 ([see here](https://savingsatoshi.com/en/chapters/chapter-1/transacting-3)). So maybe just move this tip code over and adjust the text?

![localhost_3000_en_chapters_chapter-1_genesis-1](https://user-images.githubusercontent.com/695901/220906031-dca61960-41d2-4a6c-9587-8b40ace6eeff.png)

**Comment by ecurrencyhodler** [comment]
Moving this to backlog for now until we finalize the 2nd challenge and copy.

**Comment by ecurrencyhodler** [comment]
We've confirmed that tips won't be necessary for challenge 2 either on the bottom left.
