### ISSUE TITLE
Clean up decoded message in chapter 1, challenge 1, page 2

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#181]
There are some scrambled characters at the start of the decoded message. Can we remove them? Or are they supposed to be there?

![localhost_3000_en_chapters_chapter-1_genesis-1 (1)](https://user-images.githubusercontent.com/695901/220906718-c9febb94-801e-4ed8-b982-9347aa88aeb0.png)

**Comment by benalleng** [comment]
We discussed this in this weeks call, The unintelligible characters are from the OP_Codes preceding the hex data inscribed in the genesis block. @satsie created a [figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1604%3A19617&t=plCz6vGZyDje1o21-0) file detailing what it might look like if we were to dive into removing those characters properly. As a note Jonas believes that we should keep the characters at this early stage and not worry about OP_Codes until a much later chapter.

**Comment by ecurrencyhodler** [comment]
Closing this issue as we are going to keep the scrambled characters for now.
