### ISSUE TITLE
Add a more helpful success message to chapter 1, challenge 1, page 2

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#182]
It just reads "Great job!". We can give some input on why this message means and its importance on bitcoin culture. See a proposed change in [Figma here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1604%3A21834&t=wtEGAyNRp9cwYerM-1).

![localhost_3000_en_chapters_chapter-1_genesis-1 (1)](https://user-images.githubusercontent.com/695901/220906933-45148c19-359a-483f-a023-de75f0abd972.png)

**Comment by afterburn** [comment]
Assigning this to myself because the suggested "you can read it here" should be a link that users can click according to Figma, which makes this a bit more involved when you consider our translation system. It currently only supports tooltips, no support for direct hyperlinks yet so I'll add that.
