### ISSUE TITLE
Disable spellcheck and autocomplete on terminal input field

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#187]
While testing on mobile, iOS tried to auto-correct my code input, which of course made no sense. We can disable this via the [spellcheck](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) and [autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attributes.

**Comment by GBKS** [comment]
I also noticed that pasting was not possible on iOS (worked on Android). Anyone know why that might be the case?

**Comment by ecurrencyhodler** [comment]
I can confirm paste is not working in iOS. I'll create a separate issue.
