### ISSUE TITLE
Mobile Responsiveness for Sign-up Modal Avatar 

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#192]
**Current state**
The avatar images in the Sign-up Modal on mobile screen size appear in the following way:
![Screenshot 2023-02-24 at 11 58 31 AM](https://user-images.githubusercontent.com/54861487/221108073-34d23cb0-d12e-4138-b1c5-001aff570257.png)

**Expected state**
According to the [figma mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A22335&t=0yhLFQ2wwqOYCPOi-0) the avatar images are required to appear in the following way:
![Screenshot 2023-02-24 at 11 59 46 AM](https://user-images.githubusercontent.com/54861487/221108251-3f7863fa-886d-4af0-972b-68e023c93817.png)

**Comment by afterburn** [comment]
@GBKS should users be able to scroll horizontally on mobile here? It isn't very clear from the design, so perhaps you wouldn't mind elaborating on the desired behavior?

**Comment by GBKS** [comment]
Yes, there should be horizontal scrolling. We may add more avatars in the future and showing them as a grid would be too big for mobile.

**Comment by afterburn** [comment]
@GBKS Okay, thank you!

To whoever is picking this up, please create a reusable component that:
1. Allows for horizontal scrolling on mobile.
2. Displays things in a grid when on desktop.

Then use that component to make a fix for this issue specifically.

**Comment by shaavan** [comment]
Let me give it a try!
