### ISSUE TITLE
Collecting email addresses

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#196]
As mentioned in #176 I'm creating this ticket for email address collection specifically. We can use this issue to discuss if we want to do this, and how we should approach it if we do.

**Describe the enhancement**
After users complete Chapter 1 I think we should allow them to sign up for a "Saving Satoshi Newsletter" (or whatever we decide to call it).

Ideally we store:
- the user's email address
- the user's identifier (most likely their private key by the way things are looking for Backend V1)
- a timestamp

This allows us to give the user some rewards for being a player during our 'alpha' or 'beta', which I think is a common thing to do in the gaming world. Perhaps a nice badge or some kind of achievement that can be shown to other players.

**Suggested solution**
We should see whether we can find some easy-to-use solution first. I checked out Google Forms, but I don't think it allows us to save custom fields without the user entering them specifically into the form. Maybe someone knows about an alternative solution that does support this.

If there are no easy-to-use solutions available, we can spin up a very simple Node.js service that stores the emails in a database and send a request when the user fills in their email address after Chapter 1. This approach gives us full control over what data can be stored.

**Comment by ecurrencyhodler** [comment]
We would also need to factor in an email tool to blast out updates. There are several to consider:

1. Hubspot (Free up to 2k but has HS branding)
2. Mailchimp (Free up to 1k subs)
3. Substack (Unlimited free subs)

Substack may be our best bet. 

IMO saving the identifier is a nice to have but not essential. If we don't think saving an identifier is necessary, we can point them directly to our email tool to subscribe which would save a lot of dev time. We can always add rewards later by having them submit their emails again and comparing them with what we've collected.

**Comment by afterburn** [comment]
Alternatively we could use AWS SES (pricing [here](https://aws.amazon.com/ses/pricing/)) or whatever the GCP variant is called. This would for sure let us use our own branding, and it could potentially interface a little better with our (future) backend.

**Comment by ecurrencyhodler** [comment]
We will be pushing this issue to v1.

**Comment by ecurrencyhodler** [comment]
We are informally collecting email addresses for people who want to stay updated with the project through [this google form](https://docs.google.com/forms/d/e/1FAIpQLSf1xpNqUYJyvYL5IZDnxy78273pkqzfYW2Hf91H4Do4KHgy9g/viewform?usp=sf_link). Closing this issue.

**Comment by ecurrencyhodler** [comment]
Okay quick update. We are no longer collecting emails through the form and don't have any plans to collect emails in the future. If people want to stay updated they can follow us on twitter.
