### ISSUE TITLE
Ch.1 Challenge 2 Pt. 2 copy/paste bug

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#197]
**Describe the bug**
When I copy and paste the value from the explorer to the challenge, it passes Ch.1 Challenge 2 Pt 1 but when I paste the same value into pt. 2 it fails. 

I think what's happening is that when I copy the op_return from the explorer, it brings over an extra character/space. The thing is it passes pt. 1 but not pt. 2. But when I then paste the op_return into a text tool and copy it over to the challenge, it works.

This might require some deeper investigation but I'm going to attach a screen recording of what I did. I think the ideal solution is that pt. 2 would accept the value just like it does in pt. 1.

**Comment by afterburn** [comment]
I think you're right, what happens is depending on the way you copy the code from blockstream it might contain extra characters. I tried different ways and was able to get a \t which is a tab character in my copied value, I'll add some logic that removes unwanted characters.
