### ISSUE TITLE
Code challenges

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#2]
As a learner, I can solve a code challenge using a REPL.

Open questions:
- is this repl a replit code pane?
- can I pair with others on my coding challenge?
- can I evaluate the code and receive feedback from a test that runs in the background?
- can I choose the language?

**Comment by GBKS** [comment]
What do you mean by `is this repl a replit code pane?` I guess I am confused whether REPL refers to the general read-eval-print-loop concept (which we can code with various libraries), or the specific implementation of [replit.com](https://replit.com).

Pairing seems like a larger discussion:
- For which challenges is this appropriate and useful?
- Think through the interaction model (how to invite someone, etc)
- How to make this work technically

Choosing a language should be a site wide thing (accessible via the top nav).
