### ISSUE TITLE
Make profile icon accessible

### ISSUE THREAD

**Issue by sabakhilji** [saving-satoshi/saving-satoshi#208]
In order to make the profile icon on the homepage accessible, I tried adding aria-label to it.

Initially, it worked correctly but as I restart my server it stopped working.
I am using windows narrator to check the accessibility of this button.
When I switched the button to the avatar, the narrator read it as the avatar button. But not working with the profile icon.

Please find the attached screenshot of the web accessibility tool checker to access the accessibility of the website:
![Screenshot (67)](https://user-images.githubusercontent.com/52318459/221928845-2eac49b8-2d3d-4869-a0e2-972e47a04482.png)

Also, please find attached here is the screenshot of the changes added to UserButton:
![Screenshot (68)](https://user-images.githubusercontent.com/52318459/221933618-0f1ea8de-1445-4b80-a2d5-3e7a50c0a4d4.png)

**Comment by benalleng** [comment]
Hi @sabakhilji ! Thanks for your help with this issue! Go ahead and create a new PR (pull request) with the code changes you made. You actually made another earlier issue #171 and now we're ready to [check that code](https://github.com/saving-satoshi/saving-satoshi/pulls)!
With all the crazy terms in github like: issues, prs, origin, upstream, branches, forks :exploding_head: it can get complicated fast! Feel free to ask how to get this setup and all of us will be happy to help!

**Comment by ecurrencyhodler** [comment]
Closing this since it's a duplicate. Saba make sure to submit a pull request and eng can take a look. :)
