### ISSUE TITLE
i18n folder to condense translation system

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#209]
The creation of a separate i18n folder within the repository will allow easier contribution and general searching for content and copy within the project. As well it will help to minimize the amount of reused localized copy as it will be easier to find and document what already exists if it is all in one place. This will act as the one stop shop for all localization and copy for contributors to find and add to moving forward.

**Comment by ecurrencyhodler** [comment]
Is this something that's currently in progress in a PR?

**Comment by benalleng** [comment]
Nope, I'm going to make a new PR for its once its ready

**Comment by afterburn** [comment]
Dont think this one is required for our demo, the translation system works fine as-is but this is a nice enhancement/improvement. @ecurrencyhodler
