### ISSUE TITLE
Navbar Menu not spanning to full length in Mobile view [Safari]

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#213]
**Describe the bug**
When the menu is activated and I scroll past its height, I can view all the content below it. (Watch this video for a better understanding: https://drive.google.com/file/d/1Boc-xZOP9IWaufAntH6TF2RtUN6MpMoh/view?usp=sharing)

**To Reproduce**

1. Go to https://saving-satoshi-git-fork-shaavan-navbar-update-2-savingsatoshi.vercel.app/en/chapters/chapter-1
2. Click on the challenge Menu
3. Scroll down to the bottom
4. See the error

**Expected behavior**
Either the menu expands to full length and covers the remaining part of the page or the scrolling is restricted to the length of the menu.

**Screenshots**
![IMG_2968](https://user-images.githubusercontent.com/54861487/222264472-6ec6d34b-1784-4a2a-bfe8-30ae5f7c0daa.PNG)

**Smartphone (please complete the following information):**

- Device: iPhone 13
- OS: iOS 16.3
- Browser safari

**Comment by ecurrencyhodler** [comment]
I'm going to close this issue for now as we are not prioritizing supporting safari.
