### ISSUE TITLE
Hovering mouse over tool tips are not consistent. 

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#218]
**Describe the bug**
In Ch.1 Challenge 1, pt1, there are two tool tips. When you hover over one, it shows a hand. When you over over another one, it shows the mouse cursor. Is this because there is a url embedded in the first tooltip?

Checking figma I don't see a recommended option between mouse cursor vs hand when hovering over a tool tip.

https://user-images.githubusercontent.com/32662508/222543536-e9947565-4dc7-45bd-8922-abda2e136943.mov

**Comment by ecurrencyhodler** [comment]
I think I know what's going on. If there's an external link inside the tooltip, I think the code is treating the tooltip as an external link as a whole. That's what's causing the mouse to turn into a hand. 

This is what's happening when I tap on the tooltip for mobile. It immediately jumps out to a link instead of letting me view the tooltip. I guess really this is the bug.

https://user-images.githubusercontent.com/32662508/222545359-e0dee8b2-fc2a-4f6f-8308-933627075d3e.MP4

**Comment by benalleng** [comment]
@ecurrencyhodler I have a quick fix adding a pointer class to tooltips.
However, with the mobile functionality should I go ahead and make tooltips open on mobile too?

**Comment by ecurrencyhodler** [comment]
Thanks ben! 

What do you mean "make tooltips open on mobile too?"

**Comment by benalleng** [comment]
AFAIK generally tooltips are disabled on mobile

**Comment by ecurrencyhodler** [comment]
Okay. Right now we have the functionality in mobile. So let's go with just the quick fix.

**Comment by benalleng** [comment]
okay, so the tooltip 'block explorer' IS a link so hovering it on desktop opens the tooltip but clicking it also just goes straight to a link. Do you think we should move the link to the url INSIDE the tooltip?

**Comment by ecurrencyhodler** [comment]
Yes I think so. Otherwise they'll never see the text inside the tooltip in mobile.

**Comment by benalleng** [comment]
So slight problem, as the tooltip goes away on moving the curson adding a link inside of a tooltip is quite difficult to click on. I think that maybe just having the block explorer tooltip go to the link on mobile is ok with the amount of technical debt it would create

**Comment by ecurrencyhodler** [comment]
Okay. Let's also raise this on our call tuesday so we're all on the same page. Thanks for investigating it.

**Comment by afterburn** [comment]
In my PR #233 tooltips will no longer become invisible when you move your mouse cursor over them.
