### ISSUE TITLE
Mobile tooltip with link doesn't display tip but jumps to the link.

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#220]
**Describe the bug**
On mobile, when you tap on the tooltip that has been hyperlinked, you don't see the tip. Instead it jumps to the link in the tooltip.

https://user-images.githubusercontent.com/32662508/222560564-242672fa-6fb5-4b14-9ced-32e10d2d1a79.mp4

**Comment by ecurrencyhodler** [comment]
Related to this discussion:

"So slight problem, as the tooltip goes away on moving the curson adding a link inside of a tooltip is quite difficult to click on. I think that maybe just having the block explorer tooltip go to the link on mobile is ok with the amount of technical debt it would create"

https://github.com/saving-satoshi/saving-satoshi/issues/218#issuecomment-1452543743

**Comment by shaavan** [comment]
@benalleng 

> "So slight problem, as the tooltip goes away on moving the curson adding a link inside of a tooltip is quite difficult to click on. I think that maybe just having the block explorer tooltip go to the link on mobile is ok with the amount of technical debt it would create"

- Since we cannot have a hover effect on mobile, how about we activate the tooltip when the "block explorer" text is clicked and make it persists? This way user can click the link inside the tooltip.

**Comment by ecurrencyhodler** [comment]
Closed by #233
