### ISSUE TITLE
favicon 404 on firefox desktop

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#222]
I am getting a 404 error on firefox when it attempts to load the icon.

I think this may have to do with the order that it loads the website, it first does a redirect to `/en` then attempts to load the icon from the URL `/en/favicon.png` causing a 404.
![image](https://user-images.githubusercontent.com/108441023/222626332-eba64c44-e3ec-4258-86bc-74dbdf3f3917.png)

![image](https://user-images.githubusercontent.com/108441023/222624512-76a9362d-49c5-423e-ac7c-2b5041a22baf.png)

![image](https://user-images.githubusercontent.com/108441023/222624583-cfdc96c3-bd24-46b8-81b2-bc23cff2d725.png)

I think this could be fixed by making sure the favicon.ico loads which at the moment isn't present in the networking tab.
I can go ahead and add this to #199

**Comment by vinayaksh42** [comment]
Changing the following seems to be fixing the issue in my local build:
```ts
export const config = {
  // TODO: Find a way to handle these dynamically
  matcher: [
    '/((?!_next/static|_next/image|assets|favicon.ico|android-icon|favicon|manifest.json).*)',
  ],
}
```

it is Redirecting `android-icon` and `favicon` to `/[lang]`, hence the 404 
<img width="490" alt="Screenshot 2023-03-09 at 3 05 45 AM" src="https://user-images.githubusercontent.com/54861487/223855710-2f63d90b-0494-4bc1-ae9c-9f12bdc242ab.png">

**Comment by vinayaksh42** [comment]
> I think that this can be closed now actually, with #199, #247 now in master I do not seem to be getting those 404 errors

In firefox I am still getting 2 -  `404` for favicon-32x32 and android-icon-192x192:
<img width="1352" alt="Screenshot 2023-03-09 at 3 30 09 AM" src="https://user-images.githubusercontent.com/54861487/223860430-42d31173-3e73-459c-a594-998a18d888fe.png">

**Comment by benalleng** [comment]
Sorry commented too quickly, definitely still an issue. Is this because in our `head.tsx` file our image hrefs are `/favicon-192x192.png` and not `/_next/image?url=%2Fandroid-icon-192x192.png&w=3840&q=100`

**Comment by benalleng** [comment]
> Changing the following seems to be fixing the issue in my local build:
> 
> ```ts
> export const config = {
>   // TODO: Find a way to handle these dynamically
>   matcher: [
>     '/((?!_next/static|_next/image|assets|favicon.ico|android-icon|favicon|manifest.json).*)',
>   ],
> }
> ```

That didn't work as expected for me

**Comment by benalleng** [comment]
Changing all of the `Links` in `head.tsx` to follow this format fixes this for me
```jsx
<link
  rel="icon"
  type="image/png"
  sizes="192x192"
  href="/_next/image?url=%2Fandroid-icon-192x192.png&w=3840&q=100"
  />
```
But is this really the only/ best solution?

**Comment by vinayaksh42** [comment]
> Changing all of the `Links` in `head.tsx` to follow this format fixes this for me
> 
> ```js
> <link
>   rel="icon"
>   type="image/png"
>   sizes="192x192"
>   href="/_next/image?url=%2Fandroid-icon-192x192.png&w=3840&q=100"
>   />
> ```
> 
> But is this really the only/ best solution?

I have created a draft PR #254 


this is the network tab output for favicon and android-icon in firefox:
<img width="490" alt="Screenshot 2023-03-09 at 3 43 13 AM" src="https://user-images.githubusercontent.com/54861487/223863413-b8dcaa2c-9305-43c7-b79f-f5cb221584d0.png">
