### ISSUE TITLE
Fix button styling for InputChallenges

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#234]
From @GBKS, originally part of #179:

Also, the button should only stretch the full width on mobile. On desktop, it should hug its content (with appropriate padding) (same goes for the button in the [transacting challenge](https://savingsatoshi.com/en/chapters/chapter-1/transacting-2)).

![image](https://user-images.githubusercontent.com/695901/220905635-4c612fd4-05d9-4b34-b190-6499b75b7b80.png)

**Comment by damiend97** [comment]
Hello there! I would like to help with this issue. What is an appropriate screen width for mobile? It seems like around "> 840px" the button already hugs content.

**Comment by benalleng** [comment]
@damiend97 I think that it is intended for the button to behave more like the button in this [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=1604%3A21250&t=EyhWThQ5axDowKfc-0).
Generally the Figma will always be the 'source of truth for all styling and layout changes that may be unclear. You can't go wrong matching it to an up-to-date figma!

**Comment by damiend97** [comment]
The only solution I have came up with is to override the Button width (content>lessons>genesis>genesis-1>index.tsx) with a custom class defined within globals.css. I've looked over the codebase for a few hours and tried several solutions to no avail. Overriding CSS with !important seems like bad practice and clearly not the approach used for other components that seem to be working as desired. Thanks for the opportunity to try on this one but I don't think I'll be able to get this.

**Comment by benalleng** [comment]
No worries! thanks for taking a look at it! Feel free to check out some other issues! always good to have contributors!

**Comment by ecurrencyhodler** [comment]
@damiend97 thanks for checking us out. We are actually in the midst of gearing up to hit a deadline of 3/14 for our demo. Even though this issue didn't work out, there's going to be plenty of opportunity this week to pick up an issue. 

We are going to have a call on Tuesday to get up to speed on the remaining tasks and will start assigning them. Let me know if you want to come to the call and you're more than welcome to [join us on slack](https://join.slack.com/t/bitcoindesign/shared_invite/zt-1qsxlzr3k-lkBvO2NN~IJziM4vIKkCAw) in the #saving-satoshi channel. You can find me there.

**Comment by damiend97** [comment]
Thank you @benalleng and @ecurrencyhodler. I'll keep looking in the issues. I also joined the slack. If I'm available Tuesday I'd love to join in.
