### ISSUE TITLE
Hide all language translation tools and ux for the demo

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#240]
We will only be revealing the english version for our demo. Let's hide all language translation tools to simplify the requirements including the language tool tip.

**Comment by ecurrencyhodler** [comment]
This is being addressed in https://github.com/saving-satoshi/saving-satoshi/pull/263

**Comment by ecurrencyhodler** [comment]
Before we had a language toggle in prod and in design. On the call last tuesday we had discussed to remove the ability to do that. Your designs in the PR now do not include the language toggle.

**Comment by GBKS** [comment]
OK, I just did not touch any of that in the PR, so the PR does not address it. Someone else must have done that part.

**Comment by benalleng** [comment]
I think this is safe to close now that everything should be exclusively in English until v1 @ecurrencyhodler
