### ISSUE TITLE
Translation Fallbacks

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#243]
At the moment the current localization system `/lib/translate.ts` does not properly grab fallback translations when a specific translation is missing. It seems t gather some translations but not all of them. This also happens when the localization switches without updating the language loaded for the page which happens whenever a link is clicked.

**Comment by afterburn** [comment]
Hey @benalleng, I'm addressing this in #245. I think when a translation is missing in let's say the `nl` locale, then IMO it should just return the key so we know something is wrong and we can add the missing translation(s). I feel like we shouldn't fall back to another locale (e.g. `en`) if something is missing.

**Comment by benalleng** [comment]
Ok! I think there is something to be said for fallbacks down the road i.e. no translations for an entire chapter in a specific locale but I think that could also be some separate logic down the line like simply locking it for that language. You are right that having a way to show missing translations is helpful.

**Comment by afterburn** [comment]
I understand you want to ensure a nice user experience even if translations are missing, and I agree with you. I'll explain my vision for this.

Once we have proper logging we can do fallbacks (to another locale for example), so if a key is missing, we log that it's missing, and then we fall back to the  `en` variant for example. That way we know something is missing, but the UX is relatively unaffected. Best of both worlds.
