### ISSUE TITLE
Occasional white screen after refresh

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#256]
**Describe the bug**
Occasionally I get shown a white screen when refreshing the page in Chrome.  I am unable to reliably reproduce this issue however. 

I haven't been able to reproduce the bug on desktop firefox or mobile chrome.

**To Reproduce**

1. Go to the website
2. Refresh
3. See white screen

https://user-images.githubusercontent.com/32662508/223877259-24c753a1-0193-4472-8c7e-4a12b28172c4.mov

**Comment by afterburn** [comment]
Might be an issue with the redirect in middleware.ts @vinayaksh42 @benalleng

**Comment by benalleng** [comment]
I am not able to reliably reproduce this issue on Chrome desktop or Firefox. When you do manage to reproduce this behavior what normally resolves this?

**Comment by ecurrencyhodler** [comment]
FYI the test above is chrome with default language settings as english. This doesn't seem to occur if my default language is dutch and I'm on the url /nl.

My hunch is this has to do with the browser being unable to resolve forced language settings and default language settings. If so, this would be problematic when we offer language options in the future.

**Comment by vinayaksh42** [comment]
> Okay I figured out how to reproduce this.
> 
> 1. Go to https://savingsatoshi.com/nl
> 2. Click start demo
> 3. Refresh the page (multiple times if needed)
> 
> Another thing that I notice is that the url doesn't always stick to /nl ending but jumps to /en ending.

I was unable to reproduce this error based on the instructions provided. Which browser are you using for testing this bug?

The website might be jumping to the `/en` ending due to your locale language being English.

**Comment by ecurrencyhodler** [comment]
Hmmm okay. I'm using chrome. If we can't reproduce we can close this issue.

**Comment by benalleng** [comment]
> Might be an issue with the redirect in middleware.ts

I think the issue may have to do with how our `middleware.ts` interacts with the browser's default locale search. because we are letting the browser decide which language to use, refreshing or going to a new page causes it to run `getLocale(request)` again but when the result of `getLocale()` and the locale set in the url differ this may be confusing `useLang.ts` is obviously causing some errors. when #148 is implemented we may be able to only run `getLocale()` on the first page load or when a new language is selected so that the `useLang()` and functions inside translate.ts aren't fighting with two locales. worth leaving this open to see if that PR fixes this issue later on.

**Comment by benalleng** [comment]
With the addition of some new logic in `translations.ts` I was wondering if this is still an issue, granted we are still dealing with links always switching to the `/en` locale but i wanted to ask if anyone could reliably reproduce this particular bug anymore?

**Comment by ecurrencyhodler** [comment]
So now what happens is that if I go to https://savingsatoshi.com/nl and click on "start demo" it just shoots to /en. 

I can't repro white flash anymore.

**Comment by benalleng** [comment]
I think we should close this particular issue, however we obviously need to create a new issue to solve locale consistency. i.e. once I select a particular locale I expect it to retain my choice and carry through any link I click to move through the website.

**Comment by ecurrencyhodler** [comment]
Closing this issue.
