### ISSUE TITLE
Add a success page for chapter 1, challenge 1, part 1

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#261]
This celebrates the first successful completion of a task to encourage learners. It should show right after completing the first task (which is copying the ScriptSig HEX from block 0). See the [Figma design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2374%3A26698&t=1WVTKCVc1kPVBDfc-1) and the [export-ready image](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2418%3A25721&t=1WVTKCVc1kPVBDfc-1).

![image](https://user-images.githubusercontent.com/695901/223948846-0b0bc125-f5df-4a95-abbe-e4a31ab06ff8.png)

**Comment by sabakhilji** [comment]
Can I work on this issue?

**Comment by ecurrencyhodler** [comment]
Hey @sabakhilji You can take it. Let us know if you need help with #212 as well!
