### ISSUE TITLE
Add an outro page for chapter 1

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#262]
We already have the end page ([here](https://savingsatoshi.com/en/chapters/chapter-1/done)). We want to insert another page the users sees after completing the second challenge that drives the story forward. See the [Figma design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2374%3A26622&t=1WVTKCVc1kPVBDfc-1) and [export-ready image](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A25493&t=1WVTKCVc1kPVBDfc-1).

![image](https://user-images.githubusercontent.com/695901/223949891-7e64c9db-758c-4d0f-8714-56ce1507266d.png)

**Comment by shaavan** [comment]
On it!

**Comment by shaavan** [comment]
@GBKS 

I have one question to ask. The color scheme of the 'outro page' is quite different from the rest of the Chapter. 
So I would like to confirm if this is an intentional change.

Thanks!

**Comment by GBKS** [comment]
Yes, the page background has a different gradient, that's the only change. You can ignore this for now.
