### ISSUE TITLE
Make the info template on the chapters overview page more flexible

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#268]
The template currently expects exactly three paragraphs. If those are not defined, the translation keys are rendered. As follows:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/695901/224242832-b06cf9b9-6471-4823-bc4e-88c4f9f1a7b7.png">

<img width="311" alt="image" src="https://user-images.githubusercontent.com/695901/224242889-cea73e5f-0c54-41db-8a09-b3f48f6cbf7e.png">

How can we make this template dynamic? Chapter 1 currently only needs 1 paragraph, other chapters also may need different amounts based (that copy is still TBD).

**Comment by ecurrencyhodler** [comment]
Ben does that mean we should close this issue?
