### ISSUE TITLE
Styling error in Navbar Mobile

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#275]
The border/line between the back arrow and rest of the Navbar seems to be starting from middle of the button. Expected behaviour: [Figma Mockup](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A30170&t=KtX86WzuCf6UUSzI-0). Checked for Safari and Chrome.

![IMG_2992](https://user-images.githubusercontent.com/54861487/224425536-400c004d-18b4-41e7-a0d3-02e7cb4e223f.jpg)

**Comment by benalleng** [comment]
@vinayaksh42 Do you want to pick this one up?
