### ISSUE TITLE
NavBar /[lesson]/ path display

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#276]
At the moment the filesystem in our app is designed such that `/chapters/[slug]/[lesson]` this limits us to having only a single introduction page, specifically on `/chapters/chapter-1` before it moves on to the lesson content. Adding multiple introduction pages creates problems based on the 2 possible paths. 

1. Create a new dynamic path such that `/chapters/[slug]/[intro] OR [lesson]`. however, this is not possible according to @vinayaksh42 research on it in #259
1. [current method] Simply add any introduction page beyond the second one to the [lesson] path. However, this causes the site to treat the introduction pages following the first one AS a lesson, creating some confusion or at least it leaves us with a poorly optimized NavBar tracking; being incorrect most of the time.

Paths forward:
1. Allow the copy in each page be custom set in the NavBar and thus allow us to make it whatever we want but we would have to make it every time
2.  Find a way to redesign the [lesson] path to become a [page] path in which the layout is organized as follows:

#### Intro
-Will not display Challenge numbers in the NavBar
![image](https://user-images.githubusercontent.com/108441023/224435866-5e18772e-0880-49b9-85bf-2c65d14526ab.png)

#### Challenges
-Will display Challenge numbers based on the lesson content in the NavBar
![image](https://user-images.githubusercontent.com/108441023/224435948-9faa4e80-c8dd-414e-8133-dacd16d4d0cc.png)

#### Outro
-Again will not display Challenge info in the NavBar
![image](https://user-images.githubusercontent.com/108441023/224435990-c537025d-37e5-4130-abfa-ad4aee26219e.png)

our problem is that the intro and outro can be only one page each

**Comment by afterburn** [comment]
We should refactor how this chapter metadata is being utilized:
```ts
export const metadata = {
  position: 0,
  slug: 'chapter-1',
  intro: 'reaping-rewards',
  title: 'chapter_one.title',
  image: '/assets/images/chapter-1-cover.jpg',
  lessons: [
    'genesis-1',
    'genesis-2',
    'genesis-3',
    'transacting-1',
    'transacting-2',
    'transacting-3',
    'done',
  ],
  challenges: ['genesis-1', 'transacting-1'],
}
```

The `intro` could be named `intros` (or something similar) and its value should become an array similar to how `lessons` currently work. That would allow us to still only have a single intro page, but would also allow for more if necessary.

Is this required for the demo? If yes, I'll pick this up.

**Comment by benalleng** [comment]
Your call on if you think its necessary for the demo!

**Comment by ecurrencyhodler** [comment]
Kevin how big is the lift? I'm optimistic about including this for demo as we currently only have 1 pending issue.
