### ISSUE TITLE
First Challenge Complete page in the wrong location

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#283]
Following the completion of the first challenge there is no special page congratulating me!
[This page](https://savingsatoshi.com/en/chapters/chapter-1/genesis-4) needs to be moved just before the terminal challenge based on its copy. Also calls into question our use of terms, chapter -> challenge -> task/problem?

**Comment by ecurrencyhodler** [comment]
>[This page](https://savingsatoshi.com/en/chapters/chapter-1/genesis-4) needs to be moved just before the terminal challenge based on its copy.

I think this is more of a design/copy issue than a bug. Going to assign this to christoph to see. 

@GBKS we have a success page after Challenge 1 pt 1, but not for Challenge 1 pt. 2. I looked at the designs in figma and this was built to spec. Should we move the success screen to after Challenge 1 pt2? Or do we create a separate success page for it?

**Comment by ecurrencyhodler** [comment]
Actually I agree with @benalleng after looking at the screen. This screen should come right after Challenge 1 pt. 1. But will let Christoph confirm.

**Comment by afterburn** [comment]
Only problem being that in the Topbar for the genesis terminal lesson it will still say Challenge 1 even though users just got the message that they completed the first challenge on the previous screen.

I moved it to after the genesis terminal lesson because both the genesis input and terminal lessons belong to the same challenge.

**Comment by GBKS** [comment]
The idea here is to give the user a big thumbs up and make completing the first puzzle (using this as a user-facing term, independent of our internal terminology) like a special achievement (which it is). It's a unique page, there was no intent from my side to have this type of page after other puzzles (unless the story somehow requires or warrants it).

The check boxes at in the top bar are pretty subtle. Pretty sure user will not care much about a small checkbox showing up there. The copy and overall visuals feeling consistent is probably more important.

That being said, good catch that the copy doesn't quite match up right now. Moving the page seems like the better call here. I put together something in Figma for moving the page and adjusting copy, [please take a look here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2648%3A25696&t=rkpLiQrj1RkPvUk0-1).

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/695901/224636116-3233bd5a-d0c9-4907-b2b2-9f3cdf13d1e3.png">

**Comment by ecurrencyhodler** [comment]
Move this to "To Do" for eng.

**Comment by ecurrencyhodler** [comment]
With https://github.com/saving-satoshi/saving-satoshi/pull/294  we can move the transitional designs in figma. I'm a little worried 16bit may get confused when reviewing the copy.
