### ISSUE TITLE
Modal allows vertical scrolling in mobile

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#284]
With the horizontal scrolling for the avatars there also can be some odd snappy vertical scrolling that looks like below

It has to do with the lower address bar in the mobile screen on firefox, so I'm not sure how to fix it ATM

<img src="https://user-images.githubusercontent.com/108441023/224588339-f0e51e4e-ab4a-4b57-95f4-efb9eeffb7d1.png" width="200" >
Tested on Firefox on Android 

https://user-images.githubusercontent.com/108441023/228583943-76155fa3-d4c7-4506-b5d7-4ffb54801989.mp4

**Comment by ecurrencyhodler** [comment]
Can you explain this bug a little more? Are you saying that the mobile shouldn't have a vertical scroll for the profile page?

**Comment by benalleng** [comment]
It seems to be a firefox specific bug, when pulling the avatars from side to side you can inadvertently get some odd scrolling behavior, reproducing the problem makes me think it is more of a height problem than a scroll issue

**Comment by GBKS** [comment]
If not too much of a hassle, a short video would be super helpful to communicate this issue.

**Comment by ecurrencyhodler** [comment]
@benalleng do you have a video? If not I'm going to close this issue.

**Comment by benalleng** [comment]
Video posted! sorry It took a while to get around to it, I think it needs some scoping as it seems firefox specific

**Comment by ecurrencyhodler** [comment]
Hey ben sorry. Just following up here. I don't see a video that was posted. 😬 My bad for not catching it earlier.
