### ISSUE TITLE
Terminal challenge extends beyond view on mobile even when empty

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#285]
When the terminal challenge is empty the status bar is still barely visible.
<img src="https://user-images.githubusercontent.com/108441023/224588713-5fa17d80-6311-4ddc-989e-88e93485ec26.png" width="200" >
Tested on Firefox on Android

**Comment by ecurrencyhodler** [comment]
Same is true for iPhone chrome. 

This is specifically for challenge 2 pt 2. Other challenges are fine. 
![image](https://user-images.githubusercontent.com/32662508/224595767-da99a0f8-1f5b-43d6-8002-5591384a737a.png)

**Comment by GBKS** [comment]
Looks like the terminal has a fixed height of 600px defined ([code](https://github.com/saving-satoshi/saving-satoshi/blob/85079ed2b33cc6ff89c63445210941ca42c87079/ui/lesson/Terminal.tsx#L98)). This should be dynamic.

**Comment by ecurrencyhodler** [comment]
Closed by #308
