### ISSUE TITLE
Default behavior for Enter key in Transacting Terminal Challenge 

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#286]
When typing in the answer for Transacting Terminal Challenge I noticed that hitting the Enter key doesn't behave as expected on the first button press.
Also on first keypress the virtual keyboard is autocapitalized
### Expected Behavior
- 'Run' the code to progress the challenge

### Actual Behavior
- Normal newline behavior for Enter on the first press
- Hitting enter for a second time the Enter key behaves as expected 

<img src="https://user-images.githubusercontent.com/108441023/224589332-9e2c9a25-186f-4151-bc73-3af2362e9986.png" width="200" >

Tested on Firefox on Android

**Comment by ecurrencyhodler** [comment]
Hmmm. I didn't have any issues on iPhone chrome or Firefox. Can you try to replicate this again?
![image](https://user-images.githubusercontent.com/32662508/224596262-e7fa83a0-359a-4ac7-9716-7af976cf31e5.png)

**Comment by benalleng** [comment]
Confirmed I can replicate

**Comment by benalleng** [comment]
I also noticed that the terminal input has autocapitalization

**Comment by ecurrencyhodler** [comment]
This must be unique to android then.

> I also noticed that the terminal input has autocapitalization

Mine does as well. Let's create a separate issue for that.

**Comment by benalleng** [comment]
It works as expected after a space character, this seems to be due to how the virtual keyboard wokrs on Android, it doesn't track keyCodes as you type them

**Comment by benalleng** [comment]
[Here](https://developer.android.com/reference/android/view/KeyEvent) is some documentation describing the problem on Android.
