### ISSUE TITLE
Turn off Auto-caps in terminal for mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#287]
**Describe the bug**
Auto-capitalization is enabled inside the terminal for mobile. 

**Expected behavior**
Auto-capitalization should be disabled inside the terminal.

**Desktop (please complete the following information):**

This was reproduced on iPhone chrome/firefox and android firefox.

**Comment by GBKS** [comment]
I also noticed this one. Also saw that an extra space at the end of of a command makes it incorrect. Can we maybe add some trimming?

**Comment by GBKS** [comment]
This should be simple addition of the [autocapitalize](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize) attribute on the input.
