### ISSUE TITLE
Supported platforms page

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#295]
We should have a page or copy somewhere that lists the support platforms which are:

- Browsers (Chrome/firefox)
- Desktop (Mac/Pc/Linux)
- Mobile (iPhone/Android)

**Comment by satsie** [comment]
We might be able to just let this live in Notion for now. I don't think we want one more page to maintain until we are in a more stable state.

**Comment by ecurrencyhodler** [comment]
@GBKS Following up here. Is a one-liner in the about page good enough? If not, we can put it in notion.
