### ISSUE TITLE
UX: User can skip/miss the story if they use the challenges tab

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#296]
**Demo QA**

**Environment**: Linux (Ubuntu), Chrome (private browser, so cache is totally cleared)

**Background**: On the [chapters page](https://savingsatoshi.com/en/chapters), a new user has two ways of starting their journey:

- they can click "Start chapter 1" which takes them to https://savingsatoshi.com/en/chapters/chapter-1/intro-1, and they get the backstory
- they can click "Challenges", then "Genesis", which takes them right to the challenge: https://savingsatoshi.com/en/chapters/chapter-1/genesis-1

**Issue**: I think this is more of a UX question. Do we want this second flow to be possible? For the user to bypass the story screens?

**Possible solution**: If the user has not completed the Genesis challenge (if they don't have a check mark next to it in the list of challenges), clicking the challenge will take them to https://savingsatoshi.com/en/chapters/chapter-1/intro-1 . If they have completed the challenge, the current behavior is fine, and they should be taken straight to the challenge, https://savingsatoshi.com/en/chapters/chapter-1/genesis-1

I imagine this is could be a good first issue if we decide to implement the possible solution that is proposed.

**Comment by satsie** [comment]
Hmm... thinking about this a little more now that I've unlocked challenge 1 and am about to start challenge 2. To save ourselves headaches, we should probably have very minimal copy between challenges, especially any kind of copy related to the story. If we can draw clear boundaries where the user should and shouldn't expect to see story updates, we can drastically narrow the number of paths where they could accidentally miss something story related.

**Comment by GBKS** [comment]
Along the same lines, I think the "Start chapter 1" button on the chapters overview page should always take you to the current challenge you are working on instead of restarting chapter 1. We'll have to refine this logic a bit more.

**Comment by ecurrencyhodler** [comment]
Moving this "to do". Thanks ya'll for the feedback.

**Comment by vinayaksh42** [comment]
with PR #329, the user will not be able to see the content of the locked challenge if the user clicks on the challenges tab and selects a challenge that is locked. Instead the user will be asked to go back to the last unlocked challenge.

**Comment by ecurrencyhodler** [comment]
Let's use this issue to focus on the fix below and keep the general concept in mine as we continue working on v1:

"I think the "Start chapter 1" button on the chapters overview page should always take you to the current challenge you are working on instead of restarting chapter 1. We'll have to refine this logic a bit more." - Christoph.

**Comment by ecurrencyhodler** [comment]
Let's use this issue to focus on the fix below and keep the general concept in mine as we continue working on v1:

"I think the "Start chapter 1" button on the chapters overview page should always take you to the current challenge you are working on instead of restarting chapter 1. We'll have to refine this logic a bit more." - Christoph.

**Comment by GBKS** [comment]
I mocked this up [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3101%3A33013&t=JGRwXVeW9DLnPH48-1).

**Comment by shaavan** [comment]
@benalleng has implemented a solution for the original issue by making the "intros" part of the challenge-1, mitigating the chance of skipping the story.

However, this issue also hosts another suggestion of the "continue button" suggested by @GBKS [here](https://github.com/saving-satoshi/saving-satoshi/issues/296#issuecomment-1468032003).

To avoid confusion, let me open a separate issue addressing the "Continue" button suggestion.

**Comment by ecurrencyhodler** [comment]
This is being addressed by https://github.com/saving-satoshi/saving-satoshi/pull/366
