### ISSUE TITLE
Chapter 1: Able to access Challenge 2 without doing Challenge 1

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#297]
**Demo QA**

**Environment**: Linux (Ubuntu), Chrome (private browser, so cache is totally cleared)

**Issue**: In Chapter 1, the user is able to access the second challenge before completing the first challenge.

**Steps to reproduce**:

1. Start on the chapters page. Click the "Challenges" button to verify that the second challenge ("Transacting") is locked
2. Click "Start chapter 1"
3. You'll be on https://savingsatoshi.com/en/chapters/chapter-1/intro-1 . From there, click the "2" cell on the top right with a lock next to it. 
4. Verify that you are on https://savingsatoshi.com/en/chapters/chapter-1/transacting-1 and that you can continue.

**Other**: Doesn't seem high priority, but for the sake of a good experience, we probably don't want users attempting challenge 2 without the tools they gain from doing challenge 1.

**Comment by ecurrencyhodler** [comment]
Thanks stacie. This is being addressed in [this pr](https://github.com/saving-satoshi/saving-satoshi/pulls). Closing issue for now.
