### ISSUE TITLE
Copy: Chapter 1, Challenge 1 - Stale copy regarding hidden message

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#298]
**Demo QA**

**Environment:** Linux (Ubuntu), Chrome (private browser, so cache is totally cleared)

**Issue**: Need a sanity check here. I think this bit on the last sentence is stale copy: "and see if we can find the hidden message that was mentioned" 

![Screenshot from 2023-03-13 15-29-11](https://user-images.githubusercontent.com/1823216/224812395-2e03529c-864b-4a0a-acf2-dfdff70a7f76.png)

I don't recall a hidden message ever being mentioned in the new version of the story that we have deployed

Opening the issue here so it can be tracked with the project, but it's best to hash out copy changes in Figma.

**Comment by ecurrencyhodler** [comment]
Left a comment in figma and tagged you stacie!
