### ISSUE TITLE
Chapter 1, Challenge 1, Part 2: Quotes not accepted on echo command

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#301]
**Demo QA**

**Environment:** Linux (Ubuntu), Chrome (private browser, so cache is totally cleared)

**Issue**: The following command, with the scriptSig in single quotes, is valid and should be accepted as an answer:

```
echo '04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73' | xxd -r -p
```

You can confirm this by running it on your own computer

```
$ echo '04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73' | xxd -r -p
��EThe Times 03/Jan/2009 Chancellor on brink of second bailout for banks
```

**Actual result:** It is rejected

![Screenshot from 2023-03-13 16-09-31](https://user-images.githubusercontent.com/1823216/224820678-b402951e-01d1-40b4-b99a-90a405444430.png)

**Other:** I really don't know if this is worth fixing, and this issue may even be generalized to "I expect the terminal to behave like a real command line interface but it doesn't." I know reworking the terminal has been brought up before, and am not sure where we want to draw the line. Should the terminal behave like a real one? Is it fine to let it slide because this is a game made for learning? 

Another thing to consider is this behavior applies to people that didn't understand `$scriptSigHex` is a variable, or don't want to use it. The former would probably be a beginner coder, and the latter likely an intermediate coder. Either way, I question if it's worth the extra effort.

On another note, to my delight, the command without quotes works! This is awesome!

![Screenshot from 2023-03-13 16-26-51](https://user-images.githubusercontent.com/1823216/224824595-9e25780c-d6ec-41ff-9cd5-ce6a1538edd7.png)

**Comment by satsie** [comment]
On chapter 1, challenge 2, part 2 now and am seeing that this issue also applies.

**Comment by ecurrencyhodler** [comment]
Tested single and double quotes on both challenge 1 and 2 desktop chrome and mobile chrome and it works great.

One question I have is that should this also pertain to the variable?
<img width="1124" alt="Screenshot 2023-03-13 at 2 50 02 PM" src="https://user-images.githubusercontent.com/32662508/224840258-8824ccc5-9119-4bfd-b04e-2a9cb2a7f18b.png">
