### ISSUE TITLE
Add account access to the `NavBar` component

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#31]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/695901/207537242-6195d524-8ac5-42fd-bc6f-9d3585abaf1e.png">

<img width="324" alt="image" src="https://user-images.githubusercontent.com/695901/207537449-85e0cc8e-a81a-4dd9-b5cd-b285c498b605.png">

The nav bar should show a blank avatar icon when logged out, and the avatar image the user has picked when logged in.

Clicking this icon should show the account overlay to log in or out.

**Comment by aureleoules** [comment]
I'll work on this.
