### ISSUE TITLE
Clicking outside Login/Signup Model closes it.

### ISSUE THREAD

**Issue by shaavan** [saving-satoshi/saving-satoshi#316]
**Describe the enhancement**
When a user clicks outside the Login/Signup Modal modal, it shall close it. This would be a good improvement on the UX side.

**Comment by ecurrencyhodler** [comment]
Hi Shaavan. thanks for reporting. What browser and device did you test this on? I can't seem to reproduce it on desktop chrome or mobile chrome.

**Comment by benalleng** [comment]
I think he's saying we should Add this feature

**Comment by vinayaksh42** [comment]
> **Describe the enhancement**
> When a user clicks outside the Login/Signup Modal modal, it shall close it. This would be a good improvement on the UX side.

This will be a good add-on to the login/signup modal. Normally the user expects this behavior.
