### ISSUE TITLE
Make avatars selectable in signup modal

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#32]
![image](https://user-images.githubusercontent.com/695901/207543878-1174db7e-7a65-4f87-b62b-791867ac0038.png)

The user should be able to pick one of those avatars to identify them in the future.

This modal component is currently called `SaveProgressButton`, which is not quite right. I'd rename to to `SignupModal` or something like it.

[Design in Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=393%3A10917&t=Ir9L2sg7RUjtqKyc-1).

**Comment by GBKS** [comment]
Also, the "Done" button is not functional. I assume we'll be able to pass in a function callback to handle what should happen next. This modal can be opened from various places, so we need some flexibility there.

**Comment by aureleoules** [comment]
I'll work on this
