### ISSUE TITLE
Ch.2 L1: SHA-256 challenge

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#322]
**Current situation**
Our `<InputChallenge>` component has text on top and an Input field on the bottom.

**Desired situation**
In Chapter 2 users will need to be able to do sha256 hashing. They should be able to input text on the top and see the sha256 hashed output on the bottom of their screens (see [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019-26043&t=2hKSLjtWDaVqPH0h-0)).

Investigate whether it makes sense to update the existing `<InputChallenge>` component to support this functionality, or if it makes more sense to create a new component. The new code should be written in a way that allows us to easily apply other hashing algo's (or entirely other kinds of transformations) to the users input.

The sha256 algo can be implemented using a client-side using library such as [sjcl](https://www.npmjs.com/package/sjcl), see a code snippet [here](https://stackoverflow.com/a/48738430) (their docs are somewhat lacking).

**Comment by benalleng** [comment]
[docs](https://bitwiseshiftleft.github.io/sjcl/doc/)
[demo](https://bitwiseshiftleft.github.io/sjcl/demo/)
