### ISSUE TITLE
Ch.2 L3: Mining challenge

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#323]
In Chapter 2 Challenge 3 users will need to perform mining. We need to implement a UI that let's users start and stop mining, it should also display some statistics on the right (see [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2873-29990&t=QiZtLSzbb96QH3aE-0)).

My current train of thought is that we don't actually want to generate hashes until one is found that starts with five zero's, this is resource intensive and people might get the impression that we're actually trying to mine bitcoin for ourselves using their machine. I think it makes more sense to simulate the mining process instead.

This `<Mining>` component needs to periodically update the statistics to give the impression that something is happening, the numbers can be random as long as they make logical sense. After a fixed time has passed we can show a hardcoded hash starting with five zero's to the user.

There are a couple of elements in this `<Mining>` component that lend themselves well to reusability:
- The progress bar should become a standalone component.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/10757768/226626166-a278a5b7-d1bf-449c-80fa-058fef14f564.png">

- The stats card should become a standalone component.

![image](https://user-images.githubusercontent.com/10757768/226625882-d4d5c347-b165-4244-9461-097451727fdb.png)

**Comment by ecurrencyhodler** [comment]
@GBKS after our call on tuesday, we decided that vinayak would just go ahead and choose an arbitrary amount of time for a player to wait before they complete the mining challenge. This is to prevent the player from getting stuck mining for hours. Kevin will do the same for Lesson 2.

When we test Lesson 2 and Lesson 3 next week, we can see if this amount of time needs to be adjusted for both challenges.

**Comment by GBKS** [comment]
That makes sense. Within that time span, we may still want to introduce some randomness. For example, if we mine 1,000 blocks, to would feel more "realistic" if the time between mined blocks is randomized, and not consistent. We could also randomize the number of transactions confirmed per block.
