### ISSUE TITLE
Translation help Link

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#326]
Following the discussion in #148 we should add a link / tooltip that directs prospective translators to the translation readme <s>/ slack</s> via our language selector from #315.

**Comment by ecurrencyhodler** [comment]
I prefer the readme. The target audience are dev's so should be self-explanatory for them.

**Comment by vinayaksh42** [comment]
We can add a `your language` to the bottom of the language menu in italics or small font, which will redirect to a GitHub readme file.

Thoughts @benalleng @ecurrencyhodler ?

**Comment by ecurrencyhodler** [comment]
sgtm.
