### ISSUE TITLE
Develop the login modal

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#33]
This allows users to log back in and load their progress using their personal code ([designs](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=393%3A10941&t=Ir9L2sg7RUjtqKyc-1)).

![image](https://user-images.githubusercontent.com/695901/207553661-892aeb84-8f5e-4580-8a50-dbb7bf68c655.png)

**Comment by aureleoules** [comment]
I'll work on this.
