### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#331]
Right now the same user will always be logged in because in `/providers/AuthProvider.tsx` I have a hardcoded `private_key`, we should obviously pass the user's `private_key` instead.

I think @GBKS and whoever has a strong opinion on the matter should think about the best way to approach the login flow from a user's perspective. After creating an account users will need a way to enter their `private_key` to sign in. We currently have the modal below which users can use to restore their account, but with the new backend it's no longer possible to retrieve `private_key`'s from local storage, this means we cannot login users automatically after their access_token expires, and so the question is whether the modal below is the one we want to present to our users for logging in again, or whether we want a different way for users to enter their `private_key` to 'log in'.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/10757768/228575707-d8944835-9b51-4c3c-8644-c3a4e3ac70d2.png">

**Comment by GBKS** [comment]
This still looks good to me.

**Comment by ecurrencyhodler** [comment]
Closing this issue for now. We can revisit in later milestones.

**Comment by ecurrencyhodler** [comment]
Re-opening this issue. Kevin will provide more context.

**Comment by afterburn** [comment]
With our new backend system the account creations process goes like this:

1. User navigates to savingsatoshi.com
2. User clicks on user button, the "Sign in" modal pops up:

![image](https://user-images.githubusercontent.com/10757768/231211449-905411e3-2c15-4521-b6d9-55b4f226cb41.png)
3. The user has no account yet, so he/she clicks on "Dont have an account?", which opens the "Sign Up" modal:

![image](https://user-images.githubusercontent.com/10757768/231211886-85e8a33e-7765-40af-ad26-69aa7ecf00ee.png)
![image](https://user-images.githubusercontent.com/10757768/231211965-1945ecbe-cd1d-4da1-804e-356d00e57b34.png)

4. User creates an account by:
  a.  Choosing an avatar
  b. Either generate a private key (like we did before) and copy + save it, or enter a private key themselves.
5. User presses "Create account" button, which sends the data that was input to the backend, which creates a record in the DB.
6. The user clicks on his/her avatar, which opens the "Account" modal:
![image](https://user-images.githubusercontent.com/10757768/231212248-4daf5afd-364a-40e6-a088-3d85954da58e.png)
This allows users to logout, and in the future perhaps manage account settings (change avatar, etc).

As you can see from the screenshots @GBKS, I've done my best to come up with some layouts that make sense, but they are very much designed by a programmer, so I need your help to make this look pretty.

**Comment by ecurrencyhodler** [comment]
If I understand this screen correctly, if someone enters in a personally generated privkey an account will get created. Even if that is the case, I don't think we should have copy that tells them that. 

To make it simpler, we should just say something like: "Enter your private key to below to sign into your account and restore your progress".
<img width="534" alt="Screenshot 2023-04-11 at 9 23 45 AM" src="https://user-images.githubusercontent.com/32662508/231227279-cd124ac4-983f-43cf-8b9c-faba38b33f97.png">

Then if they don't, they can click the "Don't have an account" link.

**Comment by ecurrencyhodler** [comment]
>I'm also wondering if we maybe want to replace the user button with two links for "Sign in" and "Create account" for unauthorized users, to help them get where they need to be faster. 

Most platforms I use default to either signing in or creating an account. I think it makes sense to default to signing in for saving satoshi and then having them click another link to create an account because it's a game.

**Comment by adamjonas** [comment]
A learner creates an account after completing the first chapter. The first chapter is open to everyone and no progress is saved if a learner does not complete it. 

From my understanding, the current flow prevents learners from accessing chapter 1 without logging in. That creates an unnecessary hurdle and complexity of key management for curious learners from experiencing the game.

**Comment by ecurrencyhodler** [comment]
Reopening this issue. It seems as forcing a log-in before attempting ch.1 is too much friction.
