### ISSUE TITLE
Background color for lessons on top right is different during story intro

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#335]
When a player is in ch.1 lesson 1 during the story part, the background color on the top right is not dark. However when the player gets to the actual lesson content, it becomes dark. Is this intentional?

*During story part of the lesson*
<img width="1089" alt="Screenshot 2023-03-30 at 7 24 40 AM" src="https://user-images.githubusercontent.com/32662508/228682465-ac45f170-e8c0-4de9-a56f-07053e52c0bd.png">

*During the actual lesson content*
<img width="1097" alt="Screenshot 2023-03-30 at 7 29 47 AM" src="https://user-images.githubusercontent.com/32662508/228682474-bb74107b-b8ee-4e6c-bebf-83b710134ee6.png">

**Comment by benalleng** [comment]
If I'm understanding what is being shown, this is supposed to represent which challenge you are currently on

**Comment by ecurrencyhodler** [comment]
Right. I guess I would imagine the lesson box on the top right would be dark even if it's the story part of the lesson.

**Comment by benalleng** [comment]
So looking at this it is due to how those two pages are treated as intro-1 and intro-2, I think this is a good question to ask whether these are technically intros or are they a part of the first challenge?

**Comment by GBKS** [comment]
If it's easier for navigation and other logic, then I'm cool with making intro pages parts of challenges. That way we don't have these floating pages.
