### ISSUE TITLE
Add Spanish translation to Ch. 1

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#336]
Add spanish translation to Ch. 1.

**Comment by ggwilin** [comment]
Hello! Juan Sebastian here, i'm going to take this issue with me

**Comment by ecurrencyhodler** [comment]
@ggwilin Just following up here. Have you made any progress on this?

**Comment by ecurrencyhodler** [comment]
Closing this in favor of #361
