### ISSUE TITLE
Brainstorming on alternatives of using the recommended block explorer for the user.

### ISSUE THREAD

**Issue by shaavan** [saving-satoshi/saving-satoshi#338]
A few minutes ago, I was trying to go through the chapter-1 flow and encountered an issue that prevented me from progressing further.

In lesson `genesis-2`. I clicked the `View Block 0` button and encountered an issue from the Blockstream side.

**Screenshot:**

![image](https://user-images.githubusercontent.com/85434418/228860449-d32c96ef-507a-4551-937b-0f3e98bca20a.png)

So I tried to find some alternative block explorer to complete the challenge, and I could not find any good block explorer resource easily to progress further.

If a user encounters this issue while playing the game, they might get stuck due to something we didn't plan for.

This issue is to point out the potential problem and to get a consensus on,

1. Whether we should brainstorm on a "View Block 0" solution, which is not dependent on an external website over whose service we don't have control.

2. Brainstorming about providing users a sequential guide on completing the challenge if they don't want to/can't take the "recommended" route due to some reason.

**Comment by ecurrencyhodler** [comment]
Have you been able to repro the "esplora is unavailable" error? IMO chances of that are very small.

**Comment by shaavan** [comment]
The "esplora is unavailable" error was solved within 10 minutes of posting this issue.
However, this "dependence on external sources" seems like a potential cause of concern to me, so I posted this issue to get a consensus on what others think about this.

**Comment by ecurrencyhodler** [comment]
I don't think this is a major issue. If we have people report the unavailable error we can circle back.

**Comment by vinayaksh42** [comment]
I have contributed to the Esplora project in the past and in-general the chances of the website being down is relatively small. I think it will require a lot of work to remove dependence on external sources. Creating a page for displaying something similar to Esplora will take huge amount of time plus one of the motive of this project is to introduce the user to the world of bitcoin and I think it is essential for the user to get an exposure of a bitcoin block explorer.

**Comment by ecurrencyhodler** [comment]
Closing this issue for now. We can reopen if it becomes an issue later on.
