### ISSUE TITLE
Implement mobile version of ScriptingChallenge

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#341]
I haven't paid any attention to the mobile version of the `ScriptingChallenge` so presumably it will need some work to get it to match the design [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3013-28707&t=EBUyGkVSv51VyXPo-4). 

@GBKS asked me for some early feedback and one thing I think the design still needs is a Run button on the code tab itself, I'll assign this ticket to @GBKS and when he unassigns the issue that means its free for someone to work on as the design will then be finalized.

**Comment by GBKS** [comment]
This should be ready to go now. See the screens here, and [in Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3013%3A28707&t=JGRwXVeW9DLnPH48-1).

![image](https://user-images.githubusercontent.com/695901/229416828-8aaf4068-7a55-48ed-892d-fcc4c0fd86d7.png)
