### ISSUE TITLE
Improve Javascript "compiler"

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#342]
The Javascript "compiler" currently overrides some native Javascript functions like `console.log` to redirect logging to the Runner component, and `require` to make it seem as though the user is within a Node.js environment.

1. Validate whether we should continue with this approach, maybe I've overlooked some critical issues.
2. If we are continuing down the road of 'faking it', we should probably add more overrides and decide on what subset of javascript we want users to have access to. The code is running in an iframe so its relatively save, but still.

See `/ui/lesson/ScriptingChallenge/compilers/javascript.ts` for context.

**Comment by afterburn** [comment]
This is definitely not a must have for V1 @ecurrencyhodler, would classify this as a nice-to-have

**Comment by ecurrencyhodler** [comment]
Okay removing the v1 milestone for now. Thanks!

**Comment by afterburn** [comment]
We're not doing this anymore since we have a repl solution on the backend
