### ISSUE TITLE
Error handling route

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#358]
Currently error pages in production are simply blank pages

![image](https://user-images.githubusercontent.com/108441023/230650745-6184b34a-d98c-46c2-91df-4f1511dde1a3.png)

I think it would be helpful to have a general design for what we might want it to look like but as far as development it is very similar in construction to the 404 (`not-found.tsx`) page @sabakhilji just created.

perhaps a quick design mockup would be helpful though i think it could work if we kept it very similar to the design for the 404 page.

**Comment by ecurrencyhodler** [comment]
Let's stick with the same design for the 404.
![Uploading 224974597-61bb0922-b8e4-4a06-89b8-a89ceecda004.png…]()

**Comment by benalleng** [comment]
Ok then this will just be a quick copy-paste job!

**Comment by sabakhilji** [comment]
Can I do this copy-paste thingie?

**Comment by benalleng** [comment]
Hi saba definitely! I thought a little more about it and I think I'd like to have the copy be changed slightly to be more clear for us.

Heading: Hm.. something went wrong.
sentence_1: It's not quite clear what happened.
sentence_2: Our solocopter must have crashed!

**Comment by benalleng** [comment]
[Here](https://beta.nextjs.org/docs/routing/error-handling) is some quick documentation to take a look at, long story short it will be a file nearly identical to the `notfound.tsx` file just renamed `error.tsx` and have the copy slightly changed.
*no need to add any special `page.tsx` files like in your last PR

**Comment by GBKS** [comment]
I designed new 404 and error pages.

![Frame 335](https://user-images.githubusercontent.com/695901/232444061-5cd1b107-8928-4cab-9b1a-3d876786acde.jpg)

Could not think of anything clever for the error page, so I put in a holocat that hopefully looks a little startled and guilty. Let me know of any changes you'd like to see.

Designs are [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3359%3A30855&t=vDwiuycR4ZUj74nN-1), and export-ready frames are [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A25471&t=vDwiuycR4ZUj74nN-1). (the ones straight on the canvas with export-settings applied).

**Comment by sabakhilji** [comment]
@GBKS these designs are really great..... love Holocat it is super cute.
@ecurrencyhodler Yes I can do it, but what is the deadline for V1?
If it is tomorrow, can I work on it after V1?
