### ISSUE TITLE
Two different buttons with same functionality but different name | [Tell me more] & [About]

### ISSUE THREAD

**Issue by tilltonystark** [saving-satoshi/saving-satoshi#359]
The website's landing page features a secondary Call to Action (CTA) labeled "Tell me more", while the top navigation includes an "About" button. Clicking on either of these buttons will direct the user to the same page. @GBKS  @satsie 

![image](https://user-images.githubusercontent.com/89836460/230769856-2f5a7fec-a7c0-4e37-9c77-ffbe2474abeb.png)

**Comment by ecurrencyhodler** [comment]
That's a good call out. Should probably remove the "tell me more" but will let christoph comment.

**Comment by tilltonystark** [comment]
I'd prefer "Tell me more" over "about" as it's more prominent and easily accessible to users. But yeah let's see what Christoph will come with

**Comment by GBKS** [comment]
That is intentional and a common design pattern. Global navigations include a consistent list of links to all the primary parts of the site, and banners on specific pages highlight specifically what is relevant to the user in the given context.

**Comment by tilltonystark** [comment]
I understand the importance of global navigation. However, during my usability testing of the website, I noticed that using two different names for the same feature was causing confusion among the users. Since this issue may not occur frequently, should we overlook it, or should we consider renaming one of the buttons to avoid confusion in the future?

**Comment by ecurrencyhodler** [comment]
Gonna close this issue. If we get user feedback on this issue again, we can revisit.
