### ISSUE TITLE
Check that personal code (private key) is within secp256k1 range

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#36]
Users are able to save their progress with a personal code (aka a private key) that is generated in [`components/chapters/SaveProgressButton.tsx`](https://github.com/saving-satoshi/saving-satoshi/blob/master/components/chapters/SaveProgressButton.tsx#L41)

![Screenshot from 2022-12-16 14-04-18](https://user-images.githubusercontent.com/1823216/208170460-78d99b5a-f743-4cfe-9ee3-227e506a9f9d.png)

This key is a random 64 digit hex number (aka 256 bits).

As a user, I would like to use this code to generate addresses of my own in chapter 3. In order for this to work, the secret key must be smaller than 1.1578 * 10^77 (a number that is slightly less than 2^256). 

I'm not sure what the chances are of a random 256 bit number being larger than the acceptable range. That will probably determine the priority of this ticket. However, if we don't add a check, it will result in some kind of instability in the chapter 3 challenges, because those challenges have the user generate a public key (aka a point on the secp256k1 elliptic curve) from this secret key. 

Possibly a good first issue?

**Comment by aureleoules** [comment]
Fixed with #37.
