### ISSUE TITLE
Change color of Ch.2 challenges to red

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#360]
Right now Ch.2 challenges have the same color as Ch. 1 challenges.
<img width="1273" alt="Screenshot 2023-04-09 at 9 49 32 AM" src="https://user-images.githubusercontent.com/32662508/230785599-8e624bf6-bf33-4df4-a874-6d32fe067e1e.png">

Let's update them to the red background in figma. 

![Wireframe - 52](https://user-images.githubusercontent.com/32662508/230785565-7e1b3b9f-fb4b-4167-a02c-c0a9ee8116a1.png)

**Comment by ecurrencyhodler** [comment]
This is prob. best handled after the lessons are merged.

**Comment by sabakhilji** [comment]
Hey, can I have a look at this after #333 and #349 completion?

**Comment by ecurrencyhodler** [comment]
Hey Saba! Looks like Ben is already taking a stab at this one. I'll keep you posted on its progress though.

**Comment by sabakhilji** [comment]
oh okay, no problem :)

**Comment by tilltonystark** [comment]
Should we also change the color from Chapter 2 to Chapter 3 if we decide to switch the color scheme from Chapter 1 to Chapter 2? With 10 chapters in total, it might be challenging to assign different colors to each chapter.

If red was chosen intentionally to give a feel of challenge or toughness to the user. Then better we change the color of the interface when the level of challenge is increasing in each chapter.

**Comment by ecurrencyhodler** [comment]
Hey @GBKS. WDYT?

**Comment by GBKS** [comment]
Yes, each chapter has its own color theme, but this is not a functional color-coding (red=difficult, etc). It's more about giving each chapter its own feel, to go along with the images used in each chapter. A chapter that is set at night, where the protagonist peacefully hacks away at their computer can use a darker, calm blue tone (maybe a gradient to a slight yellow). The 51% battle is more intense and the color can reflect that (without going overboard with a hyper-aggressive red).

There are pretty much infinite colors and color combinations out there (unless you restrict yourself to primary colors or another limited palette), so I don't see any problems finding enough.

The UI is constructed of white and black elements with transparency, overlaid over a color gradient. This allows us to not have to change anything about the UI elements themselves when we want to slightly change the feel. We simply need to change the background. This makes it necessary for the backgrounds to be light/dark enough for enough contrast with our overlaid black/white bits.

That being said, the current iteration of the images is not our final iteration. They will change, and we may tweak the background colors along the way. However, these are minimal changes that just require uploading a new image and changing a color variable.

That's how I see it at least. What are your thoughts?
