### ISSUE TITLE
Adding Spanish translation

### ISSUE THREAD

**Issue by SuperAtic** [saving-satoshi/saving-satoshi#361]
Hey there, please let me know if there's any reviewer interested in proofreading the Spanish translation. It will be ready in few days. Thanks for creating and sharing Saving-Satoshi 🙏

**Comment by ecurrencyhodler** [comment]
Maybe @ggwilin will? He was assigned #336 but haven't heard back. But don't let reviewing the spanish translation be a blocker for submitting a pr!

**Comment by ggwilin** [comment]
Haven't had much time, i had time today to start with this, so happy to check @SuperAtic  translation, will you submit a PR where we can work together?

**Comment by SuperAtic** [comment]
Anytime, feel free to connect with @VEINTIUNO

**Comment by ecurrencyhodler** [comment]
Closed by [#362](https://github.com/saving-satoshi/saving-satoshi/pull/362)
