### ISSUE TITLE
Background for the "need help" button is off

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#365]
When you hover over the "?" button on the top right, the background color is blue instead of green. 

<img width="381" alt="Screenshot 2023-04-10 at 8 37 40 AM" src="https://user-images.githubusercontent.com/32662508/230935467-3d31b11b-19fd-4e5f-9bf0-1d347528691e.png">

**Comment by sabakhilji** [comment]
Ya sure!!!

**Comment by benalleng** [comment]
Take a look at #325 for understanding of how it works!
