### ISSUE TITLE
'Start Chapter-1' button should take to current challenge

### ISSUE THREAD

**Issue by shaavan** [saving-satoshi/saving-satoshi#373]
**Describe the enhancement**

"The "Start Chapter 1" button on the chapter overview page should always take you to the current challenge you are working on instead of restarting Chapter 1." - Christoph

**Comment by shaavan** [comment]
One possible solution I researched is to get the user progress information and use the data to direct the user to the latest challenge they are on in a particular chapter.

This approach requires using the user's data stored in local storage. But with #158, we aim to change data storage from local to the backend. It's best to keep this issue on hold until we have transformed the storage logic.

**Comment by GBKS** [comment]
Here's a [design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3101%3A33013&t=SsCek3U9TV2ga0TP-1) for this, the button simply reads "Continue".

**Comment by shaavan** [comment]
> Here's a [design](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3101%3A33013&t=SsCek3U9TV2ga0TP-1) for this, the button simply reads "Continue".

Thanks for tagging that, @GBKS! However, the functionality change of directing users to the current challenges requires reading their progress, which is dependent on backend implementation.

IMO it's best to implement design and functionality change simultaneously in this case!
