### ISSUE TITLE
Search other fellow users on the website

### ISSUE THREAD

**Issue by monishkajha17** [saving-satoshi/saving-satoshi#383]
![Screenshot (541)](https://user-images.githubusercontent.com/109274817/232139201-e218b7ad-908b-49b5-be5b-343d02f35444.png)
There is no username kind of thing on the profile section of the user. As we somebody wants to search anyother user it is not possible at now. Before starting the chat forum we need to usernames to the user account so that it can be used in chat forums as well by mentioning the user and would be able to search them as well.

**Comment by ecurrencyhodler** [comment]
Hey monishkajha17. Thanks for submitting this issue.

We are actually taking a different approach to profiles and user accounts. We want profile log-ins to be based on secrets rather than emails/usernames/passwords. 

We also don't expect users to look or search for one another. 

Does that address your concern?

**Comment by monishkajha17** [comment]
Okay, so users can't search each other that's fine. But like if we make a community forum for the users where they can hang out with each other ask their doubts over there. So that will also work from pubkey

**Comment by ecurrencyhodler** [comment]
Hmmm we currently don't have any plans to create a community forum. 

Also not sure if you were able to find our [notion page](https://leaf-singer-0fc.notion.site/Saving-Satoshi-a4aa560d071646f8af7484d923a0b399). It's kind of hidden. 😅 But it has some great context about the history and goals of the project. 

Going to close this issue for now but thanks again for the suggestion!
