### ISSUE TITLE
Implement new designs for 404 error pages

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#386]
Here are the new designs for 404 error pages. This is not essential for v1.

![232444061-5cd1b107-8928-4cab-9b1a-3d876786acde](https://user-images.githubusercontent.com/32662508/232549844-f2b86cb6-c47d-4e13-b4ad-1eaed71486b6.jpg)

Could not think of anything clever for the error page, so I put in a holocat that hopefully looks a little startled and guilty. Let me know of any changes you'd like to see.

Designs are [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3359%3A30855&t=vDwiuycR4ZUj74nN-1), and export-ready frames are [here](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2323%3A25471&t=vDwiuycR4ZUj74nN-1). (the ones straight on the canvas with export-settings applied).

**Comment by ecurrencyhodler** [comment]
Ooo that could be fun. I think the biggest blocker would be the actual design. If we get that, then we can compare!

**Comment by sabakhilji** [comment]
Hey, I want to work on this issue. Can I??
