### ISSUE TITLE
Clicking the next button on a lesson takes to its `en` version.

### ISSUE THREAD

**Issue by shaavan** [saving-satoshi/saving-satoshi#395]
**Describe the bug**
Clicking the next button on a lesson takes to its `en` version instead of the one the user selects.

**To Reproduce**

1. Go to https://savingsatoshi.com/es/chapters/chapter-1/intro-1
2. Click on "Continuar".
3. Notice that the intro-2 is in `en` language
4. This is true with other lessons as well. Clicking on next defaults to `en`.

**Expected behavior**
It should take to the page's variation in the language the user selects.

**Screenshots and/or logs**

https://user-images.githubusercontent.com/85434418/233089219-9fc9b3e9-5fa4-462b-a808-472efc8f81b7.mov

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser: [Chrome]

**Comment by benalleng** [comment]
Ok, so This has to do with how the function `getNextLessonPath()` works in `lib/progress.ts` It is directing the user to a bare url without a locale so because we have our language set to English I presume, it is taking us directly to the `en/` route

**Comment by benalleng** [comment]
```
export const getNextLessonPath = (userProgressKey: string): string => {
  const id = keys.indexOf(userProgressKey)
  const result = keys[id + 1]

  if (!result) {
    console.error('There is no next lesson')
    return keysMeta[userProgressKey].path
  }

  return keysMeta[result].path
}
```

**Comment by sabakhilji** [comment]
Yes, the same happened in Windows 10. After the sign-up modal further pages continue in English.
Also, every time the intro page is in the desired language but Chapter1 genesis is in English.
