### ISSUE TITLE
going back to last completed challenge

### ISSUE THREAD

**Issue by sabakhilji** [saving-satoshi/saving-satoshi#397]
**Describe the enhancement**
Let's say I am on Challenge 2 and by mistake, I pressed the power button I have to redo all the challenges again although I was already logged in.

Is there any way for an already logged-in user to reach the last attempted challenge skipping off all the challenges which are already finished?

https://user-images.githubusercontent.com/52318459/233114226-997efa56-2332-499b-ba0a-efb2af743eaf.mp4

**Comment by ecurrencyhodler** [comment]
Yeah the browser back button is the move here. Closing this for now. Let's see if people default to the power button for the back button. If so, then we may need to adjust the design.
