### ISSUE TITLE
Learner Progress

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#4]
As a learner, I have some sense of how many tasks I've completed and how many more I have to complete.

**Comment by ggwilin** [comment]
We can measure progress using the code challenges inside every lesson, it is much simpler than tracking every time that a user clicks next after reading all the introductory/lesson part (but if we have to, we'll do it).

What Exercism seems to do is that every-time a challenge is passed(tests are working) they generate a solution, to thats how they can respond whenever a user asks: ¿Whats my current progress, how many and which challenges have i completed?

**Comment by GBKS** [comment]
Overall progress will be visible on the Chapters page (see here in [Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=642%3A10501&t=Ir9L2sg7RUjtqKyc-1)). When you're in a chapter, the top bar indicates your progress.

We deal with a linear sequence of chapters and challenges, so from a technical side, maybe it's enough to just track which chapter & challenge the user is on at the moment? 

Any way to update the title of this issue to a more narrow scope?

**Comment by GBKS** [comment]
#86 partially addresses this.

**Comment by adamjonas** [comment]
Going to close this meta issue for now given we have more discrete tasks to focus on.
