### ISSUE TITLE
Update copy on website to remove mentions of demo

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#402]
Update copy to remove mentions of this being a demo.

- [ ] Home page
- [ ] Chapters page

**Home Page**
<img width="677" alt="Screenshot 2023-04-21 at 12 45 18 PM" src="https://user-images.githubusercontent.com/32662508/233722222-c55eec8c-90bc-4f3d-aa93-123b7d4780b8.png">

**Home page**
<img width="989" alt="Screenshot 2023-04-21 at 12 45 29 PM" src="https://user-images.githubusercontent.com/32662508/233722200-129a0b1c-a3d4-473d-90d9-84f186ddefdb.png">

**Suggested copy**
Home page: Start the demo -> Play the game

Chapters page: Blocked by #381

**Comment by GBKS** [comment]
On the home page, I'd just use a simple "Start".

![image](https://user-images.githubusercontent.com/695901/235107892-ef6fa8bf-0841-4880-b604-ca9e15415169.png)

For the chapters page, how about replacing the demo disclaimer with a bit of text that both informs users that a bit of coding experience is required, and also let's them know that we'd like their input?

![image](https://user-images.githubusercontent.com/695901/235108105-5cb35fc3-0257-4406-a25a-d4112bf3590d.png)

Here's the [Figma link](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=3634%3A37469&t=13l3as2iUxjzNSqI-1).

**Comment by ecurrencyhodler** [comment]
Love it. Thanks christoph

**Comment by vinayaksh42** [comment]
Can I work on this issue?

**Comment by ecurrencyhodler** [comment]
Yes!
