### ISSUE TITLE
Update copy in account login flow

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#406]
Our copywriter suggested the following copy changes to the "Save Progress" flow.

This flow appears at the end of Ch.1 when the player is prompted to save their progress.
<img width="573" alt="Screenshot 2023-04-25 at 2 23 14 PM" src="https://user-images.githubusercontent.com/32662508/234407192-ff909da0-d859-471b-bb99-634eb6f32122.png">

Then they are taken to this screen:
<img width="373" alt="Screenshot 2023-04-25 at 2 03 48 PM" src="https://user-images.githubusercontent.com/32662508/234405250-388ccb74-b582-4c4d-a1df-bf9ed6368e69.png">

I believe this is a new flow that must be created separately from the "create account" flow we currently have. @GBKS is this flow intended to be separate from creating an account?

**Comment by GBKS** [comment]
This is the flow we had originally designed (then we made adjustments for the demo), so I don't think there is anything new here.
