### ISSUE TITLE
Improve UX on user typing

### ISSUE THREAD

**Issue by grunch** [saving-satoshi/saving-satoshi#408]
I just found something that is a not a big issue but I think it would improve the UX, both ways are ok but only one is accepted as correct.

![image](https://user-images.githubusercontent.com/228364/234698130-d3222aac-a61b-419d-855f-f39c68af2e08.png)

As in a real unix terminal 

`echo aabbcc | xxd -r -p`  == `echo aabbcc| xxd -r -p` == `echo aabbcc |xxd -r -p`  == `echo aabbcc|xxd -r -p`

**Comment by ecurrencyhodler** [comment]
Thanks for reporting this grunch! Let me raise this with the engineers to see if we have some availability. 

Right now our terminal is implemented client side and isn't an actually working terminal so we have to manually account for each accepted value.

**Comment by afterburn** [comment]
I think we can get around the issue of having to manually account for each possible input value by changing how we parse and validate the answers. Left a comment about that [here](https://github.com/saving-satoshi/saving-satoshi/pull/414#pullrequestreview-1403474394).
