### ISSUE TITLE
Refactor terminal user input parsing & validation

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#417]
As I mentioned in #414 in [this comment](https://github.com/saving-satoshi/saving-satoshi/pull/414#pullrequestreview-1403474394) I think our approach to how we parse and validate user input could be improved for the Terminal Challenge. Instead of replacing characters in the user input until we hope that the string now matches the expected answer, we should tokenize the user input into an array of strings and compare that against an expected answer (which is also an array of strings).

I demonstrate the solution in this [jsfiddle](https://jsfiddle.net/q4y7r2gp/).

**Comment by tilltonystark** [comment]
Seems a really good solution to minimize error

**Comment by benalleng** [comment]
Closed as no longer relevant with new repl system
