### ISSUE TITLE
Fix tooltip styling

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#422]
Something has happened to the tool tip styling, not sure when. This used to match the designs.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/695901/235683694-fb2b7bbd-883e-4778-b643-1d019724a475.png">

Desired look ([Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=2019%3A22776&t=a2nrfSs8Hc1yKO4I-1)).

![image](https://user-images.githubusercontent.com/695901/235683907-31f2116c-95ee-4177-b092-23a9b80b1407.png)

**Comment by ecurrencyhodler** [comment]
This is seen in chrome. Looks fine in Safari.

**Comment by benalleng** [comment]
@GBKS I am getting started on this PR and I wanted to ask you if you think transitioning tooltips over to a "mono-theme" as our chapters have gradients while I think we can agree that a small space like the tooltip has such a small area the gradient is jarring
