### ISSUE TITLE
Super heavy First Load JS. Can it be a problem?

### ISSUE THREAD

**Issue by shaavan** [saving-satoshi/saving-satoshi#423]
I have noticed while building the master that the first load js has gotten quite massive with each new development.

<img width="1117" alt="Screenshot 2023-05-02 at 7 46 04 PM" src="https://user-images.githubusercontent.com/85434418/235693438-8b7bdf0e-7ef6-48e8-80f7-c00b6b78441d.png">

I read that this can cause SEO-related problems. Though right now, our goal is to complete the development over optimization. Is it possible that this optimization problem becomes too big to solve once we go deeper into development?

**Comment by ecurrencyhodler** [comment]
Thanks for flagging this. Let's discuss on our call today.

**Comment by GBKS** [comment]
Just checked the live site against PageSpeed Insights and we get 98% performance on mobile and 100% performance on desktop. [Test link](https://pagespeed.web.dev/analysis/https-savingsatoshi-com/mrt4iqzknj?form_factor=mobile). The chapters page gets 85% of mobile and 100% on desktop.

Just from that quick test it does not look like we have an urgent problem. Maybe close this issue?

**Comment by ecurrencyhodler** [comment]
SGTM
