### ISSUE TITLE
Set up a way to distinguish desktop and mobile layouts in code

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#43]
Some pages render totally different layouts in desktop and mobile (code challenges). So those classes need to know which mode they are in. What's the best way to handle that centrally in React? Global state? A utility function?

I know how I'd handle this in Vue, but not really sure what the best approach is in React.

**Comment by aureleoules** [comment]
We can apply tailwind classes based on the size of the screen, see https://tailwindcss.com/docs/responsive-design.

**Comment by GBKS** [comment]
For certain changes, we need the UI to render differently and Tailwind classes are not enough. I am introducing the `react-responsive` module in #48 for this.

**Comment by aureleoules** [comment]
Fixed by #48.
