### ISSUE TITLE
Manually typing in url to navigate redirects me to Ch. 2

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#457]
I have completed Ch. 2. I went back to Ch. 1 to do some QA. I manually typed in the url for the outro for ch. 1 when I was in Ch. 1. I then got redirected to the outro of Ch. 2.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/13caf5c4-9a2b-4409-98eb-d583f87f4cc9

**Comment by benalleng** [comment]
Figured this one out, it is redirecting because I accidentally am saving to a nextLessonKey at the end of CH2 even though no next lesson exists

**Comment by benalleng** [comment]
additionally the logic of the redirect doesn't work exactly as I expected
