### ISSUE TITLE
formatHash needs to allow for multiple colors

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#458]
the formatHash helper function returns the hash in a specific color but we need it to be different colors based on the user's progress in the hashChallenge

**Comment by benalleng** [comment]
@vinayaksh42 there seems to be some odd behavior of colors in the formatHash function, do you have any insight on why this might be the case, I see you used !important for some of your color classes in your mining challenge

**Comment by vinayaksh42** [comment]
@benalleng `!important` is not being used within the lib/formatHash.tsx helper function. Within the mining challenge `!important` is only being used twice:
1. Switching between the default and highlight border (towards the end of the challenge).
2. Changing the color of the hash number provided by the lib/formatHash to #5DBC59 green but I don't think it should affect the lib/formatHash as it is being applied locally within the mining challenge.

**Comment by vinayaksh42** [comment]
We might have to do a little work on the lib/formatHash helper function in order to make it more customizable. Maybe adding extra props for changing the color or the way the hash is displayed (row-wise or column-wise).
