### ISSUE TITLE
Ch.2 Mobile design issues

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#460]
Ran through savingsatoshi on iPhone Chrome. 

There are 3 issues that I found:

- [ ] Button on Ch.2 Challenge 3 is off. The play button is larger than the box it's supposed to be in.
![IMG_2634](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/f5c616ec-c11c-439a-8198-05152b779528)

- [x] Ch.2 Challenge 1 hint. Is it supposed to be transparent? If so disregard.
![IMG_2633](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/dcbcde3e-4f44-47f8-b04b-1e0d6b59af97)

- [x] Ch.2 Challenge 3 When all blocks are found, the 1000 is missing a comma. The same is true on desktop.
![IMG_2635](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/274bbce8-d457-47f3-afb0-08a877cedf48)

**Comment by vinayaksh42** [comment]
Working on the third part of this issue

**Comment by GBKS** [comment]
Adding two small ones to this report (let me know if you'd like me to create a separate issue), from Safari/iOS.
- When focusing the code editor, the screen slightly zooms into that area. Parts of the code is now hidden, and you have to close the keyboard and pinch to zoom out again. We should be able to prevent this zoom.
- In the execute tab, the code output should be shown fully (and not cropped by the button box).

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/4d94feeb-d142-4133-a158-728836ac9d19)

**Comment by GBKS** [comment]
Sorry, two more.
- The blank avatar icon is too big
- The layout (and some text details) of the chapter end screen is not quite right. The text covers the whole image, you can't really see what's going on.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/e8ecce88-1302-43e9-9be1-450f0c936f90)


![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/62f7d538-db35-4e94-b710-d6a9c23bb14e)

**Comment by ecurrencyhodler** [comment]
Hey Christoph, thanks for filing these. I think it's better to create separate issues so we can also assign them to different contributors.

**Comment by GBKS** [comment]
Did you already create new issues or do you want me to?

**Comment by ecurrencyhodler** [comment]
I just made one!
