### ISSUE TITLE
Ch.2 iPhone/Firefox: Start of Ch.2 takes me to text and I don't see the image.

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#462]
I started Ch. 2 on iPhone/Firefox and it takes me straight to the text and I don't see the image. Starting Ch.2 should take me to the top of the page, not the middle of it I would think.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/c739e32c-94ff-483f-8a04-213240d0a10a

**Comment by ecurrencyhodler** [comment]
@vinayaksh42 do you think you can take this one?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 do you think you can take this one?

Sure
