### ISSUE TITLE
Chapters page mobile layout issue

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#476]
As you can see in the screenshots below, the lock icon is gigantic. Probably just missing width/height properties. A secondary small thing is that the spacing on the right between the title and button is too big.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/ec6ed12f-2e62-4b6a-a36c-76b4dd873933)

**Comment by vinayaksh42** [comment]
> @GBKS what device is this on I am unable to replicate this bug?

It is Safari browser on iPhone.
This problem occurred when we shifted to the new way of storing icons.

**Comment by GBKS** [comment]
You may also want to remove `width` and `height` attributes from the SVGs. I've had problems in another project before where those conflicted with CSS width/height attributes. As long as the SVG has a `viewBox`, it should be fine (just need to ensure to always be explicit about the size.
