### ISSUE TITLE
Implement Ch3 outro functionality

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#480]
Currently the end screens have their progress tracked such that If i reach the end screen but don't hit the continue button I 'technically' have not completed the chapter.

This isn't a problem for chapter 1 as we are demanding that the user sign in but or subsequent chapters they should already be logged in and as such can quit the chapter without progressing.

This question came up when dealing with this set of PR's #472 and #477 whereby we introduced a way for the user to continue and be automatically directed to the next chapter. If the user quits the outro screen rather than continuing they may feel like they completed the lesson having been congratulated but their progress will remain in that chapter `CH(#)OUT(#)` instead of being at the start of the next chapter `CH(#+1)INT1`.

While this is a small issue i decided it was worth some discussion for enhancing user flow

Should the final lesson of each chapter be skipped, saved, or neither?

**Comment by vinayaksh42** [comment]
What about saving the progress for the outro pages as soon as the user arrives on the page. Technically the user is not supposed to do anything once they arrive on the outro page so it might be logically to straight away store the progress as soon as the outro page loads.

**Comment by ecurrencyhodler** [comment]
If we go with this approach, we could use the button to collect feedback. @GBKS curious on your thoughts here. I kinda like that it is auto-saved for the user.

**Comment by GBKS** [comment]
Yes, we only need the manual save progress thing after the first chapter when they don't have an account. Afterwards we can auto-save. At the end of the last available chapter (where we haven't implemented the next one yet), we can ask for feedback since it's the end of the experience (for now). Otherwise we can show the continue button.

**Comment by ecurrencyhodler** [comment]
Let's turn the button in Ch.2/outro-1 into a "give feedback" button. @benalleng also suggested turning this into a component that can be reused as we add future chapters.

**Comment by vinayaksh42** [comment]
the progress for chapter-1 is being saved manually when the user creates account and at the end of chapter-2 we are displaying feedback form (PR #490). We won't be able to make progress on this issue as we only have 2 chapters right now. 

Maybe we should move this issue to backlog as we only have 2 chapter @ecurrencyhodler ?

**Comment by ecurrencyhodler** [comment]
Updating this ticket to work on two issues:

- [ ] Auto-save progress at the end of the chapter. Make it reusable so we can continue to add it as we add more chapters.
- [ ] Fix background image non-reduction mentioned in https://github.com/saving-satoshi/saving-satoshi/pull/531#issuecomment-1607519826.  "In the Figma mockup the background image is reduced in size and completely displayed, followed by the text. Where as in the preview of this PR the image is displayed differently."
