### ISSUE TITLE
Ch.2 Challenge 3 - Put small hashes in a row, not column

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#489]
The small hash is displayed in columns - should be rows. See image below.
![239549946-e8800aa3-f306-46e5-a9ca-2481420b5d4b](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/4bec154b-2909-4e51-bcc9-3f0c3a13c213)

This will require changes to the lib/formatHash.tsxfile which is being used in other challenges as well so we might have to add an extra prop for changing the order in which the hashes are displayed.

**Comment by benalleng** [comment]
At the moment the format hash function in `MiningStatisticsNonce.tsx` is using the formatHash function as such
```
        (blockFound % 4 === 0 && blockFound !== 0)) && (
        <div className="order-last flex items-center justify-center">
          <div className="flex  w-[76px] overflow-hidden font-space-mono text-[6px] !text-[#5DBC59]">
            {formatHash(finalHash, 4, 4, 64, false, true)}
          </div>
          <Icon icon="greenCheck" className="h-8 w-8 py-2 text-[#5DBC59]" />
        </div>
```

This code should be returning the hash into 4x4 rows with a total length of 64 but instead it seems to be returning columns instead

**Comment by benalleng** [comment]
@saba I got a new method working for the formatHash() function but the change is quite a doozy! you can take a look here in my repo
https://github.com/benalleng/saving-satoshi/tree/hash-formatting
