### ISSUE TITLE
Got stuck at chapter 2 mining 1

### ISSUE THREAD

**Issue by sabakhilji** [saving-satoshi/saving-satoshi#500]
While testing the latest production version I found this:
![Screenshot (107)](https://github.com/saving-satoshi/saving-satoshi/assets/52318459/b78904fc-e7dc-4f08-8dd8-36486075cf8e)
 

not able to move forward in the challenges.

**Comment by ecurrencyhodler** [comment]
Interesting. I think I faced a similar problem but couldn't reproduce it. https://github.com/saving-satoshi/saving-satoshi/issues/471

Can you repro this? If so, what were the conditions?
