### ISSUE TITLE
Create Intro page for Chapter 3

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#501]
Page 1:
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/3524f57c-61e3-4b6d-9dcd-f396994e9fb8)

Page 2:
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/edd5cfc7-a504-4fb1-bcdc-6713b377d337)

Should follow the same conventions as intros for chapter 1 and 2

**Comment by ecurrencyhodler** [comment]
Included in this issue should be to update the copy we see in light of the new story we've developed. 

Title of Ch.3 is now "51% attack". You can see the changes in our [narrative doc here](https://docs.google.com/document/d/1m3FcsjI7IYGwCrNyaMJWzPEtKzKf1wJcRXouzowtlEA/edit?usp=sharing).

The intro text to Ch. 3 should be the following:

You enter the address of a block explorer and sure enough, blocks are back to ten minutes intervals. Somehow, holocat sleeps through the noise of the machines. 

However, something is off. The blocks are empty, and transactions aren’t processing. Did you make a mistake? Could this be a coincidence? Another message pops up on the computer screen, waking holocat. It’s not a coincidence.
