### ISSUE TITLE
Create Outro page for Chapter 3

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#502]
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/5dfd7bfa-30ee-4799-af21-089915d0245d)

Should follow the same conventions as outro pages for chapter 1 and 2

**Comment by ecurrencyhodler** [comment]
Not sure if the scope is too large for this issue to add another one, but we did want to address https://github.com/saving-satoshi/saving-satoshi/issues/480 as well once we added another Chapter.

**Comment by afterburn** [comment]
I think we can address them separately, where this issue is focusing more on creating the markup/styling needed for this page whereas #480 is more aimed at functionality, as such they can be addressed separately imo and we can keep issues relatively small which is better for reviewing.

**Comment by ecurrencyhodler** [comment]
SGTM.

**Comment by benalleng** [comment]
As for the `secondaryTheme` I think that `#3c5c6e` is a good dark contrasting color to match the theme of the page,
_taken from the top of the image_
