### ISSUE TITLE
Chapter 3.1 - Solo vs Bitrey lesson (Lose)

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#504]
Using the `HashrateChallenge` component we created in https://github.com/saving-satoshi/saving-satoshi/issues/503 implement the Co-op vs. Bitrey (Lose) challenge. In this challenge the player and cooperators will go up against Bitrey. They lose this round because they didn't split the nonces when working together.

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=4102-52875&t=LZXGkrObhw4Swxjv-4)

**Comment by ecurrencyhodler** [comment]
Updated the issue title and description to match story line in figma.
