### ISSUE TITLE
Create Chip component

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#508]
In Chapter 3 we need to create a `Chip` component we can use to display some data on top of user avatars:
Lets create a component that can support the variants shown below:

![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/b9a6e995-8ffc-4ca2-8b47-312efb4d4520)
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/9fbecfd8-4cb6-4a6a-ad1b-c8e4778ec3a5)

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=4228-70031&t=eCkKSeUA1EDezOwi-4)

**Comment by ecurrencyhodler** [comment]
Chip should transition nicely between stages.

**Comment by sabakhilji** [comment]
@GBKS does the color of this component vary with every chapter according to the theme?

**Comment by sabakhilji** [comment]
@shaavan

, I think there is a slight difference in the picture of the cat here. In your chip component full picture of the cat is present while in Figma dimension of the cat picture is 25px* 25px.
![Screenshot (109)](https://github.com/saving-satoshi/saving-satoshi/assets/52318459/de9f4f1f-ca32-4ef7-aec0-cba148f0f5f4)
![Screenshot (110)](https://github.com/saving-satoshi/saving-satoshi/assets/52318459/88ae6896-64bd-422f-98f7-6b1b91120053)

**Comment by shaavan** [comment]
You are right, @sabakhilji

That's why, for the chipped component, I imported the _cropped_ 25*25 version of the cat and used it instead of the full image.

**Comment by GBKS** [comment]
@sabakhilji I don't know if we will ever use this component again, as the other chapters have not been designed yet.

I also saw a note in the PR #530 about making the component more generic. Totally cool if the team wants to do that. I'd just be careful to not over-generalize things that we don't even know if we'll ever use them again. Personally I like to only make general-purpose what actually needs to be general-purpose, not on a speculative basis. Your call though.
