### ISSUE TITLE
ProfileComponent improvements

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#509]
@sabakhilji has made an initial draft for the `ProfileComponent` which will be used for Chapter 3 a lot.
 
We need to implement the following to make it ready for use:
1. Move from `components/utils/Profile.tsx` to `ui/Profile.tsx` since this component will be used for lessons only.
2. Use the new `Chip` component from https://github.com/saving-satoshi/saving-satoshi/issues/508 and make it overlap the Avatar. This should be optional.
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/ea2534ea-32f5-418e-8d53-36b2e76bdbf9)
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/6ed6ede8-df94-406b-9ecc-47a7281e7cfb)

**Comment by ecurrencyhodler** [comment]
@sabakhilji do you think you can work on this one since you also worked on the chip component?

**Comment by sabakhilji** [comment]
Yes sure!!

**Comment by ecurrencyhodler** [comment]
Closed with this [commit](https://github.com/saving-satoshi/saving-satoshi/commit/2036a08f8cb3d97d6a3546795a62aba2426464d4).

**Comment by afterburn** [comment]
Lets close this once #548 goes through
