### ISSUE TITLE
Improve Scripting Challenge UX

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#513]
1. It's not immediately clear when I press `Run script` that the system first needs to spin up a Docker container (system monitor tab), so there is a delay before stuff starts appearing in the "Hasher" tab.
2. We should communicate more clearly to the user that they only have to write the function body, not an actual script that performs a loop. This is because behind the scenes there is already a program written that calls the `findHash` function, so users just need to implement the function. (full code below video)
3. If there are errors we should automatically jump to the Console tab (which logs the errors).

Video reference:

https://github.com/saving-satoshi/saving-satoshi/assets/10757768/0f53ae42-aef1-46cb-a950-7536f0d60f03

```js
/* USER CODE */
const crypto = require('crypto')

function findHash(nonce) {
  return crypto.createHash('sha256').update(nonce.toString()).digest('hex')
}

/* INVISIBLE SYSTEM CODE */
const timeLimit = 3000;
const difficulty = 5;
let hashFound = false;
let nonce = 0;
let previousHash = ''
let previousHashMatchCount = 0

async function _runScript() {
  let hash = findHash(nonce)
  if (typeof hash !== 'string') {
    console.log('Error: findHash does not return a string')
    return console.log('KILL')
  }

  if (hash.length !== 64) {
    console.log('Error: findHash should return a string of 64 characters')
    return console.log('KILL')
  }

  function forceSolution() {
    hash = findHash(nonce + 1);
    hash = new Array(difficulty + 1).join("0") + hash.slice(0, hash.length - difficulty);
    console.log(hash);
    hashFound = true
  }

  setTimeout(() => {
    if (!hashFound) {
      forceSolution()
    }
  }, timeLimit)

  while (!hashFound) {
    hash = findHash(nonce);

    if (hash === previousHash) {
      previousHashMatchCount += 1
      if (previousHashMatchCount === 3) {
        console.log('Error: Your script keeps generating the same hash, make sure you use the nonce')
        break
      }
    }

    console.log(hash);
    previousHash = hash
    nonce++;
    await _sleep(50);
  }

  console.log('KILL')
}

function _sleep(t) {
  return new Promise((resolve) => {
    const timeout = setTimeout(() => {
      resolve();
      clearTimeout(timeout);
    }, t);
  });
}

_runScript();
```

**Comment by afterburn** [comment]
I have had multiple people mention that it doesn't work, what they try to do is implement a loop that calls `findHash` themselves, which is not going to work because the invisible progam that we have already does the looping for you.

We can solve this in two ways:
1. Make the instructions/ux more  clear that users only have to implement the function body for `findHash`.
2. Have users write a full program, so they will have to implement the loop and nonce generation themselves.

**Comment by ecurrencyhodler** [comment]
Let's have the challenge be focused on the player writing the whole formula.

**Comment by afterburn** [comment]
**From our call on June 13, 2023:**
Instead of asking users to implement just the findHash function, instead users will have to write a full program.

This has a couple of benefits:
1. The confusion that I have described in previous comments in this thread will no longer happen.
2. Since there is no longer a invisible program in which the users code is embedded line numbers in errors will now map to the users script correctly.

As well as some negatives:
1. The `Hasher` tab no longer makes sense, since the user might choose to not print out/log their hashes to stdout, which means our frontend wont know what to render:

![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/5e516711-130c-4e4b-9621-c538eb584c6e)

2. We are no longer able to force a solution after a certain time has passed.

@ecurrencyhodler @adamjonas @GBKS

**Comment by ecurrencyhodler** [comment]
Do you have code I can copy paste to see the experience in your PR? I assume it's changed since we are now writing the whole formula. Can be either for JS or Python.

**Comment by benalleng** [comment]
Late to the discussion as i wasn't in the call but did we rule out some form of incremental difficulty? first scripting challenge in the current case simply asking to make a `findHash()` function and the second getting them to repeat it?
At the moment the scripting lesson is only one challenge

**Comment by ecurrencyhodler** [comment]
We haven't discussed that as an option yet! But maybe it'll help if we give some context as to why we ended up at this decision. 

Jonas went through the challenge and felt frustrated because he actually wrote out the full formula but failed the challenge. Kevin also showed the game to several friends and he said they all ran into the same issue. 

That's when we realized that a majority of people going through the challenge was writing their own loop. So we went with this route for now.

**Comment by ecurrencyhodler** [comment]
@GBKS the skip button kevin brought up was if the script doesn't find a hash quickly. 

Right now we are forcing the UI to show that a hash has been found. But now with real code, finding a hash is variable. Kevin is suggesting we provide a skip button after x amount of time in case it takes too long to find a hash.

But @afterburn what would be the difference between displaying a skip button and forcing the UI to show that a hash was found like we currently have?

**Comment by GBKS** [comment]
What's the average time (or attempts) it takes to find a hash, and how often does this function run per second? I am just testing on the live site, and the hasher does not seem to work properly. When I enter my code and press run, I see one has after a little bit. It does not continue checking different nonces. After pressing the pause button again twice (button does not change state), it checks a few more nonces (maybe 10) and then stops again. So there are some interaction details to tweak here (IMHO) before figuring out if we need a skip option:

- Can the hasher just continuously run without needing press the pause button?
- The pause button should pause things and change to `Run the script` again when pressed
- Can we show the actual nonce used in `Running: findHash(nonce)` in the Hasher tab?
- Can we remove the `System monitor` tab? Not really relevant to the user what is happening on the server. If there is a boot-up time, we could just show something in the `Hasher` tab.
- I don't understand what is show in the `console` tab. Looks like hashes maybe? Can we make this a bit more descriptive?
- I can land on the page and press `Run the script` without having touched the code. Let's prevent that and disable the button

I got the success message with this result. Is that what you mean by the challenge timing out after a while and showing the success status not matter what?

<img width="481" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/35677bc8-6ba8-495a-97af-c2a3cf699bdc">

And now some proposals for all my complaining.

Initial state with hopefully clearer copy. Note that there are not Hasher/Console/System tabs, I tried to integrate those into the main output box.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/770e9f2e-bcd5-4070-ba1d-1c696c713bc1)

System starting up.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/dba5779b-3a9d-4b88-9849-0184a68effb7)

Failure on first run of the `findHash` function. Not that `Running` now shows which nonce is being used. From my testing, the console errors were pretty short, so maybe we can just display them here directly and don't need a dedicated tab?

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/1f48f3cb-48de-42d3-891a-c848f583de63)

Finally I wrote the correct code and the hasher cycles through nonces. Note how the number of leading zeroes is highlighted.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/339a7196-b348-4e9d-aec4-d5fbd4e896d8)

5 leading zeroes! I did it! Slay!

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/fdf8bd8e-50b1-484a-8844-bd85fefe47de)

Let me know what you think. Would that be a better experience and address issues we discussed? Is it technically feasible?

**Comment by afterburn** [comment]
Thanks @GBKS for your feedback.

## Some context
I think there are currently 2 different approaches for how we could set up this challenge.
1. The user just implements the findHash function (like you have done in your screenshots).
2. The user writes a full program that will generated nonces in a loop and creates sha256 hashes from those nonces.

As per my comment [here](https://github.com/saving-satoshi/saving-satoshi/issues/513#issuecomment-1591387614) we found that most users prefer 2.

By letting users write the full program we can no longer be sure that users print out the hashes. Before, this is what our invisible program was doing behind the scenes, but now that users have to write the program themselves, this is no longer guaranteed to be the case. Which means that we _cannot_ show the individual hashes in whats current called the `Hasher` tab. This is why I think we need to abandon whats currently called the "Hasher" tab and show the "Console" instead, which just shows whatever is being printed by the program.

To illustrate, the experience that we had was:
1. User implements findHash script.
2. Invisible program executes findHash script in a loop.
3. Results from findHash are checked to see whether they are valid sha256 hashes starting with five zeroes.
   1. If the hash does not meet criteria, we print the hash along with an error.
   2. If the hash meets criteria, we print the hash along with a success message.

The experience that we have chosen instead goes like this:
1. User writes a program:
   1. The program should generate nonces in a loop.
   2. The program should convert those nonces into sha256 hashes
   3. The program should check whether the resulting hashes start with five zeroes.
   4. If the resulting hash matches criteria, the program should `<submit the answer>`.
5. User executes program.
6. We check to see if the result from the program is a sha256 hash starting with five zeroes.
   1. If the resulting hash does not meet criteria, we show an error.
   3. If the resulting hash meets criteria, we show a success message.

Its important to understand the difference, the former performs what I like to call 'runtime evaluation', whereas the latter on performs validation after the script has finished executing. I think the approach we've chosen means some of your feedback no longer applies but I'll try to answer your questions below anyway. More context can be found [here](https://github.com/saving-satoshi/saving-satoshi/pull/494#issuecomment-1588269702).

## Answering your questions

1. Can the hasher just continuously run without needing press the pause button?
Like I mentioned, the script executes and either succeeds or fails now, so IMO the pause button no longer makes sense. After pressing the run button, we should not show a pause button because we no longer have a way to influence the script thats being run.

2. The pause button should pause things and change to Run the script again when pressed.
We can't do that in our new approach (full program, instead of implement single script).

3. Can we show the actual nonce used in Running: findHash(nonce) in the Hasher tab?
No, since its not guaranteed that the users program logs the nonce (or hash). We could if we were to instruct to user "Hey please log the nonce and hash" but this in my opinion is asking for trouble.

4. Can we remove the System monitor tab?
We can, but we need to make sure users understand that we need to boot some stuff up before their script can be run. The "Starting up" suggest accomplishes that goal, so yes.

5. I don't understand what is show in the console tab.
Since its no longer guaranteed that the users program prints hashes instead of showing the Hasher tab we should show the Console tab. This would show anything the user prints out. I can speak from experience that a lot of developers use `console.log` or `print` to develop their programs. Its an essential thing to have, otherwise its like having to write a program on paper without any feedback, its very hard to do.

6. I can land on the page and press Run the script without having touched the code. Let's prevent that and disable the button.
Agreed.


## My feedback on your updated design
1. Lets remove the `Running: findHash`, we dont know what the users program looks like, there is no way to detect what they'll name their hashing function if they even choose to make this a separate function in the first place. This is what my script looked like for example:

```python
# Python
from hashlib import sha256

nonce = 0
found = False

while not found:
    hash = sha256(str(nonce).encode('utf-8')).hexdigest()
    print(hash)

    if hash.startswith('000'):
        found = True
    
    nonce += 1
```
2. I feel we should remove the placeholder code, I think we just show a comment saying "Write a program that prints out a sha256 hash starting with five zeroes", then its up to the user to come up with an approach for achieving this goal.
3. We cannot show what nonce is being used, and we cannot show what hash is currently being evaluated. So lets remove these from the Hasher/console/system monitor thing.

**Comment by GBKS** [comment]
OK, thanks for the thorough explainer. So it sounds like what's live on the site right now is basically broken then?

Not sure I like this new direction very much. Feels like a simple text update could have made the instructions more clear instead of redoing the whole exercise with the update resulting in a much less responsive experience. In the code example you provided, there is no point where it actually returns a value. Does it just check the last print statement? Is this clear to coders? It's cool if we want to change directions, but we have to make sure this new direction is more intuitive than what we started with. I am not convinced of that right now. It may also be helpful to look forward at future scripting challenges, like chapter 4. If we establish a UX pattern we establish here, users may expect it again later (and we may want to keep it consistent to keep the amount of work lower).

And regarding the last point about how long it generally takes, that's just a matter of running it a few times on a few devices and seeing how long it takes. We just need a rough estimate to be able to make a call. We can then just wait until 2-3 times the average time has elapsed and then show a message that there might be a way for the author to optimize their code. I don't see simply showing a success message despite not having found a correct solutions as a valid design decision here.

**Comment by afterburn** [comment]
> So it sounds like what's live on the site right now is basically broken then?

Last time I checked it worked, but something might have broken on the backend in the meantime. I will check today.

> Feels like a simple text update could have made the instructions more clear

I agree, its what I suggested during our call and in [this comment](https://github.com/saving-satoshi/saving-satoshi/issues/513#issuecomment-1589171916).

> In the code example you provided, there is no point where it actually returns a value.

You are right, nowhere in my code do I currently `<submit the answer>` explicitly, right now the frontend is set up in a way where anything printed to the console is evaluated as an answer. This is how we have been evaluating the hashes in the previous approach.

I feel we either need to make it clear to the user that printing the hash is how they are being evaluated, provide a way to do this (e.g. by providing a `submitAnswer(correctHash)` function on the global scope) or prefill the code with a function like in the previous approach and make it clear that the return value of that function is whats being evaluated. 

> I am not convinced of that right now.

Neither am I, I actually prefer the other approach, but we've seen multiple people started to implement a full program as opposed to just implementing the `findHash` function. That's why the decision was made. This could maybe have been prevented by improving the UX (which is why I made this issue originally), but everyone seemed to lean to the full program approach. And to be fair, most "learn coding" platforms also seem to take this approach.

> And regarding the last point about how long it generally takes, that's just a matter of running it a few times on a few devices and seeing how long it takes. ... I don't see simply showing a success message despite not having found a correct solutions as a valid design decision here.

It really depends on the code that is being submitted. If I submit code that causes an infinite loop it will never finish executing. If I just print a string to the console it almost immediately stops executing. If I use a loop it depends on the difficulty, processing power of the machine and luck basically, [here](https://github.com/saving-satoshi/saving-satoshi/pull/522#issuecomment-1591512846) you can see that being the case.

I don't think anyone feels we should just show a success message despite not having found a correct solution, the hash should be a valid sha256 string and should start with five leading zeroes. Its actually a hard problem to detect whether the users code would produce a valid string and only then show the skip button after a certain time has passed by.

I think we can either:
1. Show the skip button after a certain time has passed while executing codem even though code might be wrong, or:
2. Show the skip button after x amount of wrong tries.

Not sure what the right answer is here.

**Comment by afterburn** [comment]
As discussed per our call on **20/06/2023**:

1. We will go forward with the "full program" approach.
2. Validation will happen via console.log/print.
3. Users are able to console.log/print multiple times throughout their program but the first message will be evaluated, if this is not a valid sha256 string starting with five leading zeroes, the challenge will fail (but the output will still be visible to the user).
4. We will increase the `MAX_SCRIPT_EXECUTION_TIME` to 15 seconds.

**Comment by Ulemu96** [comment]
Was this sorted?
