### ISSUE TITLE
regression on genesis challenge

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#52]
On https://savingsatoshi.com/chapters/chapter-1/genesis, I am no longer able to paste the ScriptSig hex for block0.

**Comment by aureleoules** [comment]
It works for me :thinking:

**Comment by aureleoules** [comment]
What OS / Window Manager / Browser are you using?

**Comment by aureleoules** [comment]
I think this can be closed since @adamjonas said he got it working again in our last call.
