### ISSUE TITLE
Ch.2 Title text overflow

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#524]
Looks like the title text "hashing out a plan" overflows out of the box on mobile. 
![image](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/ba1e249f-82bd-46f2-8f62-993d7e605f6b)

**Comment by ecurrencyhodler** [comment]
Is the solution here to change the font? @GBKS

**Comment by benalleng** [comment]
I think a simpler solution would be to add some dynamic text size on mobile, just making it a little smaller should do the trick

**Comment by GBKS** [comment]
Making the text smaller only works if the user has not chosen to increase the font size on their device via accessibility settings, or in their browser tab (small `aA` button in the bottom left on iOS Safari). A more flexible solution is to restrict it to one line of text using [text-overflow: ellipsis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow).

**Comment by benalleng** [comment]
Unfortunately It looks like our solution doesn't work site-wide. lets re-open
