### ISSUE TITLE
Occasional flickering in the UI

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#526]
Saba noticed after finishing a challenge, every time while moving on to the next challenge screen flickers. Also, there is no flicker while moving backward.

https://github.com/saving-satoshi/saving-satoshi/assets/52318459/602de2bc-7f4d-4897-967c-81c4eda511f7

_Originally posted by @sabakhilji in https://github.com/saving-satoshi/saving-satoshi/issues/495#issuecomment-1582722327_

ecurrencyhodler also noticed some flickering on the lock [here](https://github.com/saving-satoshi/saving-satoshi/pull/469#issuecomment-1561707009).

Lastly here is Christoph's comment in slack:

When I click to navigate to the next page, the current page briefly resets to its initial state before taking me to the new page. So if I’m in a challenge where I entered some text, it disappears. Images also flicker very briefly. Can anyone reproduce this? What could be causing this?

**Comment by GBKS** [comment]
Just left a comment with some thoughts [here](https://github.com/saving-satoshi/saving-satoshi/pull/519#issuecomment-1596531638).

**Comment by ecurrencyhodler** [comment]
This should've been addressed by #519. Closing this issue.
