### ISSUE TITLE
Fix Navbar design for challenges on mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#543]
In #538, we fixed the navbar to have ellipses for the chapter outro in mobile. But we need some guidance on how to handle the navbar for challenges. @GBKS do you have any suggestions on how we can handle the overflowing text in challenges-navbar?

### on dev.savingsatoshi
 ![image](https://user-images.githubusercontent.com/108441023/250120213-e233932d-f51e-4161-ac37-6c789c82a559.png) 

_Originally posted by @vinayaksh42 in https://github.com/saving-satoshi/saving-satoshi/issues/538#issuecomment-1614844831_

**Comment by ecurrencyhodler** [comment]
Let's get design requirements before addressing this one. We should also focus on issues related to components first.

**Comment by GBKS** [comment]
Same approach, I'd say. Limit each row to one line and use "...".
