### ISSUE TITLE
Improve answer evaluation for CH.2 Scripting 2

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#547]
From our call on July 11, 2023, in `CH2SCR2` we're checking whether user output is 64 chars long and starts with five zeroes, instead we should be validating whether the _nonce_ would generate a valid sha256 hash.

1. Figure out how to best solve this problem.
2. Implement the solution.

**Comment by ecurrencyhodler** [comment]
During a user interview, a bitcoin expert recommended that we have the print pre-image specifically and then verify the five 0’s after.
