### ISSUE TITLE
Improve ContributionBar 

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#557]
After we merge #542 we should spend some time to improve the contribution bar a little:
1. Improve animations - right now, the updates seem kind of choppy.
2. Improve avatar positioning - Avatars seem to be cut off at times, we can solve this by moving them to a different place in the markup hierarchy.

**Comment by GBKS** [comment]
I'd also recommend changing how bar sizing is implemented. Using scale and then the inverse scale for the avatar image is a bit funky.
