### ISSUE TITLE
Improve ScriptingChallenge terminal colors

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#558]
![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/f4f179d8-711d-4ed3-a84f-14ac51a747a2)

Some of the colors used for the node.js terminal are difficult to read. We can either:
1. Force text to always be white.
2. Replace ansi escape code color codes to ones that better fit the saving satoshi design.

Please leave your thoughts @GBKS 

Edit: Python terminal for reference:

![image](https://github.com/saving-satoshi/saving-satoshi/assets/10757768/681eff5d-148c-42ee-9fd9-bf2005de09db)

**Comment by ecurrencyhodler** [comment]
@GBKS pinging you on this design issue Christoph! Can you take a look?

**Comment by GBKS** [comment]
Could the text be white with 75% opacity? That would dim it a bit, but still be legible.

**Comment by ecurrencyhodler** [comment]
Okay let's try that. Thanks christoph.
