### ISSUE TITLE
Size of UI for text changes dynamically

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#568]
It looks like the sizing of the design changes when the text gets displayed which feels a bit jarring. Also the screen with the extra text doesn't fit within the standard window. The design fix here I think is that the width of the text box should wider. 

This is true for solo-1 and pool-1. I don't think we have challenge 3 yet.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/fc95e0b2-a1d0-4464-a953-82b810cbaa5a

_Originally posted by @ecurrencyhodler in https://github.com/saving-satoshi/saving-satoshi/issues/542#issuecomment-1638817642_

**Comment by ecurrencyhodler** [comment]
Christoph I wanted to get your feedback on this issue before we decide to add this issue as something to be fixed. 

To me, it's a bit jarring when the UI of the text box changes position when extra text is displayed but wanted to get your thoughts on if this is the intended.

**Comment by GBKS** [comment]
The solution is to implement things as designed (sorry, stupid comment, I know).

- In the design, the boxes are horizontally arranged, not vertically (fix the issue where stuff moves up/down)
- In the implementation, the content is vertically centered, it should be top-aligned (with top padding of course). This is optional, it also works as is (with the other fixes here, and a small tweak for varying text widths based on amount)
- Text should be centered
- Body text should be semi-bold and not bold

As for the jarring part, we just need to use the same text fade out/in transition as we used in previous chapters.

**Comment by benalleng** [comment]
I think this may have been solved in my current PR, I made some adjustments to the padding to allow for some text variance at the bottom as well as including the fade-in

**Comment by ecurrencyhodler** [comment]
Closed by #566.
