### ISSUE TITLE
Add ability to define hidden programs again

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#573]
For chapter 4 we'll need the ability to add hidden programs again. These hidden programs enable two things:
1. They allow engineers to predefine a set of functions/libraries that users can use to complete their challenges.
2. They allow engineers to define an evaluation program that calls into user code to determine whether the user passes the challenge.

**Comment by benalleng** [comment]
Doing a slight bit of probing I tried changing an option `wordWrap: 'off'` and then on the specific line where I add the relevant code create some css to hide it 
```
.view-line:nth-child(2) {
  visibility: hidden;
}
```

Wonder if you think there is a better way to avoid having to turn off wordWrap

**Comment by benalleng** [comment]
Closed by #692
