### ISSUE TITLE
Create guide page for scripting challenges

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#576]
To ensure that the user has a clear understanding of how to proceed with coding challenges we should add a page or modal that clearly defines how the user should proceed on all challenges of this type.

### Possible options
- page before 1st coding challenge
- modal with explaining tips
- gif showing what the user should do
- a combination of these approaches

**Comment by afterburn** [comment]
Created a separate issue for the last part #577

**Comment by ecurrencyhodler** [comment]
@benalleng do you think this is still needed if the user is unable to delete the code? I feel as if we won't need it anymore.

**Comment by benalleng** [comment]
I don't think so, if it turns out we can prevent code deletion we can close this issue

**Comment by afterburn** [comment]
Plugin works, see https://github.com/saving-satoshi/saving-satoshi/pull/578
