### ISSUE TITLE
Fix: Chapter 3 Challenge order

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#580]
https://dev.savingsatoshi.com/en/chapters/chapter-3/intro-1?dev=true

The sequence of challenges in chapter 3 is unorganized. This issue can be either dealt with right now and then the upcoming PRs for new challenges will maintain the sequence or we can organize the challenges once all the PR's for chapter 3 challenges have been merged.

**Comment by benalleng** [comment]
This was closed by #571
