### ISSUE TITLE
Chapter 3 Challenge 2 [Co-op vs BitRey loose] styling related feedback (Christoph)

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#587]
- not use a fixed width at smaller sizes, but a max-width. That allows the boxes to shrink a little further if needed, like for iPhone SE. (for the waiting screen avatar boxes). 
- centering the copy on mobile
- the “Waiting…” text would slightly fade in and out to indicate that there’s activity. And then if the images faded in nicely.

**Comment by 0tuedon** [comment]
Hey @vinayaksh42  for the second issue i don't know what copy should me center aligned here (LGTM)
screenshot below
<img width="777" alt="Screenshot 2023-08-19 at 22 48 36" src="https://github.com/saving-satoshi/saving-satoshi/assets/90271995/58d58ebd-09f3-4b2e-a584-990ad258d54b">

**Comment by benalleng** [comment]
I believe the issue there is mobile, I'm not sure though as it does seem inline with other pages.

![Screenshot_20230819-190017.png](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/226a8bd6-0290-41a3-8cba-231668c5bbbb)

**Comment by ecurrencyhodler** [comment]
Closed by #613
