### ISSUE TITLE
Leave mouse as default cursor on tooltips.

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#589]
When someone hovers over a tool tip, they may expect the tooltip to be a link because the mouse turns into a finger. Let's keep it as the default cursor (but still display the tooltip) when the mouse hovers over the underlined text.

**Comment by 0tuedon** [comment]
> Unless the tool tip is also a link, in which case the cursor change makes sense. Something else we discussed recently is having tool tip only text use a dashed underline, and only use a solid underline for links (whether those have tooltips or not).

@afterburn  are we changing the type of underline we are using as mentioned here?

**Comment by ecurrencyhodler** [comment]
Hey @0tuedon yes that would be great if you could include that in your PR.
