### ISSUE TITLE
Research SVG component for visualizing elliptic curves

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#593]
<img width="592" alt="Screenshot 2023-08-07 at 19 59 45" src="https://github.com/saving-satoshi/saving-satoshi/assets/10757768/c64581f4-b40a-40cb-8938-acd9771895f0">

Figure out the best way to render something akin to the above, ideally it should support animation.

**Comment by benalleng** [comment]
Making some progress!

[Kazam_screencast_00009.webm](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/244a5e7c-4fc7-4d77-a90e-2868acccaaf0)
