### ISSUE TITLE
Move "Need a hint?" prompt in Ch. 2 to hash generation section in hashing challenges

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#612]
I conducted 3 user interviews. All 3 users said their eyes were looking at the output of the hashing challenges instead of the input section.

We should move the "need a hint?" prompt that appears to the output section of the hashing challenges.

<img width="1054" alt="hint" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/c7679808-d1e2-4378-ba2a-e1f16867e01b">

**Comment by sabakhilji** [comment]
Hey @ecurrencyhodler is this issue open?

**Comment by ecurrencyhodler** [comment]
Hello Saba! Good to hear from you. :)

Yes it is! Would you like to take it?

**Comment by sabakhilji** [comment]
yes

**Comment by benalleng** [comment]
Closed by #641
