### ISSUE TITLE
Can't go past Ch.3 Intro-1

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#617]
I can no longer go past Ch.3 intro-1 through this url: https://dev.savingsatoshi.com/en/chapters/chapter-3/intro-1?dev=true

Could this be a feature flag issue? @afterburn 

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/0269bd91-d755-44ee-8cbe-4d3832d54d41

**Comment by 0tuedon** [comment]
Are there chances that you may need to complete other chapters first on the staging? @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Hmmm historically `?dev=true` allowed people to bypass any progress locks. Are you able to go past Ch.3 intro-1?

**Comment by 0tuedon** [comment]
nope,  i get stuck on this screen
<img width="1680" alt="Screenshot 2023-08-31 at 20 50 51" src="https://github.com/saving-satoshi/saving-satoshi/assets/90271995/b706df83-4964-4484-a8d9-7578645b551f">

although i did try build it locally and it went through could that be because i have completed all chapters

**Comment by ecurrencyhodler** [comment]
I tried after completing ch.2 and still got stuck. :-/ I think iBen's guess of this being a feature flag issue is the most likely culprit.

**Comment by ecurrencyhodler** [comment]
<img width="1305" alt="Screenshot 2023-09-01 at 12 38 56 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/eba41084-7ecb-4bbd-ba5b-367f934c9232">
Logs I got from the console.

**Comment by afterburn** [comment]
Fixed in 0ad14c39335da83bba2a88915cd7ffe8d8aa477f
