### ISSUE TITLE
Size of images should focus on top when window is smaller.

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#618]
When I make the width of the screen smaller, the website focuses on the bottom of the image. IMO it makes more sense for it to focus on the top. But I'd like @GBKS to take a look and provide some guidance on how to handle situations like this.

This is for the chrome browser on mac.

<img width="674" alt="Screenshot 2023-09-03 at 12 29 51 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/ee1d3849-c8ca-49eb-a17b-38d2ebcaa21d">

Dimensions were :1300 x 672

This issue is not a blocker for release.

**Comment by GBKS** [comment]
Good one. We briefly discussed this a while ago. The solution here is to have a custom [object-position](https://css-tricks.com/almanac/properties/o/object-position/) CSS property for this page template (and maybe other templates, too). When an image is cropped, this property defines how to position the image inside its boundaries. You essentially define where the primary point of interest of the image is. Considering we sometimes use different images for desktop and mobile, we may need 2 properties for this also.

**Comment by benalleng** [comment]
Already implemented! just needs to be used here!
