### ISSUE TITLE
Find solution for adding tool tips to text

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#62]
See the tooltip in the following design:
![image](https://user-images.githubusercontent.com/695901/211272321-c0ff3181-9051-41c8-8e63-66ad99b12f25.png)

We have a tooltip component already, but how can we apply it to text that is defined in markdown ([text from image above](https://github.com/saving-satoshi/saving-satoshi/blob/master/content/lessons/genesis-pt2.mdx))? From my research, markdown doesn't support this type of rich markup. Do we need to get away from using markdown altogether?

This tooltip should be used in all texts that contain technical terms. We don't want users stuck and opening up new tabs just to Google terms and end up discouraged. Ideally we can answer any open questions in these tiny tooltips.

**Comment by aureleoules** [comment]
Related #79 #80.

**Comment by afterburn** [comment]
With the new architecture adding tooltips has now become possible. There is still an unresolved issue wrt translations that I outline in #121 but you can currently see it working in [this PR](https://github.com/saving-satoshi/saving-satoshi/pull/122).

**Comment by afterburn** [comment]
We currently have 2 `Tooltip` components that we still need to merge into a single component, so lets leave this issue open for now (unless you want to create a new issue for it @ecurrencyhodler?). I'll pick that up tomorrow.

**Comment by ecurrencyhodler** [comment]
Sounds great!

**Comment by GBKS** [comment]
Yes, this architecture is great. The 2 tool tips can be merged in a separate PR.
