### ISSUE TITLE
Text box in success status is too large for chapter-3/pool-3

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#621]
Once the mining challenge is complete for chapter-3/pool-3, the success text box and button is expanded making it too large. This is for the chrome browser on mac.
<img width="1302" alt="Screenshot 2023-09-03 at 12 45 26 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/b397947c-7a6b-465a-b483-32874e4ffdd2">

When we look at the previous challenge, we see that the "continue" button still has space at the bottom. This might be a text font issue. If not, I recommend making the text box limits wider.
<img width="1480" alt="Screenshot 2023-09-03 at 12 47 02 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/7ee95426-b0ce-4555-8b3a-3dfa25a0c24c">

**Comment by ecurrencyhodler** [comment]
chapter-3/split-2 is also affected by this. The "tell me more" button is too low. There should be space between that and the bottom of the page. I can also scroll down despite having an almost fully expanded width.
<img width="1481" alt="Screenshot 2023-09-03 at 12 53 01 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/fcc32f42-73b6-4dce-9361-2b50b26632b9">

**Comment by ecurrencyhodler** [comment]
The whole section in chapter-3/split-2 is affected by this issue. This is the screen I see after I tap on "tell me more".
<img width="1479" alt="Screenshot 2023-09-03 at 12 54 39 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/9e8f8604-910b-430c-8590-dab6e2a8a50e">

**Comment by ecurrencyhodler** [comment]
In firefox, the sizing is better, almost perfect. It still has room to scroll down though once the success state is triggered.
<img width="1379" alt="Screenshot 2023-09-03 at 1 40 48 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/39c4e799-f34f-4eed-ab44-edda5011283b">
<img width="1371" alt="Screenshot 2023-09-03 at 1 41 34 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/2e934d1a-9a35-4ecf-8787-847a574152e6">

**Comment by benalleng** [comment]
I think a stray top-padding got introduced
![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/10f9587d-535f-4196-ae0b-d68acbc28f9f)
