### ISSUE TITLE
chapter-3/split-1 lay out is not well-sized

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#622]
chapter-3/split-1 lay out is not well-sized. As you can see in the video, I can scroll down after landing on the page. This section should be fit such that there is no scroll button unless the width is minimized. 

This is for the chrome browser on mac.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/b9eb31e4-7401-4c49-a9a5-7e36fc67873e

**Comment by ecurrencyhodler** [comment]
This isn't an issue in firefox/mac.

**Comment by 0tuedon** [comment]
> chapter-3/split-1 lay out is not well-sized. As you can see in the video, I can scroll down after landing on the page. This section should be fit such that there is no scroll button unless the width is minimized.
> 
> This is for the chrome browser on mac.
> 
>  outro.mov

Hey @ecurrencyhodler, Thanks for spotting the issue, but i am finding it hard to replicate this issue on my device both on chrome and firefox, except i significantly reduce my screen size. @benalleng  could you check this out on your end also?

**Comment by benalleng** [comment]
Me either, I have to make my screen substantially shorter/thinner. what is the maximum screen size that you have @ecurrencyhodler? I did notice the heading at the top is not the correct size though [Figma]()

**Comment by ecurrencyhodler** [comment]
Width I have is 2312x281 on chrome at 100% zoom.

**Comment by benalleng** [comment]
can you confirm 2312x281 ?

**Comment by ecurrencyhodler** [comment]
Now it's saying 2142x281. Is this the right way to determine max size?
<img width="1107" alt="Screenshot 2023-09-19 at 11 50 10 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/030afdf5-f10e-4c39-90e0-c2b9bc4a8330">

**Comment by benalleng** [comment]
oh ok sorry, was just suprised by the height you gave me, what is your max height?

**Comment by ecurrencyhodler** [comment]
Okay I dunno if I'm doing this right but now I have 1472x740. If this is just a "me" issue, then I think we can just close this issue.

https://github.com/saving-satoshi/saving-satoshi/assets/32662508/b941d584-eda6-435e-951a-2205d844eb47

**Comment by 0tuedon** [comment]
@ecurrencyhodler, did you mean this on the call? i thought you meant #660

**Comment by ecurrencyhodler** [comment]
Since this can't easily be reproduced, I'm going to close this issue.
