### ISSUE TITLE
Implement CH4 Challenge 1 - Elliptic curve cryptography

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#625]
Use the `ScriptingChallenge` component  to implement chapter 4 challenge 1. For our lesson IDs we can use `CH4EC1` and `CH4EC2`.

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=1535-19614&mode=design&t=bUUrHbu3heWV0c7c-0)

Is currently blocked by #624 and #593

**Comment by 0tuedon** [comment]
@afterburn  is this still blocked by #624  and #593 ??

**Comment by benalleng** [comment]
#593 is really just an intro page, and #624 should be ready to be implemented; it is still open only because we haven't tested it in an actual way yet. This issue should be ready for dev!

**Comment by benalleng** [comment]
From the call I think that the mvp for this issue should also include creating the placeholder for the suceeding lesson, as this person would be most familiar with how they have saved the data on their primary work. @afterburn let me know if you disagree on this
