### ISSUE TITLE
Implement CH4 Challenge 2 - Address generation

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#626]
Use the `ScriptingChallenge` component to implement chapter 4 challenge 2. For our lesson IDs we can use `CH4AD1` and `CH4AD2`.

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=1535-19614&mode=design&t=bUUrHbu3heWV0c7c-0)

Is currently blocked by https://github.com/saving-satoshi/saving-satoshi/issues/624

**Comment by sabakhilji** [comment]
Can I work on this issue?

**Comment by benalleng** [comment]
ATM blocked by #701 due to need for saveData => getData
