### ISSUE TITLE
Implement CH4 Outro

### ISSUE THREAD

**Issue by afterburn** [saving-satoshi/saving-satoshi#628]
Pretty straightforward, we should create outro pages for Chapter 4

[Link to Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=1535-19614&mode=design&t=bUUrHbu3heWV0c7c-0)

**Comment by benalleng** [comment]
Closed by #667
