### ISSUE TITLE
Fix layout issues on the chapters page

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#63]
There's a handful of pretty minor layout issues on the chapters page ([Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=975%3A12149&t=nxCE26gS2fD24CVh-1)). See them in the image below.

![image](https://user-images.githubusercontent.com/695901/211272860-e92e0633-a57b-4a72-baa3-2d04715d8fd9.png)

**Comment by vinayaksh42** [comment]
@GBKS I have created a pull request for this issue.

**Comment by vinayaksh42** [comment]
> Thanks @vinayaksh42, just merged it in.
> 
> Small note that the issue about the image resizing when tabbing (and the content height changes) is still outstanding, I've created issue #83 for it.

Thanks for the information
