### ISSUE TITLE
Remove horizontal scroll bar in chapter 3 mining challenges

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#633]
It is not important to show a scroll bar here at all. Horizontal scrolling is a really common interaction people are familiar with. As far as communicating to users that the area is scrollable, the standard is simply that some items are cut off and go beyond the screen edge.

<img width="911" alt="image" src="https://github.com/saving-satoshi/saving-satoshi/assets/695901/1d95ddbf-8e6d-48c2-900e-ceb1e3c58d10">

Also the content on the right should go all the way to the edge and not be cut off 15px from the browser edge.

If there's insistence that we need a scrollbar, I can come up with a much more subtle one that this big white block.

**Comment by ecurrencyhodler** [comment]
Hi Christoph. 

I was the one who suggested adding the scrollbar back into the challenge. The issue I ran into was when the width of the screen nicely landed and cut off BitRey as a hasher. So it wasn't immediately obvious or clear that I had to scroll horizontally to see BitRey. Here's my comment and screenshot:
https://github.com/saving-satoshi/saving-satoshi/pull/604#issuecomment-1686657637

WDYT? Should we still remove the scroll? Or should we add something different?

**Comment by GBKS** [comment]
Here are two options (in addition to having the option of having nothing), both are pretty common. The first one is a scrollbar, but way more subtle (it can become brighter on hover). The second one is an arrow indicator on the right edge (so you can scroll via mouse or click that indicator and a similar indicator on the left appears once you have scrolled a bit).

![saving-satoshi-scroll-indicator-options-230906](https://github.com/saving-satoshi/saving-satoshi/assets/695901/cc62c81c-4dc5-4704-a85b-1dddabaf17b3)

**Comment by ecurrencyhodler** [comment]
I kinda like the first option with the subtler scroll bar.
