### ISSUE TITLE
Layout issues in CH 3 Challenge 4

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#635]
On the left, you can see the text budging directly against the percentage boxes, and text sticking outside of its container. On the right, the first avatar is much smaller than the others causing inconsistencies.

The second issue is probably caused by applying a fixed with to the labels ("Hashrate", "Blocks found"...). Not a good approach, it's much better to relay on [flex layout](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) to space things correctly.

The user boxes have a max-width of 220, which should be 300 per Figma. That will also help fit in all the content and prevent layout issues.

![Frame 1](https://github.com/saving-satoshi/saving-satoshi/assets/695901/e35ac1a6-8a71-46b9-b003-2f0852162386)

I also see a bunch of unnecessary Tailwind classes again. For example, a text paragraph with `flex` and `flex-col`. Those two properties define how child elements are laid out, but text paragraphs don't have any. Doesn't break anything, just confusing and makes it harder to work with the code.

[Dev site link](https://dev.savingsatoshi.com/en/chapters/chapter-3/split-2?dev=true).

**Comment by GBKS** [comment]
We should be OK because we only have 4 miners here, not 5.

**Comment by 0tuedon** [comment]
> We should be OK because we only have 4 miners here, not 5.

Yup, it does work that way.

**Comment by ecurrencyhodler** [comment]
Looks a lot better to me. WDYT @GBKS ? [Link to test](https://saving-satoshi-n697cc5gn-savingsatoshi.vercel.app/en/chapters/chapter-3/split-2?dev=true)

![Image](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/b9db8db7-ad5e-4d32-bd3e-26030194c7eb)



![Image](https://github.com/saving-satoshi/saving-satoshi/assets/32662508/e0f019b5-1083-4ff6-907a-b737edcec9e5)

**Comment by GBKS** [comment]
Yes, looks better. There is a layout jump that happens when pressing the first "Tell me more" on certain screen sizes. Looks like up to that point, the width setting is different than after. It would be great to fix it so the layout is consistent and this jump does not occur.
