### ISSUE TITLE
Add mobile layout to chapter 1 intro page

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#64]
**Screenshot:**

![image](https://user-images.githubusercontent.com/695901/211273297-2f108fa4-dae9-4058-9099-741f7176a904.png)

**Design ([Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=83%3A1818&t=nxCE26gS2fD24CVh-1)):**

![image](https://user-images.githubusercontent.com/695901/211273207-b591c1d4-f209-405a-931f-c15c7469ea30.png)

Also, the image should resize proportionally on desktop - it should not distort.

**Comment by vinayaksh42** [comment]
Hey, I would like to work on this issue
