### ISSUE TITLE
Specific page in Ch.3 Challenge 4 is not fit to screen. (iPhone/Firefox/Chrome)

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#640]
As I go through Ch.3 Challenge 4, the section right after the replay is not fit to screen. This is the section where we first click on "tell me more".

Below are two screens: The first "tell me more" and the second "tell me more".  As you can see the first "tell me more" is not visible for both browsers. However it is visible on the second "tell me more" screen.

It appears the cause of this is the focus of the page is in the middle rather than the top. 

I think for this specific section, it is good if we focus the page on the middle. But we should keep focus at the top of the page when someone is brand new to the page as described in https://github.com/saving-satoshi/saving-satoshi/issues/638.

**Chrome**
<img width="367" alt="Screenshot 2023-09-04 at 1 06 48 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/ceeb3cdd-900d-418b-a54c-45f321ca1f0c">

**Firefox**
<img width="352" alt="Screenshot 2023-09-04 at 1 06 12 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/32662508/2a262b6a-bc0c-4b59-bd25-5b19cf6126da">

[Preview](https://dev.savingsatoshi.com/en/chapters/chapter-3/split-2?dev=true)

**Comment by benalleng** [comment]
I may not completely understand this issue as compared to #638, Is the issue that the tell me more isn't visible if the user presses the start button without scrolling and then may not see the "tell me more button"?

**Comment by ecurrencyhodler** [comment]
#638 should have the focus at the top when someone is brand new to a page.

Here the first "tell me more", the focus is at the top which prevents that button from being seen. The second "tell me more" the focus is in the middle which allows the button to be seen.

I suggest that for this specific challenge, the focus be in the middle for the first "tell me more" like it is for the second "tell me more". Does that make sense?
