### ISSUE TITLE
Add .nvmrc file to repo

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#642]
A request from Christoph is to add a ".nvmrc" file to the repo. This allows the repo to auto-switch to an appropriate node version when installing dependencies.

**Comment by sabakhilji** [comment]
Can I have a look at it?

**Comment by benalleng** [comment]
a version that I know works is `16.20.0`, that is probably the version we should force in our `.nvmrc`

as well it might be nice to add engine specs to our package.json for new dependencies

``` json
// package.json    
"engines": {
    "node": ">=16.20.0",
    "yarn": ">=1.22.19"
}

```

**Comment by benalleng** [comment]
go for it @sabakhilji!

**Comment by sabakhilji** [comment]
Thanks @benalleng for the information. I want to ask one question here I am trying to include a setup script for nvm instead of directly installing it in the git repo. Is that fine? I will make a shell script file for that and update the readme file. Please LMK your thoughts about it.

**Comment by benalleng** [comment]
I think it would be easiest if you just add the .nvmrc file to the repo with a note in the README to run `nvm use` if you need to set your node version.  This is mostly just a fix incase people are having problems spinning up a dev environment
