### ISSUE TITLE
Improve interaction model of input area on Copy challenges

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#65]
The component currently uses the [react-individual-character-input-boxes](https://www.npmjs.com/package/react-individual-character-input-boxes) module. The expected behavior is that of a regular text box, so it feels a bit off when trying to do anything more than a simple paste. 

Let's try a simple text box approach that is styled to still show the underlines (maybe another hidden text area behind the input that intelligently shows the underscored for blank characters).

This affects the two copy challenge pages we have:
- [Genesis](https://savingsatoshi.com/chapters/chapter-1/genesis)
- [Transacting](https://savingsatoshi.com/chapters/chapter-1/transacting/transacting-1)

Screenshot:
![image](https://user-images.githubusercontent.com/695901/211274054-f74ddd74-bd36-4e44-b779-f4a8f3704436.png)

**Comment by adamjonas** [comment]
ref #97
