### ISSUE TITLE
Occasionally unable to go past Ch.3 intro-1

### ISSUE THREAD

**Issue by ecurrencyhodler** [saving-satoshi/saving-satoshi#651]
We are still running into the error whereby entering chapter 3 crashes the site in dev mode using the dev=true fragment.

I am able to append dev=true here: https://saving-satoshi-git-fork-benalleng-issue632-savingsatoshi.vercel.app/en/chapters?dev=true, which enables the chapter 3 button for me, when I press it it takes me to https://saving-satoshi-git-fork-benalleng-issue632-savingsatoshi.vercel.app/en/chapters/chapter-3/intro-1?dev=true without any issues. 

But when I press "continue" the website hangs. 

It's very inconsistent, I can't figure out why some branches are broken and why others aren't. dev.savingsatoshi.com sometimes works, sometimes doesn't

I could be wrong but I believe it is related to the deployments vs some code deployed on the app. It crashed the vercel bar at the bottom of the screen first, and no error in the code is ever presented on local deployments

**Comment by benalleng** [comment]
It does! I'll keep looking!

**Comment by afterburn** [comment]
@benalleng thanks, I updated my comment above with some new findings

**Comment by benalleng** [comment]
Closed by #644
