### ISSUE TITLE
Point new contributors to Bitcoin Design Discord instead of Slack on About page

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#672]
Current:

If you want to get involved with design, story, or anything else, join us in the #saving-satoshi channel in the [Bitcoin Design slack](https://bitcoin.design/contribute/). Mention how you’d like to contribute and we’ll help point you in the right direction.

Update:

If you want to get involved with design, story, or anything else, join us in the #saving-satoshi channel in the [Bitcoin Design Discord](https://discord.gg/K7aQ5PErht). Mention how you’d like to contribute and we’ll help point you in the right direction.

**Comment by benalleng** [comment]
Closed by #688
