### ISSUE TITLE
chapter 3 does not unlock after I've completed chapter 2

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#673]
I've reproduced this 3 times. On prod, if I finish chapter 2, I am returned to the index screen and chapter 3 is not unlocked.

<img width="1424" alt="Screenshot 2023-10-04 at 11 06 13 AM" src="https://github.com/saving-satoshi/saving-satoshi/assets/755825/6decfb5f-d339-4635-9323-863c1b86f5f8">

**Comment by benalleng** [comment]
@afterburn Is this a feature-flag issue?

**Comment by afterburn** [comment]
Fixed in #676
