### ISSUE TITLE
Chapter 4 locked despite Chapter 3 Completed

### ISSUE THREAD

**Issue by sunnybhoy** [saving-satoshi/saving-satoshi#686]
Can't proceed to Chapter 4 with message "Complete Chapter 3 to unlock". All challenges in Chapter 3 have been completed.

This behavior is on both my desktop with Microsoft Edge browser and Android 14 Chrome desktop. I've tried to sign out and back in again, as well as repeating chapter 3 on numerous occasions.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/33714292/45158600-3ae3-4bb5-bdbd-6c4aa2d192a4)

![image](https://github.com/saving-satoshi/saving-satoshi/assets/33714292/3fb55b26-ff84-4db7-881e-1a00dc0211e6)

**Comment by benalleng** [comment]
Unfortunately Chapter-4 is still locked, we have gotten the copy incorrect for this chapter, it should still say coming soon

**Comment by benalleng** [comment]
Feature-flag enabled
