### ISSUE TITLE
Instead of tool tips to explain concepts, link to holocat on chatbtc

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#698]
For example, https://chat.bitcoinsearch.xyz/?author=holocat&question=How%2520is%2520bitcoin%27s%252021%2520million%2520supply%2520cap%2520enforced%253F

**Comment by benalleng** [comment]
Going to assign this to @GBKS for now, I knwo you had previewed a quick demo of an old wireframe of this concept. wondering how you might want this to look?

**Comment by benalleng** [comment]
@adamjonas is there an api available? Or would you ideally want to direct them to the ChatBTC site?

**Comment by GBKS** [comment]
Here are two ideas. One is inline and works best for looking up things in the text. The other is below the text, better for additional questions, and more explicit (there could also be multiple of those pills below each other). We could decide on one, or use both in different places. What do you think?

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/c830c625-fcc4-4263-9905-6d285e14f520)

**Comment by adamjonas** [comment]
I personally like the one at the bottom but either works and is worth testing. 

@benalleng there is no API but the urls for specific questions can be shared which I think suffices the use case. E.g. https://chat.bitcoinsearch.xyz/?author=holocat&question=What%2520is%2520sha-256%253F

**Comment by 0tuedon** [comment]
Wondering if we also need to do for specific languages?

**Comment by benalleng** [comment]
I don't think the bitcoin search chat has support for different languages

**Comment by benalleng** [comment]
Making a list of places we should add these questions, feel free to add more
- [ ] `chapter-2/scripting-1`
What is the target difficulty?
https://chat.bitcoinsearch.xyz/?author=holocat&question=what%2520is%2520target%2520difficulty%253F

- [ ] `chapter-4/address-1`
discrete log problem
https://chat.bitcoinsearch.xyz/?author=holocat&question=how%2520is%2520the%2520discrete%2520log%2520problem%2520relevant%2520to%2520bitcoin%253F

- [ ] `chapter-5/derive-message-7`
We'll cover this more in the next chapter
Maybe something like: "(dont worry too much about that right now, we'll go into more detail into this soon)"
https://chat.bitcoinsearch.xyz/?author=holocat&question=what%2520are%2520sighash%2520flags%253F

- [ ] `chapter-2/hashing-3`
how is SHA-256 used in bitcoin?
https://chat.bitcoinsearch.xyz/?author=holocat&question=how%2520is%2520SHA-256%2520used%2520in%2520bitcoin%253F

**Comment by 0tuedon** [comment]
Thanks @benalleng.
