### ISSUE TITLE
Add umami analytics to Saving Satoshi

### ISSUE THREAD

**Issue by aassoiants** [saving-satoshi/saving-satoshi#699]
- [ ] [Main page](https://savingsatoshi.com/) overall analytics + listeners on each main CTA (Start + Tell me more)  + main nav buttons (Chapters & About)
- [ ] [Chapters page](https://savingsatoshi.com/en/chapters) overall analytics + listeners on each of the chapter "Start" buttons + main nav buttons (Chapters & About)

**Comment by daviroo** [comment]
Why specifically Umami @aassoiants?  Have you considered alternatives?

**Comment by benalleng** [comment]
Closed by #704
