### ISSUE TITLE
Chapter 5 Challenge-1 Part-2 (transaction parse)

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#713]
This page adds a new component that mimics the Editor page but instead uses an <Input /> to parse a transaction into different colors.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/ec9e341c-5e66-46a7-ad57-463cc0a42d5f)

[Figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=5381%3A5191&mode=dev)

**Comment by benalleng** [comment]
https://github.com/coinsurenz/LibreTX possible solution

**Comment by benalleng** [comment]
From the call 
- This particular transaction will be the same for everyone so perhaps the logic will not need to be so complex but in the future it would be nice to have the functionality of being able to parse all possible transactions

**Comment by daviroo** [comment]
> @pinheadmz Do you think it would be best to build a fully functional parser instead of a basic "color at string[Index]" css at this point? will we likely use something like this to split transactions in the future?

My suggestion would be to never optimise early - especially if it's a complicated piece of work.

**Comment by pinheadmz** [comment]
I dont think we will need a generic tx parser. However, in ch 6 we'll be creating our own transactions and it will be kind of the opposite of this, like fill in the blanks:

input 0 txid: _______
input 0 index: ______
input 0 sequence: _____
input 0 witness: ______

...etc

**Comment by pinheadmz** [comment]
> @pinheadmz Do you think it would be best to build a fully functional parser instead of a basic "color at string[Index]" css at this point? will we likely use something like this to split transactions in the future?

Plot twist: user will write the TX parser for the chapter 6 challenge ;-)

**Comment by daviroo** [comment]
Merged in #732
