### ISSUE TITLE
Typo in chapter 4 challenge

### ISSUE THREAD

**Issue by jeffreyweier** [saving-satoshi/saving-satoshi#737]
**Describe the bug**
There is a spelling error in chapter_four > address_one > paragraph_one: "We’lll learn about that in the next challenge."

**To Reproduce**

1. Complete the step in Challenge four where you create a compressed public key.
2. See error

**Expected behavior**
We'lll should be spelled We'll. "We’ll learn about that in the next challenge."

**Screenshots and/or logs**
If applicable, add screenshots and/or logs to help explain your problem.

![Saving Satoshi typo](https://github.com/saving-satoshi/saving-satoshi/assets/98287483/97c493e5-b48b-4a9a-9ff6-00af9ea92af7)

**Desktop (please complete the following information):**

- OS: Windows 11 Enterprise
- Browser: Brave
- Version: Version 1.60.110 Chromium: 119.0.6045.105

**Comment by daviroo** [comment]
Thanks for the report @jeffreyweier
