### ISSUE TITLE
Mining Challenge style bug

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#741]
10x and Runner buttons should be flex-wrap reverse on small screens

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/f7003add-836d-473b-9e2f-5fcdc56a9531)

**Comment by 0tuedon** [comment]
> 10x and Runner buttons should be flex-wrap reverse on small screens
> 
> ![image](https://private-user-images.githubusercontent.com/108441023/281091793-f7003add-836d-473b-9e2f-5fcdc56a9531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDE4NzAsIm5iZiI6MTcwMTMwMTU3MCwicGF0aCI6Ii8xMDg0NDEwMjMvMjgxMDkxNzkzLWY3MDAzYWRkLTgzNmQtNDczYi05ZTJmLTVmY2RjNTZhOTUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQyMzQ2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODAyY2RjMDI0NzhhZDdhZGNiMjFkOWZhMjMyOWU1NTgzMzQ4ODNhMjZlNTA4Y2Q3YjliOTczYjdlMWMwNjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6ff1erLFACZycW78mxbUKZY1eRBG0pye0ZY8cyPOm5Q)

finding it hard to reproduce this on local, is there a specific browser used on mobile

**Comment by 0tuedon** [comment]
> 10x and Runner buttons should be flex-wrap reverse on small screens
> 
> ![image](https://private-user-images.githubusercontent.com/108441023/281091793-f7003add-836d-473b-9e2f-5fcdc56a9531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDA0ODksIm5iZiI6MTcwMTM0MDE4OSwicGF0aCI6Ii8xMDg0NDEwMjMvMjgxMDkxNzkzLWY3MDAzYWRkLTgzNmQtNDczYi05ZTJmLTVmY2RjNTZhOTUzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxMDI5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDgwOWRiYjZlYmNlOWFiYjIyNTFiYzVmMTk5NTA0MWI1M2QyZGZkNjY5NjU5YmVjMTdjOTBjMDgyNGYzMDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wtb8f9ZxWlod6Dk2tkDq8o5gyKTXu8mR6ZeRqbBXdwY)

could you recheck on thr dev branch?

**Comment by benalleng** [comment]
sorry, Here is what I see currently on dev
![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/695966c2-2a84-44e3-8b34-11717a4b8e95)

I'd like the buttons to use `flex-wrap reverse` so that they can be stacked on small screens

**Comment by 0tuedon** [comment]
> sorry, Here is what I see currently on dev ![image](https://private-user-images.githubusercontent.com/108441023/287062234-695966c2-2a84-44e3-8b34-11717a4b8e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjI1NDcsIm5iZiI6MTcwMTQyMjI0NywicGF0aCI6Ii8xMDg0NDEwMjMvMjg3MDYyMjM0LTY5NTk2NmMyLTJhODQtNDRlMy04YjM0LTExNzE3YTRiOGU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwOTE3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTdiZGE2NTUyNjQzM2IxZjg1MjFjYTU0NzQ0OWEzMTQ2NmVhM2FkMmE5ZDE1MTI4YmVmMjM1ZTk0OTAyNmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wfXdEV1UTUENlybmne4ko415ANDgsKAKwc3r06lrp8s)
> 
> I'd like the buttons to use `flex-wrap reverse` so that they can be stacked on small screens

okay
