### ISSUE TITLE
Chapter 2 background colour makes green coding text difficult to read

### ISSUE THREAD

**Issue by aassoiants** [saving-satoshi/saving-satoshi#743]
See image below for context CC @GBKS 

![image](https://github.com/saving-satoshi/saving-satoshi/assets/126297088/7b176d7d-3f51-4990-a620-ae3b7357d9e0)

**Comment by GBKS** [comment]
Note how the code editor in the design below has an extra background (black with 15% opacity). That is helpful for creating the extra contrast to see the colored text better. It's missing in this screenshot above.

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/fcb43f4f-ea6f-4e16-8be9-b073ccf66aa0)

**Comment by aassoiants** [comment]
Yours looks a lot better - is that a change that's been made or you recommend us adding that extra black background with 15% opacity?

**Comment by benalleng** [comment]
it was a reminder to me to add that in :sweat_smile: I did however add it in #748 so take a look!

**Comment by aassoiants** [comment]
Looks good!
