### ISSUE TITLE
Chapter 4: Able to see code behind the code 👀 

### ISSUE THREAD

**Issue by aassoiants** [saving-satoshi/saving-satoshi#749]
After selecting all (CTRL + A), and pressing any other button after, am able to see the code that precedes the main copy and instructions starting with "// Import ECDSA library.." See vid for context [here](https://www.loom.com/share/bea01fec0fc241a5821a67a42d437974)

![image](https://github.com/saving-satoshi/saving-satoshi/assets/126297088/441ec62b-cd85-4c81-9a7d-b797c02fc992)

Was not able to replicate with Chapter 2 coding challenge.

**Comment by aassoiants** [comment]
Doesn't replicate in Chap4Chal1, subchallenge 2 
![image](https://github.com/saving-satoshi/saving-satoshi/assets/126297088/184c1976-18e1-4bb3-8440-6f4b317dbfbd)

**Comment by daviroo** [comment]
It's an easter egg 😆

**Comment by benalleng** [comment]
beacause of our need for some hidden code I do not think we can avoid this, like David says perhaps an easter egg for those wanting to see the hidden code on a given challenge. The page where you couldn't replicate it is because that challenge has no hidden code
