### ISSUE TITLE
Repl server still not back online

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#761]
While access to our progress routes are working again our repl api failed to start up again and we cannot run code through the backend

`[system] Error running container: connect ENOENT /var/run/docker.sock`

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/cd31d591-61e7-4dd0-9297-1c2388aa6abe)

**Comment by daviroo** [comment]
Docker wasn't installed on the server - I've installed it and it seems to be working now.
