### ISSUE TITLE
Chapter 6 Challenge 2 Transaction Class

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#771]
Implement Page 2 of Challenge 2

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/b16c65e9-053c-43f9-b085-4841f5d8ca4b)

https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=6401%3A18172&mode=dev

**Comment by sabakhilji** [comment]
@benalleng can I implement this?
