### ISSUE TITLE
Chapter 6 Challenge 2 Transaction Digest

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#772]
Implement the Transaction Digest Page

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/bb50e1bb-7eb0-4428-889c-9e1d54f715b9)

https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=6200%3A31627&mode=dev

**Comment by sabakhilji** [comment]
Hi @benalleng can I work on this?

**Comment by benalleng** [comment]
Sure!

**Comment by benalleng** [comment]
For speed Saba and practicing some save-load code features I'm going to go ahead and assign this one to myself
