### ISSUE TITLE
Storybook Repl

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#777]
I was wondering if it would be helpful to add a blank `<ScriptingChallenge/>` page outside of the standard progress to allow us to test arbitrary code while we are building out the content for a lesson. This is mostly directed at @pinheadmz, do you think you would ever use it when testing the challenge repo?

**Comment by pinheadmz** [comment]
I don't think I would need this, how would it be different from an actual challenge page?

**Comment by benalleng** [comment]
none, it would just be a blank scripting page to test the output from the prod repl server
