### ISSUE TITLE
Default REPL language should carry over from lesson to lesson

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#786]
If I use python in 1 challenge we should default the repl to python in the next challenge

Carry over from issue #784

**Comment by sabakhilji** [comment]
@benalleng  can we use local storage to store user's preferences in this case?

**Comment by benalleng** [comment]
Yeah, I think that could be a good approach, since it will generally only need to carry over within a chapter. 
Another approach would be to run a basic code on the loaded code to see if it contains some python or JS specific syntax to determine what language should be used

**Comment by sabakhilji** [comment]
will try both!

**Comment by benalleng** [comment]
The main code you are going to want to modify is here
```
  const config: EditorConfig = {
    defaultLanguage: 'python',
    languages: {
      javascript,
      python,
    },
  }
```

changing the defaultLanguage: from javascript to python and vice versa will load the page and then also disabling this code to prevent switching
```
  const handleSelectLanguage = (language: string) => {
    setLanguage(language)
  }
```
