### ISSUE TITLE
Adding german as a language option

### ISSUE THREAD

**Issue by bTCpy** [saving-satoshi/saving-satoshi#808]
**Describe the enhancement**
Hey everybody, I would like to provide a .ts file for the german language. I'm a native speaker and love this project.

**Code Snippet**
const translations = {
  shared: {
    next: 'Fortfahren',
    start: 'Start',
    copy: 'Kopieren',
    copy_acknowledged: 'Kopiert!',
    about: 'Über uns',
    chapter: 'Kapitel',
    chapters: 'Kapitel',
    challenge: 'Herausforderung',
.....

**Additional information**
I'm confident to provide the translated .ts file today or a least until the end of the week.

**Comment by 0tuedon** [comment]
> **Describe the enhancement** Hey everybody, I would like to provide a .ts file for the german language. I'm a native speaker and love this project.
> 
> **Code Snippet** const translations = { shared: { next: 'Fortfahren', start: 'Start', copy: 'Kopieren', copy_acknowledged: 'Kopiert!', about: 'Über uns', chapter: 'Kapitel', chapters: 'Kapitel', challenge: 'Herausforderung', .....
> 
> **Additional information** I'm confident to provide the translated .ts file today or a least until the end of the week.

Sounds great @bTCpy

**Comment by benalleng** [comment]
If you want to open a PR with the german file added go ahead! If you want we can add in some additional edits to get your translation working with the codebase

**Comment by benalleng** [comment]
Closed by #810
