### ISSUE TITLE
Keep chapter height consistent when tabbing (Chapters page)

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#83]
The height of each tab content is different. So when tabbing, the layout changes (medium-width screens). It should not. Best way to solve this is to place add a container with a the min-height set to the taller height of both tab contents. This requires us to render both (also the one not shown to the user at the moment). Not elegant (let me know if you have a better proposal - fixing the height does not work across responsive screen sizes and dynamic content), but the current layout jump is pretty unpleasant.

**Current behavior:**
![localhost_3000_chapters (2)](https://user-images.githubusercontent.com/695901/212651596-f47a44e0-b72a-4513-a7d8-bcc550c745ae.png)

![localhost_3000_chapters (3)](https://user-images.githubusercontent.com/695901/212651615-18d72716-0153-4778-97c9-9e792ecd4ecc.png)

Expected behavior is that the height remains the same, even when tabbing to the challenges.

**Comment by vinayaksh42** [comment]
I have created a PR for this issue.
