### ISSUE TITLE
Allow success state to be non boolean

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#830]
Currently the success state that allows the user to proceed is accepted as a boolean, either true or false, however with the current challenge having many possible successful solutions we should add a new way for the success state to be acheived.

perhaps creating a new success enum like so

```
export enum SuccessState {
  Idle = 0,
  Failed = 1,
  Poor = 2,
  Good = 3,
  Perfect = 4
}
```

The design is shown below from the [figma](https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?node-id=7100%3A70363&mode=dev)

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/8f6a9895-d87f-40be-b343-e4f8e30a27c3)

**Comment by sabakhilji** [comment]
Is this issue need some changes in the status bar component too? @benalleng

**Comment by benalleng** [comment]
Yeah! that would likely be where most of this change would occur though most of the lessons would also need to be moified to return a number instead of a true or false fvalue here but I would need to check once more exactly how our lessons look for success state
