### ISSUE TITLE
Add some pointer to show that the user should check out the help page

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#855]
Currently we have nothing that tells the user the help page exists, I think we could add a tooltip or pointer early on to show that the help page exists!

**Comment by GBKS** [comment]
How about this?

![image](https://github.com/saving-satoshi/saving-satoshi/assets/695901/4e63d610-36fb-461b-a5ef-02474bd03bad)

**Comment by daviroo** [comment]
@GBKS @benalleng I could take a look at this next if you would like?

**Comment by GBKS** [comment]
Thank you, sounds great (if everyone is OK with the design).
