### ISSUE TITLE
Chapter 8 Showtime!

### ISSUE THREAD

**Issue by benalleng** [saving-satoshi/saving-satoshi#901]
Populate chapter 8 challenge lesson 6

![image](https://github.com/saving-satoshi/saving-satoshi/assets/108441023/9d7ce205-4983-40d9-8aa2-72456a9b1728)

https://www.figma.com/file/LqjK3Tpvd9KJ4buFArCJBQ/Saving-Satoshi?type=design&node-id=7329-19199&mode=design&t=jLPYPgDRkFJphyCx-0

**Comment by 0tuedon** [comment]
Closed by pr #949
