### ISSUE TITLE
Disable viewport zoom

### ISSUE THREAD

**Issue by GBKS** [saving-satoshi/saving-satoshi#918]
When focusing the code editor on mobile, the screen currently zooms into that field (at least on mobile). This is an automatic browser behavior meant to help you focus on the edit task at hand. But in this case, it's just weird. Some of the UI is now cut off and it takes some messing around to get back to the full 100% view.

Solution would be to prevent this automatic zoom by updating the `viewport` tag to the following.

`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">`

It currently is:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

I could not figure out how to do this in Next, since it's not as easy as just putting that tag in the header (you end up with duplicate meta tags).

This would be a good one to get a test PR up and running to see if it fixes the behavior.

**Comment by benalleng** [comment]
What device/ browser does this occur on?

I couldn't reproduce this behavior on any android browser, but easy enough to still add this `maximum-scale` prop

**Comment by benalleng** [comment]
Looks like one major issue with preventing all duplicate viewport meta tags is that we have some metadata that is rendered with `use-client` there I figure I can just add this duplicate meta tag at the bottom and that will be used

**Comment by benalleng** [comment]
Perhaps in the future we can rethink these lesson page component being client side as opposed to server side

**Comment by GBKS** [comment]
Happens for me on iOS in chapter 2, challenge 2. Here's a [link](https://dev.savingsatoshi.com/en/chapters/chapter-2/scripting-2?dev=true).

https://github.com/saving-satoshi/saving-satoshi/assets/695901/6c586a28-5fe4-4c36-b308-975f0ca342c7

Since the code editor takes over the cursor events, I can only pinch and zoom out with my fingers on the top nav elements.
