### ISSUE TITLE
chapter 2 intro page locks on refresh

### ISSUE THREAD

**Issue by adamjonas** [saving-satoshi/saving-satoshi#925]
1. Pass chapter 1 and write down secret
2. Advance to chap 2 (see flash of a lock)
3. Refresh page
<img width="520" alt="Screenshot 2024-05-06 at 12 08 17 PM" src="https://github.com/saving-satoshi/saving-satoshi/assets/755825/c0e70973-e232-4ff7-873f-446d868b0502">

4. Go back to chap 1 outro page, click advance
5. Chapter 2 is unlocked again

**Comment by benalleng** [comment]
I noticed in our network tab that the account progress is at 'CH1OUT2' after following these steps while localStorage is at 'CH2INT1' @daviroo will #923 resolve this?

**Comment by daviroo** [comment]
> I noticed in our network tab that the account progress is at 'CH1OUT2' after following these steps while localStorage is at 'CH2INT1' @daviroo will #923 resolve this?

I think so yes.

**Comment by benalleng** [comment]
Closed by #923
