### ISSUE TITLE
Improve chapter-1/genesis wording and/or linking

### ISSUE THREAD

**Issue by satsdev** [saving-satoshi/saving-satoshi#93]
_I realize it may be somewhat early to suggest content changes so feel free to close this issue for now if preferred._

On chapter-1/genesis, there is a call to action in the 2nd sentence of the first paragraph stating "Go to a block explorer and search for '0'" (see screenshot 1). This will prompt some users to venture off to find their own block explorer via search engine. Not all block explorers show the ScriptSig HEX. It may be intuitive to link the text "a block explorer" to https://blockstream.info/ to save them the search, and guide them to the preferred block explorer.

Currently, it is possible to add a link into the markdown content, but the links do not have any distinctive link styling. Preferably this would have an underline or similar styling to show that it is a link (see screenshot 2).

Call to action / actionable content
![image](https://user-images.githubusercontent.com/123048299/213626865-9a59ce72-a06a-4b67-8214-51e3cdaf5c9f.png)

Example of hyperlink with underline
![image](https://user-images.githubusercontent.com/123048299/213627154-ab7c70fd-a357-4c41-b789-6ad785ebfb71.png)

**Comment by ecurrencyhodler** [comment]
There are a couple ways we could solve this based on [discussions in slack](https://bitcoindesign.slack.com/archives/C0442BRGJ5U/p1674184000304149): 

1. direct user to [this link](https://technicaldifficulties.io/2020/10/24/bitcoin-how-to-find-decode-the-genesis-blocks-hidden-message/)
2. embed video/gif into the challenge page as a tip

**Comment by GBKS** [comment]
This can be much improved by re-writing the copy on this challenge, and adding tool tips. For the tool tips, we still need to find a technical solution to make them possible, [see here](https://github.com/saving-satoshi/saving-satoshi/issues/62).

As it's a text change, we should address this in Google Docs or Notion and Figma first before implementing.

**Comment by ecurrencyhodler** [comment]
Closing this issue and moving it to "Done" as we have added tool tips and are in progress of revamping copy for Ch.1.
