### ISSUE TITLE
Site crashes on first page load

### ISSUE THREAD

**Issue by SamSamskies** [saving-satoshi/saving-satoshi#94]
**Describe the bug**
Site crashes on first page load. Refreshing the page fixes the problem.

**To Reproduce**

1. Open home page in incognito mode

**Screenshots and/or logs**

![Screenshot 2023-01-20 at 11 34 56 AM](https://user-images.githubusercontent.com/3655410/213766791-db2b00b7-2c88-447d-9c9a-614dc2251e5c.png)

![Screenshot 2023-01-20 at 11 40 01 AM](https://user-images.githubusercontent.com/3655410/213766894-4f78708f-5cea-42e1-9729-af0b0e049e91.png)

**Comment by SamSamskies** [comment]
Might be a good idea to include some basic e2e tests using something like [Cypress](https://www.cypress.io/) to help prevent bugs like this.

**Comment by SamSamskies** [comment]
Would also recommend setting up a bug reporting tool such as [Bugsnag](https://www.bugsnag.com/).

**Comment by satsdev** [comment]
I am able to reproduce this. Fix incoming.
