### ISSUE TITLE
Preserve code comments when solutions carry over to later lessons

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#945]
When reviewing the terminal reset PR, https://github.com/saving-satoshi/saving-satoshi/pull/939 I was made aware of this awesome feature we have where sometimes, your solution to a code challenge can show up in a subsequent challenge as pre-loaded code. 

For example, in [Chapter 6, Putting it all together, Build the transaction digest](https://savingsatoshi.com/en/chapters/chapter-6/put-it-together-1), you need to write a `Transaction.digest()` method that implements BIP-143. In the next challenge, [Build the witness class](https://savingsatoshi.com/en/chapters/chapter-6/put-it-together-2), your `Transaction.digest()` method appears as part of the pre-loaded starter code!

This is very cool. Being able to incrementally build up to the final challenge like this is really satisfying. It would be nice though if the code comments also carried over. Especially when we're working with these really complex and technical topics, code comments can make learning and referencing your old code a lot easier.

**Update**: here is where the comments are stripped out: https://github.com/saving-satoshi/saving-satoshi/blob/93016dfb92c8b4a5541aa23d41c733d7497518d6/ui/lesson/ScriptingChallenge/index.tsx#L139

I understand if there is a case to be made for trying to minimize the amount of user code persisted, or if sanitizing this user input helps things run more smoothly. I can accept if dropping code comments is an intentional choice.

**Comment by benalleng** [comment]
Curious what others @daviroo or @0tuedon think. We currently remove code comments because of the `// YOUR CODE HERE` throughout the game, but perhaps we could just target these comments instead of just removing all comments?

**Comment by 0tuedon** [comment]
Hmm, as @benalleng  said we removed the comments because of # YOUR CODE HERE. But I guess we could just target that?
