### ISSUE TITLE
Chapter 7, "Assemble a Block" - Issues with block weight instructions

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#951]
Chapter 7 tasks the player with successfully filling a block with transactions. They face several challenges in doing this: 
- they can't go over the max block weight
- they need to take into account that some transactions have parents that also need to be mined, and 
- ideally, the solution optimizes for fees

The first thing that needs to be done is to add a check for the block weight because the code that is initially presented to the player has a loop that just puts every transaction from the mempool into the block. In the mempool [JSON file](https://raw.githubusercontent.com/saving-satoshi/challenges/master/chapter7/javascript/mempool.json) provided, there is a `weight` property on each transaction. The only place that units are mentioned is the table, which says the transaction weights are in virtual bytes (vBytes). If you match the values up, this indeed appears to be true:

![Screenshot from 2024-05-21 14-07-53](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/8893c6b1-e44c-41ee-b499-1df35d2e95bd)

![Screenshot from 2024-05-21 14-11-01](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/cc597fc9-d3da-4436-8a0f-391b38bc293f)

It follows that checking for max block weight should then be done terms of vBytes. The max block weight is:

- 4 million weight units (WU), or
- 1 million vBytes

Source: https://bitcoinvisuals.com/chain-block-weight and Holocat from ChatBTC ;)

![Screenshot from 2024-05-17 23-48-51](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/21690a45-ae47-401c-9406-9d9967a68c28)

However, if you proceed to do this and set the max block size to 1 million in your code, your solution will never meet the threshold for even an "okay" answer because the solution checker is expecting a max block weight of [4 million](https://github.com/saving-satoshi/saving-satoshi/blob/3722b0fe21cca6ba29fc8e7dc90e873857909091/content/lessons/chapter-7/mempool-transaction-1.tsx#L99). Your answer ends up being off by about (probably a little less in practice) a factor of 4!

4 million WU makes more sense instead of 1 million vBytes because [WU is used for](https://learnmeabitcoin.com/technical/transaction/size/) adding transactions to a block. Many people are probably familiar with vBytes though because that's what is used for calculating fees. And honestly, I bet a lot of people don't even realize there are two ways to measure the weight of a transaction.

This leads me to several questions:

1. What is the unit for the weight of the transactions in the JSON file? I can't claim to have a sixth sense for this, but those numbers do seem to be WU. If it really is vBytes, should we have the player convert the weight from vBytes to WU? I guess it wouldn't matter as long as their code was checking against the appropriate definition of block weight.
2. The answer in the [Learning Resources/help page](https://savingsatoshi.com/en/chapters/chapter-7/mempool-transaction-1/help) uses a `MAX_BLOCK_WEIGHT` constant but it isn't defined anywhere. Should the solution include the definition of this, or should the `MAX_BLOCK_WEIGHT` constant be provided in the pre-loaded code for the challenge?
3. Was any of this by design to add a layer of learning that talks about the differences between WU, vBytes, and the history of vBytes (aka Segwit)? 

Filing this as a bug because I think we need to add some clarification about block weight at least somewhere in the challenge. The easiest thing to do is define `MAX_BLOCK_WEIGHT = 4000000` for the player, and to change the table to say the transaction weights are in WU (or not, and let the user do the conversion). 

I'm happy to implement whatever fix is appropriate here and welcome any feedback on the direction things should go. I spent more time than I'd like to admit trying to optimize a solution that checked against 1million vBytes for max block weight and was insulted for a bit knowing this challenge had a special message for the folks that got perfect answers :laughing:. I would not wish that upon anyone else!

**Comment by benalleng** [comment]
@pinheadmz I think I need your feedback on this before I can make any actionable issue for the rest, but the `MAX_BLOCK_WEIGHT = 4000000` issue definitely can be addressed
I think as an oversight I hid the in the validation here https://github.com/saving-satoshi/saving-satoshi/blob/dev/content/lessons/chapter-7/mempool-transaction-1.tsx#L99C1-L99C34

**Comment by benalleng** [comment]
Or maybe add an introductory copy page that introduces mempools and the concepts in the lesson a little more?

**Comment by benalleng** [comment]
also the first transaction has the wrong weight, looks like it should be 2020
