### ISSUE TITLE
Remove Scroll Bar on "Need Help" Mouse Over

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#980]
![Screenshot from 2024-06-10 21-23-59](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/6fcef1a6-6fdb-43d3-b251-0828d8eece45)

Is it possible to remove the scroll bar on this "Need Help?" mouse over? I noticed the other mouse overs (for the other sections in a chapter) also have scroll bars when the list of items isn't long enough to require scrolling. I know scroll bars may be necessary for some displays like mobile, but if it's not too much trouble to make these go away when they aren't needed it will make the game look more polished.

**Comment by satsie** [comment]
haha yes, for all of the drop down menus here. You mean other people don't see this? I'm using Chrome for Linux 124.0.6367.201

**Comment by satsie** [comment]
I get it on challenge instructions too :sweat_smile: 

![Screenshot from 2024-06-11 21-55-54](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/3c9d394c-ab5a-4e86-a72d-fd754530fd74)

**Comment by benalleng** [comment]
Is it actually scrollable or is it just an empty scroll bar?

**Comment by benalleng** [comment]
Do you see overflow tags on those elements when you inspect the page?

**Comment by benalleng** [comment]
Ok it might be that I've added `overflow: scroll;` instead of `overflow: auto;` going to make a PR first thing in the morning to see if that fixes some of these

**Comment by satsie** [comment]
> Ok it might be that I've added `overflow: scroll;` instead of `overflow: auto;` in some areas going to make a PR first thing in the morning to see if that fixes some of these

That just fixed it! I changed it in the inspect console and it looks great!
