### ISSUE TITLE
Horizontal Scrolling occurring on multiple pages (About, Chapters)

### ISSUE THREAD

**Issue by vinayaksh42** [saving-satoshi/saving-satoshi#99]
**Describe the bug**
Horizontal Scrolling occurring on multiple pages (About, Chapters)

**To Reproduce**

1. Go to 'https://savingsatoshi.com/chapters or https://savingsatoshi.com/about'
2. See the error

**Screenshots**
![Screenshot 2023-01-22 at 7 18 33 AM (2)](https://user-images.githubusercontent.com/54861487/213897151-0f42f9d6-8be2-4366-a144-e591263e5755.png)
<img width="1512" alt="Screenshot 2023-01-22 at 7 19 04 AM" src="https://user-images.githubusercontent.com/54861487/213897152-bc5bf605-a791-4011-9492-cf6064a32a9d.png">

**Additional context**
Changing `w-screen` to `w-full` fixes the issue

**Comment by GBKS** [comment]
I can't reproduce this one, but what you're describing makes logical sense. The issue could be an element having `w-screen` and left/right padding without `box-model` set to `border-box`. That would make the element width 100% of the viewport plus the left/right padding, leading to a scrollbar.

Overall, we're totally overusing `w-screen` in the codebase. It should almost never be needed, maybe for the root element in overlays or sticky elements. Something to clean up at some point.
