### ISSUE TITLE
Chapter 8: Bug in a success message

### ISSUE THREAD

**Issue by satsie** [saving-satoshi/saving-satoshi#991]
https://savingsatoshi.com/en/chapters/chapter-8/building-blocks-6

![Screenshot from 2024-06-17 22-38-38](https://github.com/saving-satoshi/saving-satoshi/assets/1823216/2d8864d7-c73f-477a-bcbe-2ac619933ab7)

`(get subsidy)` should be `getSubsidy` (JS) or `get_subsidy` (Python)

**Comment by benalleng** [comment]
Closed by #1000
